"""
Vigile — Insights Manager

Implements the 3-phase insights and profiling system:
  - Phase 1: structured LLM profiling and fallback heuristic rules
  - Phase 2: real-time rule-based insights (disk regression, CPU/RAM thresholds)
  - Phase 3: real-time diagnostic LLM analysis for anomalies
"""

import asyncio
import enum
import json
import logging
import re
import time
from typing import Any

import aiosqlite
from pydantic import BaseModel, Field

from master.core.llm_client import LLMClient
from master.core.node_manager import NodeManager
from master.core.structured_llm import StructuredLLM
from master.core.plugin_manager import PluginManager

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data Models for Node Profile
# ---------------------------------------------------------------------------


class HeavyProcessConfig(BaseModel):
    container_name: str | None = Field(default=None)
    service_name: str | None = Field(default=None)
    cpu_threshold_percent: float = Field(
        description="CPU percentage threshold above which this is considered active"
    )
    label: str = Field(description="Human-friendly label")


class ServiceCategory(str, enum.Enum):
    MEDIA = "media"
    DATABASE = "database"
    LLM = "llm"
    REVERSE_PROXY = "reverse_proxy"
    CI_CD = "ci_cd"
    SYSTEM = "system"
    MONITORING = "monitoring"
    OTHER = "other"


class PluginPattern(BaseModel):
    container_pattern: str | None = Field(default=None, description="Regex pattern for container name/image")
    service_pattern: str | None = Field(default=None, description="Regex pattern for systemd service name")
    category: ServiceCategory
    label: str
    cpu_threshold_percent: float


class ClassifiedService(BaseModel):
    name: str
    service_type: str
    category: ServiceCategory
    label: str
    cpu_threshold_percent: float


class NodeServiceClassification(BaseModel):
    services: list[ClassifiedService]
    context_label: str
    baseline_ram_percent: float


def _guess_context(hostname: str, containers: list[dict[str, Any]]) -> str:
    host_lower = hostname.lower()
    if "web" in host_lower:
        return "Serveur Web / Applicatif"
    elif "db" in host_lower or "sql" in host_lower:
        return "Serveur de Base de Données"
    elif "media" in host_lower or "nas" in host_lower:
        return "Homelab Médias & Stockage"
    return "Serveur général"


class NodeProfile(BaseModel):
    node_id: str
    known_heavy_processes: list[HeavyProcessConfig] = Field(default_factory=list)
    baseline_ram_percent: float = Field(
        default=70.0, description="Expected baseline RAM utilization percentage"
    )
    context_label: str = Field(
        default="Serveur homelab", description="Overall context label of the node"
    )


# ---------------------------------------------------------------------------
# Pydantic schema for Phase 3 Diagnostic Analysis
# ---------------------------------------------------------------------------


class DiagnosticReport(BaseModel):
    """Structured diagnostic report generated by LLM on demand during anomaly."""

    headline: str = Field(description="Short human-friendly summary of the diagnostic")
    explanation: str = Field(description="Detailed explanation of what is causing the load")
    suggested_action: str = Field(description="Remediation action recommended for the user")


# ---------------------------------------------------------------------------
# Insights Manager
# ---------------------------------------------------------------------------


class InsightsManager:
    """
    Manages node profiling, real-time insights generation, and anomaly diagnostics.
    Follows Dependency Injection: receives LLMClient and PluginManager inside constructor.
    """

    def __init__(self, llm_client: LLMClient | None = None, plugin_manager: PluginManager | None = None) -> None:
        self._llm_client = llm_client
        self._sllm = StructuredLLM(llm_client) if llm_client else None
        self._plugin_manager = plugin_manager

    # -----------------------------------------------------------------------
    # Phase 1: Profile Generation
    # -----------------------------------------------------------------------

    async def generate_profile(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        nm: NodeManager,
        force: bool = False,
        locale: str = "fr",
    ) -> NodeProfile:
        logger.info("Generating profile for node %s (force=%s)...", node_id, force)

        node = await nm.get_node(db, node_id)
        if not node:
            raise ValueError(f"Node not found: {node_id}")

        hostname = node.get("hostname") or ""

        services: list[dict[str, Any]] = []
        containers: list[dict[str, Any]] = []

        cached_services = node.get("cached_services_json")
        if cached_services:
            try:
                services = json.loads(cached_services)
            except Exception:
                pass

        cached_containers = node.get("cached_containers_json")
        if cached_containers:
            try:
                containers = json.loads(cached_containers)
            except Exception:
                pass

        if node.get("online"):
            if not services:
                try:
                    from master.core.plugin_helpers import parse_service_list

                    result = await self._auto_profiling_intent(
                        node_id, "LIST_SERVICES", {}, nm, db, timeout=8.0
                    )
                    if result.get("success"):
                        parsed = parse_service_list(result.get("output", ""))
                        if parsed:
                            services = parsed
                except Exception as e:
                    logger.warning("Profile gen: failed live services query: %s", e)

            if not containers:
                try:
                    from master.core.plugin_helpers import parse_container_list

                    result = await self._auto_profiling_intent(
                        node_id, "LIST_CONTAINERS", {}, nm, db, timeout=8.0
                    )
                    if result.get("success"):
                        parsed = parse_container_list(result.get("output", ""))
                        if parsed:
                            containers = parsed
                except Exception as e:
                    logger.warning("Profile gen: failed live containers query: %s", e)

        classification = await self.classify_node_services(
            node_id, db, nm, locale=locale, services=services, containers=containers
        )

        context_label = classification.context_label
        baseline_ram_percent = classification.baseline_ram_percent

        known_heavy = [
            HeavyProcessConfig(
                container_name=s.name if s.service_type == "container" else None,
                service_name=s.name if s.service_type == "systemd" else None,
                cpu_threshold_percent=s.cpu_threshold_percent,
                label=s.label,
            )
            for s in classification.services
        ]

        profile = NodeProfile(
            node_id=node_id,
            known_heavy_processes=known_heavy,
            baseline_ram_percent=baseline_ram_percent,
            context_label=context_label,
        )

        logger.info("Profile ready for node %s", node_id)

        now = time.time()
        await db.execute(
            """
            UPDATE nodes SET
                insight_profile = ?,
                insight_profile_generated_at = ?,
                cached_services_json = ?,
                cached_containers_json = ?
            WHERE id = ?
            """,
            (
                profile.model_dump_json(),
                now,
                json.dumps(services) if services else node.get("cached_services_json"),
                json.dumps(containers) if containers else node.get("cached_containers_json"),
                node_id,
            ),
        )
        await db.commit()

        return profile

    async def _auto_profiling_intent(
        self,
        node_id: str,
        action: str,
        params: dict[str, Any],
        nm: NodeManager,
        db: aiosqlite.Connection,
        timeout: float = 8.0,
    ) -> dict[str, Any]:
        """
        Create, auto-approve, execute, and complete a profiling intent.

        Read-only profiling intents (LIST_SERVICES, LIST_CONTAINERS) are
        auto-approved by 'system' — no human operator needed — but are still
        tracked through ActionProposal for audit trail consistency.
        """
        from master.core.action_proposal import ActionProposal
        from master.core.audit import AuditAction, log_action

        proposal = ActionProposal(
            node_id=node_id,
            action=action,
            params=params,
            reasoning="Profiling intent (auto-approved, read-only).",
            risk_level="LOW",
            created_by="insights",
            status="APPROVED",
            approved_by="system",
        )

        data = proposal.to_db_dict()
        await db.execute(
            """INSERT INTO action_proposals
               (id, node_id, action, params_json, reasoning, risk_level,
                status, created_by, approved_by, created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                data["id"], data["node_id"], data["action"], data["params_json"],
                data["reasoning"], data["risk_level"],
                data["status"], data["created_by"], data["approved_by"],
                data["created_at"], data["updated_at"],
            ),
        )
        await db.commit()

        try:
            result = await nm.send_intent(
                node_id, {"action": action, "params": params}, timeout=timeout
            )
            success = result.get("success", False)
            proposal.complete(success=success, result_data=result)
        except RuntimeError as exc:
            proposal.complete(success=False, result_data={"error": str(exc)})
            result = {"success": False, "error": str(exc)}
        except TimeoutError:
            proposal.complete(success=False, result_data={"error": "worker_timeout"})
            result = {"success": False, "error": "Worker did not respond in time"}

        db_data = proposal.to_db_dict()
        await db.execute(
            """UPDATE action_proposals SET
                status = ?, updated_at = ?, executed_at = ?, result_json = ?
               WHERE id = ?""",
            (
                db_data["status"], db_data["updated_at"],
                db_data["executed_at"], db_data["result_json"],
                proposal.id,
            ),
        )
        await db.commit()

        await log_action(
            db,
            user_id="system",
            action=AuditAction.AUTOMATION_TRIGGERED,
            node_id=node_id,
            details={
                "proposal_id": proposal.id,
                "action": action,
                "status": proposal.status,
            },
        )

        return result

    def _get_plugin_patterns(self) -> list[PluginPattern]:
        if not self._plugin_manager:
            return []
        try:
            results = self._plugin_manager.call("get_heavy_process_patterns")
            patterns = []
            for result in results:
                if isinstance(result, list):
                    for item in result:
                        if isinstance(item, dict):
                            patterns.append(PluginPattern(**item))
                        elif isinstance(item, PluginPattern):
                            patterns.append(item)
                elif isinstance(result, PluginPattern):
                    patterns.append(result)
            return patterns
        except Exception as e:
            logger.debug("Failed to collect plugin patterns: %s", e)
            return []

    def _classify_services_fallback(
        self,
        services: list[dict[str, Any]],
        containers: list[dict[str, Any]],
    ) -> list[HeavyProcessConfig]:
        known_heavy: list[HeavyProcessConfig] = []
        plugin_patterns = self._get_plugin_patterns()

        for c in containers:
            c_name = c.get("name", "")
            c_image = c.get("image", "")
            for pattern in plugin_patterns:
                if pattern.container_pattern:
                    if re.search(pattern.container_pattern, c_name.lower()) or re.search(pattern.container_pattern, c_image.lower()):
                        known_heavy.append(
                            HeavyProcessConfig(
                                container_name=c_name,
                                cpu_threshold_percent=pattern.cpu_threshold_percent,
                                label=pattern.label,
                            )
                        )
                        break

        for s in services:
            s_name = s.get("name", "")
            for pattern in plugin_patterns:
                if pattern.service_pattern:
                    if re.search(pattern.service_pattern, s_name.lower()):
                        known_heavy.append(
                            HeavyProcessConfig(
                                service_name=s_name,
                                cpu_threshold_percent=pattern.cpu_threshold_percent,
                                label=pattern.label,
                            )
                        )
                        break

        return known_heavy

    async def classify_node_services(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        nm: NodeManager,
        locale: str = "fr",
        services: list[dict[str, Any]] | None = None,
        containers: list[dict[str, Any]] | None = None,
    ) -> NodeServiceClassification:
        logger.info("Classifying services for node %s...", node_id)
        node = await nm.get_node(db, node_id)
        if not node:
            raise ValueError(f"Node not found: {node_id}")

        hostname = node.get("hostname") or ""

        if services is None:
            services = []
            cached = node.get("cached_services_json")
            if cached:
                try:
                    services = json.loads(cached)
                except Exception:
                    pass

        if containers is None:
            containers = []
            cached = node.get("cached_containers_json")
            if cached:
                try:
                    containers = json.loads(cached)
                except Exception:
                    pass

        if self._sllm and self._llm_client and self._llm_client.base_url:
            lang = (
                "Write the label and context_label in English."
                if locale == "en"
                else "Écris le label et le context_label en français."
            )
            try:
                messages = [
                    {
                        "role": "user",
                        "content": (
                            f"Classify every container and service running on server '{node.get('name')}'.\n\n"
                            f"Systemd services:\n{json.dumps(services[:30], indent=2)}\n\n"
                            f"Docker containers (with image):\n{json.dumps(containers[:30], indent=2)}\n\n"
                            f"For each entry, determine:\n"
                            f"- category: one of {[e.value for e in ServiceCategory]}\n"
                            f"- label: short human-friendly description in French\n"
                            f"- cpu_threshold_percent: CPU % above which this process is considered actively loaded "
                            f"(e.g. 50 for Plex transcoding, 30 for a reverse proxy, 40 for a database)\n"
                            f"- service_type: \"container\" or \"systemd\"\n\n"
                            f"Also suggest:\n"
                            f"- context_label: overall role of this server (e.g. \"Serveur Médias\", \"Base de Données\", \"Passerelle LLM\")\n"
                            f"- baseline_ram_percent: normal baseline RAM usage for this server\n\n"
                            f"{lang}"
                        ),
                    }
                ]
                result = await self._sllm.create(
                    response_model=NodeServiceClassification,
                    messages=messages,
                    max_retries=2,
                )
                logger.info("LLM classification successful for node %s", node_id)
                return result
            except Exception as ex:
                logger.warning("LLM classification failed for node %s: %s", node_id, ex)

        known_heavy = self._classify_services_fallback(services, containers)
        context = _guess_context(hostname, containers)
        classified = [
            ClassifiedService(
                name=h.container_name or h.service_name or "",
                service_type="container" if h.container_name else "systemd",
                category=ServiceCategory.OTHER,
                label=h.label,
                cpu_threshold_percent=h.cpu_threshold_percent,
            )
            for h in known_heavy
        ]
        return NodeServiceClassification(
            services=classified,
            context_label=context,
            baseline_ram_percent=65.0,
        )

    def generate_fallback_profile(
        self,
        node_id: str,
        hostname: str,
        services: list[dict[str, Any]],
        containers: list[dict[str, Any]],
    ) -> NodeProfile:
        known_heavy = self._classify_services_fallback(services, containers)
        context = _guess_context(hostname, containers)
        return NodeProfile(
            node_id=node_id,
            known_heavy_processes=known_heavy,
            baseline_ram_percent=65.0,
            context_label=context,
        )

    # -----------------------------------------------------------------------
    # Phase 2: Real-time Insights (Deterministic)
    # -----------------------------------------------------------------------

    async def get_insights(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        nm: NodeManager,
        locale: str = "fr",
    ) -> dict[str, Any]:
        """
        Produce real-time insights for a node (Phase 2).
        Calculates disk slope on-the-fly and evaluates current CPU/RAM.
        """
        node = await nm.get_node(db, node_id)
        if not node:
            return {"node_id": node_id, "insights": [], "profile_confidence": "low"}

        # 1. Trigger profile generation automatically if missing and online
        profile_json = node.get("insight_profile")
        if not profile_json:
            if node.get("online"):
                # Spawn generation background task
                asyncio.create_task(self.generate_profile(node_id, db, nm, locale=locale))
                return {
                    "node_id": node_id,
                    "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "insights": [
                        {
                            "type": "status",
                            "severity": "info",
                            "icon": "🔄",
                            "headline": "Analyse du profil en cours",
                            "detail": "Vigilbot identifie les services et configure les seuils de charge...",
                        }
                    ],
                    "profile_confidence": "low",
                }
            else:
                return {
                    "node_id": node_id,
                    "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "insights": [
                        {
                            "type": "status",
                            "severity": "warning",
                            "icon": "⚠️",
                            "headline": "Profil manquant",
                            "detail": "Le serveur doit être connecté en ligne pour initialiser son profil d'insights.",
                        }
                    ],
                    "profile_confidence": "low",
                }

        profile = NodeProfile.model_validate_json(profile_json)

        # 2. Get latest metrics snapshot
        latest_snap = None
        async with db.execute(
            "SELECT * FROM metrics_snapshots WHERE node_id = ? ORDER BY collected_at DESC LIMIT 1",
            (node_id,),
        ) as cursor:
            row = await cursor.fetchone()
            if row:
                latest_snap = dict(row)

        if not latest_snap:
            return {
                "node_id": node_id,
                "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "insights": [
                    {
                        "type": "status",
                        "severity": "warning",
                        "icon": "🔄",
                        "headline": "En attente de métriques",
                        "detail": "Aucun rapport de métriques n'a encore été stocké pour ce serveur.",
                    }
                ],
                "profile_confidence": "medium",
            }

        insights = []

        # --- A. DISK INSIGHT (On-the-fly Linear Regression) ---
        disk_insight = await self._calculate_disk_insight(node_id, db, latest_snap)
        if disk_insight:
            insights.append(disk_insight)

        # --- B. CPU INSIGHT ---
        cpu_insight = self._calculate_cpu_insight(latest_snap, profile, node, locale=locale)
        if cpu_insight:
            insights.append(cpu_insight)

        # --- C. RAM INSIGHT ---
        ram_insight = self._calculate_ram_insight(latest_snap, profile, locale=locale)
        if ram_insight:
            insights.append(ram_insight)

        return {
            "node_id": node_id,
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "insights": insights,
            "profile_confidence": "high" if node.get("online") else "medium",
        }

    async def _calculate_disk_insight(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        latest_snap: dict[str, Any],
    ) -> dict[str, Any] | None:
        """Calculate linear regression slope of disk usage and return insight."""
        disk_total = latest_snap.get("disk_total_bytes", 0)
        disk_used = latest_snap.get("disk_used_bytes", 0)
        disk_percent = latest_snap.get("disk_percent", 0.0)

        if disk_total == 0:
            return None

        # Query metrics snapshots from the last 24 hours (86400 seconds)
        now = time.time()
        limit_time = now - 86400

        snapshots = []
        async with db.execute(
            """
            SELECT collected_at, disk_used_bytes
            FROM metrics_snapshots
            WHERE node_id = ? AND collected_at >= ?
            ORDER BY collected_at ASC
            LIMIT 150
            """,
            (node_id, limit_time),
        ) as cursor:
            async for r in cursor:
                snapshots.append(dict(r))

        free_bytes = disk_total - disk_used
        free_gb = free_bytes / (1024**3)
        used_percent = round(disk_percent, 1)

        # Calculate slope only with enough snapshots AND sufficient time span.
        # With fewer points (or a very short window), filesystem noise yields
        # absurd extrapolations (e.g. +39000 GB/day from a 60s delta).
        slope = 0.0  # GB per day
        min_snapshots = 5
        min_timespan_seconds = 1800  # 30 minutes
        timespan = (
            (snapshots[-1]["collected_at"] - snapshots[0]["collected_at"])
            if len(snapshots) >= 2
            else 0
        )
        if len(snapshots) >= min_snapshots and timespan >= min_timespan_seconds:
            t0 = snapshots[0]["collected_at"]
            # Convert collected_at to days relative to first snapshot to avoid floating overflow
            x = [(s["collected_at"] - t0) / 86400.0 for s in snapshots]
            y = [s["disk_used_bytes"] / (1024**3) for s in snapshots]

            n = len(snapshots)
            sum_x = sum(x)
            sum_y = sum(y)
            sum_xx = sum(xi * xi for xi in x)
            sum_xy = sum(xi * yi for xi, yi in zip(x, y))

            denominator = n * sum_xx - sum_x * sum_x
            if abs(denominator) > 1e-6:
                slope = (n * sum_xy - sum_x * sum_y) / denominator
                if slope < 0.0:
                    slope = 0.0  # Ignore shrinking disk for the "full in" prediction
            else:
                slope = 0.0

        if slope > 0.01:  # Growth rate of at least 10 MB per day
            days_left = free_gb / slope

            if days_left < 14:
                severity = "critical"
                icon = "🚨"
            elif days_left < 60:
                severity = "warning"
                icon = "⚠️"
            else:
                severity = "ok"
                icon = "✅"

            # Human friendly time estimation
            if days_left < 1:
                headline = "Disque plein dans moins d'un jour !"
            elif days_left < 7:
                headline = f"Disque plein dans ~{round(days_left)} jours"
            else:
                weeks = int(days_left / 7)
                days = int(days_left % 7)
                if weeks < 5:
                    day_str = f" et {days}j" if days > 0 else ""
                    headline = f"Disque plein dans {weeks} sem{day_str}"
                else:
                    months = int(days_left / 30)
                    headline = f"Disque plein dans ~{months} mois"

            detail = f"Taux de croissance de +{slope:.2f} Go / jour"
        else:
            severity = "ok"
            icon = "✅"
            headline = "Disque stable"
            detail = "Plus de 6 mois d'autonomie restants"

        return {
            "type": "disk",
            "severity": severity,
            "icon": icon,
            "headline": headline,
            "detail": detail,
            "raw": {
                "used_percent": used_percent,
                "free_gb": round(free_gb, 1),
                "growth_gb_per_day": round(slope, 3),
            },
        }

    def _calculate_cpu_insight(
        self,
        latest_snap: dict[str, Any],
        profile: NodeProfile,
        node: dict[str, Any],
        locale: str = "fr",
    ) -> dict[str, Any]:
        """Match current CPU load against node profile rules and active processes."""
        cpu_percent = latest_snap.get("cpu_percent", 0.0)

        top_procs: list[dict[str, Any]] = []
        raw_top = latest_snap.get("top_processes_json")
        if isinstance(raw_top, str):
            try:
                top_procs = json.loads(raw_top)
            except Exception:
                pass
        elif isinstance(latest_snap.get("top_processes"), list):
            top_procs = latest_snap["top_processes"]

        active_containers = []
        cached_containers = node.get("cached_containers_json")
        if cached_containers:
            try:
                active_containers = [
                    c.get("name")
                    for c in json.loads(cached_containers)
                    if c.get("state") == "running" or "up" in c.get("status", "").lower()
                ]
            except Exception:
                pass

        active_services = []
        cached_services = node.get("cached_services_json")
        if cached_services:
            try:
                active_services = [
                    s.get("service")
                    for s in json.loads(cached_services)
                    if s.get("state") == "active"
                ]
            except Exception:
                pass

        culprit = None
        culprit_pct: float | None = None
        culprit_ram_pct: float | None = None
        headline = "Stable CPU" if locale == "en" else "CPU stable"
        detail = "Server calm and stable" if locale == "en" else "Serveur calme et stable"
        icon = "💤"

        # Phase 1: Find all running heavy processes
        running_heavy: list[HeavyProcessConfig] = []
        for p in profile.known_heavy_processes:
            is_running = False
            if p.container_name and p.container_name in active_containers:
                is_running = True
            elif p.service_name and p.service_name in active_services:
                is_running = True

            if is_running:
                running_heavy.append(p)

        # Phase 2: Match running heavy processes against actual CPU usage from top_processes
        # Priority: use ACTUAL CPU usage, not threshold value
        if running_heavy and top_procs:
            best_actual_cpu = -1.0
            for p in running_heavy:
                p_name = (p.container_name or p.service_name or "").lower()
                for tp in top_procs:
                    tp_name = tp.get("name", "").lower()
                    tp_cpu = tp.get("cpu_percent", 0.0)
                    if (p_name in tp_name or tp_name in p_name) and tp_cpu >= p.cpu_threshold_percent:
                        if tp_cpu > best_actual_cpu:
                            best_actual_cpu = tp_cpu
                            culprit = p
                            culprit_pct = tp_cpu
                            mem_total = latest_snap.get("mem_total_bytes", 0)
                            if mem_total > 0 and tp.get("mem_rss_kb"):
                                culprit_ram_pct = (tp["mem_rss_kb"] * 1024) / mem_total * 100
                            else:
                                culprit_ram_pct = None
                        break

        # Phase 3: If no heavy process matched but CPU is high, use the top process directly
        if not culprit and top_procs and cpu_percent > 40:
            top = top_procs[0]
            top_cpu = top.get("cpu_percent", 0.0)
            if top_cpu > 10:
                culprit_pct = top_cpu
                mem_total = latest_snap.get("mem_total_bytes", 0)
                if mem_total > 0 and top.get("mem_rss_kb"):
                    culprit_ram_pct = (top["mem_rss_kb"] * 1024) / mem_total * 100

        # Filter out culprit if its resource consumption is negligible (both CPU and RAM < 5.0%)
        if culprit:
            cpu_val = culprit_pct if culprit_pct is not None else cpu_percent
            ram_val = culprit_ram_pct if culprit_ram_pct is not None else 0.0
            if cpu_val < 5.0 and ram_val < 5.0:
                culprit = None

        if cpu_percent > 75:
            if culprit:
                severity = "warning"
                icon = "🔥"
                raw_name = culprit.container_name or culprit.service_name or culprit.label or "inconnu"
                culprit_display_name = raw_name[0].upper() + raw_name[1:] if raw_name else "Inconnu"
                cpu_val = culprit_pct if culprit_pct is not None else cpu_percent
                ram_val = culprit_ram_pct if culprit_ram_pct is not None else 0.0

                resource_parts = []
                if cpu_val >= 5.0:
                    resource_parts.append(f"{cpu_val:.0f}% CPU" if locale == "en" else f"{cpu_val:.0f}% du processeur")
                if ram_val >= 5.0:
                    resource_parts.append(f"{ram_val:.0f}% RAM" if locale == "en" else f"{ram_val:.0f}% de la RAM")
                
                resource_str = (" and " if locale == "en" else " et ").join(resource_parts)
                headline = f"Intense activity · {culprit_display_name}" if locale == "en" else f"Activité intense · {culprit_display_name}"
                if resource_str:
                    detail = f"Service '{raw_name}' uses {resource_str}." if locale == "en" else f"Le service '{raw_name}' utilise {resource_str}."
                else:
                    detail = f"Service '{raw_name}' is active." if locale == "en" else f"Le service '{raw_name}' est actif."
            elif top_procs and top_procs[0].get("cpu_percent", 0) > 10:
                severity = "warning"
                icon = "⚠️"
                top = top_procs[0]
                headline = "Unusually high load" if locale == "en" else "Charge élevée anormale"
                detail = f"Active process {top['name']} ({top['cpu_percent']:.0f}%)" if locale == "en" else f"Processus {top['name']} actif ({top['cpu_percent']:.0f}%)"
            else:
                severity = "warning"
                icon = "⚠️"
                headline = "Unusually high load" if locale == "en" else "Charge élevée anormale"
                detail = "No known heavy process is active." if locale == "en" else "Aucun processus lourd connu n'est actif sur le système."
        elif cpu_percent > 40:
            if culprit:
                severity = "info"
                icon = "⚡"
                raw_name = culprit.container_name or culprit.service_name or culprit.label or "inconnu"
                culprit_display_name = raw_name[0].upper() + raw_name[1:] if raw_name else "Inconnu"
                cpu_val = culprit_pct if culprit_pct is not None else cpu_percent
                ram_val = culprit_ram_pct if culprit_ram_pct is not None else 0.0

                resource_parts = []
                if cpu_val >= 5.0:
                    resource_parts.append(f"{cpu_val:.0f}% CPU" if locale == "en" else f"{cpu_val:.0f}% du processeur")
                if ram_val >= 5.0:
                    resource_parts.append(f"{ram_val:.0f}% RAM" if locale == "en" else f"{ram_val:.0f}% de la RAM")
                
                resource_str = (" and " if locale == "en" else " et ").join(resource_parts)
                headline = f"Moderate load · {culprit_display_name}" if locale == "en" else f"Charge modérée · {culprit_display_name}"
                if resource_str:
                    detail = f"Service '{raw_name}' uses {resource_str}." if locale == "en" else f"Le service '{raw_name}' utilise {resource_str}."
                else:
                    detail = f"Service '{raw_name}' is active." if locale == "en" else f"Le service '{raw_name}' est actif."
            elif top_procs and top_procs[0].get("cpu_percent", 0) > 5:
                severity = "info"
                icon = "🏃"
                top = top_procs[0]
                headline = "Moderate activity" if locale == "en" else "Activité modérée"
                detail = f"Active process {top['name']} ({top['cpu_percent']:.0f}%)" if locale == "en" else f"Processus {top['name']} actif ({top['cpu_percent']:.0f}%)"
            else:
                severity = "info"
                icon = "🏃"
                headline = "Moderate activity" if locale == "en" else "Activité modérée"
                detail = f"General server load at {cpu_percent:.0f}%" if locale == "en" else f"Charge générale du serveur à {cpu_percent:.0f}%"
        else:
            severity = "ok"
            icon = "✅"
            headline = "Stable CPU" if locale == "en" else "CPU stable"
            detail = "Server calm and stable" if locale == "en" else "Serveur calme et stable"

        return {
            "type": "cpu",
            "severity": severity,
            "icon": icon,
            "headline": headline,
            "detail": detail,
            "raw": {
                "cpu_percent": round(cpu_percent, 1),
                "culprit_container": culprit.container_name if culprit else None,
                "culprit_service": culprit.service_name if culprit else None,
                "top_processes": top_procs[:5] if top_procs else None,
            },
        }

    def _calculate_ram_insight(
        self,
        latest_snap: dict[str, Any],
        profile: NodeProfile,
        locale: str = "fr",
    ) -> dict[str, Any]:
        """Assess RAM and swap usage against profile baseline."""
        mem_percent = latest_snap.get("mem_percent", 0.0)
        mem_total = latest_snap.get("mem_total_bytes", 0)
        mem_used = latest_snap.get("mem_used_bytes", 0)
        swap_used = latest_snap.get("swap_used_bytes", 0)

        used_gb = mem_used / (1024**3)
        total_gb = mem_total / (1024**3)
        swap_mb = swap_used / (1024 * 1024)

        baseline = profile.baseline_ram_percent

        if mem_percent > 90:
            severity = "warning"
            icon = "⚠️"
            headline = "RAM nearly full" if locale == "en" else "RAM presque saturée"
            detail = "Potential slow down risk (OOM)" if locale == "en" else "Risque potentiel de ralentissement (OOM)"
        elif mem_percent > baseline:
            severity = "info"
            icon = "🐏"
            headline = "Active RAM" if locale == "en" else "RAM active"
            detail = (
                f"Usage higher than the usual baseline ({baseline:.0f}%)"
                if locale == "en"
                else f"Utilisation supérieure à la ligne de base habituelle ({baseline:.0f}%)"
            )
        else:
            severity = "ok"
            icon = "✅"
            headline = "Stable memory" if locale == "en" else "Mémoire stable"
            if swap_mb < 50:
                detail = "No swap pressure" if locale == "en" else "Aucune pression d'échange (swap)"
            else:
                detail = f"Swap used: {swap_mb:.0f} MB" if locale == "en" else f"Swap utilisé : {swap_mb:.0f} Mo"

        return {
            "type": "ram",
            "severity": severity,
            "icon": icon,
            "headline": headline,
            "detail": detail,
            "raw": {
                "used_percent": round(mem_percent, 1),
                "used_gb": round(used_gb, 1),
                "total_gb": round(total_gb, 1),
                "swap_used_mb": round(swap_mb, 1),
            },
        }

    # -----------------------------------------------------------------------
    # Phase 3: Anomaly AI Analysis (On-Demand)
    # -----------------------------------------------------------------------

    async def analyze_anomaly(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        nm: NodeManager,
        locale: str = "fr",
    ) -> DiagnosticReport:
        """Call LLM Client on demand to analyze processes and diagnose anomaly."""
        logger.info("Running AI diagnostic for anomaly on node %s...", node_id)
        if not self._sllm:
            return DiagnosticReport(
                headline="Diagnostic IA temporairement indisponible",
                explanation="Le service d'IA n'est pas configuré sur ce serveur Master.",
                suggested_action="Veuillez configurer la clé LLM dans l'environnement du Master.",
            )

        node = await nm.get_node(db, node_id)
        if not node:
            raise ValueError(f"Node not found: {node_id}")

        # Fetch active containers and services lists
        cached_services = node.get("cached_services_json") or "[]"
        cached_containers = node.get("cached_containers_json") or "[]"

        # Get latest metrics
        latest_snap = None
        async with db.execute(
            "SELECT * FROM metrics_snapshots WHERE node_id = ? ORDER BY collected_at DESC LIMIT 1",
            (node_id,),
        ) as cursor:
            row = await cursor.fetchone()
            if row:
                latest_snap = dict(row)

        snap_str = json.dumps(latest_snap) if latest_snap else "Metrics unavailable"

        # Fetch recent audit log entries for this node (last 6 hours)
        recent_audit = []
        try:
            async with db.execute(
                """SELECT action, details_json, created_at
                   FROM audit_log WHERE node_id = ? AND created_at > ?
                   ORDER BY created_at DESC LIMIT 10""",
                (node_id, time.time() - 21600),
            ) as cursor:
                rows = await cursor.fetchall()
                recent_audit = [dict(r) for r in rows]
        except Exception:
            pass
        audit_str = json.dumps(recent_audit, indent=2) if recent_audit else "No recent audit events"

        # Fetch recent automation log entries for this node (last 6 hours)
        recent_automations = []
        try:
            async with db.execute(
                """SELECT rule_id, status, trigger_data_json, triggered_at
                   FROM automation_logs WHERE node_id = ? AND triggered_at > ?
                   ORDER BY triggered_at DESC LIMIT 10""",
                (node_id, time.time() - 21600),
            ) as cursor:
                rows = await cursor.fetchall()
                recent_automations = [dict(r) for r in rows]
        except Exception:
            pass
        auto_str = (
            json.dumps(recent_automations, indent=2)
            if recent_automations else "No recent automation events"
        )

        lang_instruction = (
            "You must write the explanation, headline, and suggested_action in English."
            if locale == "en"
            else "Tu dois obligatoirement rédiger l'explication (explanation), le titre (headline) et l'action suggérée (suggested_action) en français."
        )
        messages = [
            {
                "role": "user",
                "content": (
                    f"Analyze this server anomaly for node '{node.get('name')}':\n"
                    f"- Active Services: {cached_services}\n"
                    f"- Active Containers: {cached_containers}\n"
                    f"- Current Metrics: {snap_str}\n"
                    f"- Recent Audit Events (last 6h): {audit_str}\n"
                    f"- Recent Automation Events (last 6h): {auto_str}\n\n"
                    f"Diagnose what is causing the anomaly and suggest remediation actions. "
                    f"When evaluating the situation, consider recent audit/automation events "
                    f"that may have triggered state changes. "
                    f"{lang_instruction}"
                ),
            }
        ]

        try:
            report = await self._sllm.create(
                response_model=DiagnosticReport,
                messages=messages,
                max_retries=2,
            )
            logger.info("✓ AI Diagnostic complete for node %s", node_id)
            return report
        except Exception as ex:
            logger.error("Failed to call LLM for diagnostic on node %s: %s", node_id, ex)
            return DiagnosticReport(
                headline="Diagnostic IA temporairement indisponible",
                explanation=f"Une erreur est survenue lors de l'appel au service de diagnostic : {ex}",
                suggested_action="Veuillez inspecter manuellement les services systemd et conteneurs Docker via l'interface du serveur.",
            )
