from __future__ import annotations

"""
Vigile — Insights Manager

Implements the 3-phase insights and profiling system:
  - Phase 1: structured LLM profiling and fallback heuristic rules
  - Phase 2: real-time rule-based insights (disk regression, CPU/RAM thresholds)
  - Phase 3: real-time diagnostic LLM analysis for anomalies
"""

import asyncio
import dataclasses
import enum
import json
import logging
import re
import time
from typing import Any

import aiosqlite
from pydantic import BaseModel, Field

from master.core.llm_client import LLMClient
from master.core.node_manager import NodeManager
from master.core.structured_llm import StructuredLLM
from master.core.plugin_manager import PluginManager

logger = logging.getLogger(__name__)

# Global minimum — used as the default for observation readiness.
MIN_OBSERVATION_HOURS: float = 2.0

# Target hours for a fully mature profile (used for progress bar in frontend).
TARGET_OBSERVATION_HOURS: float = 24.0

# Per-type observation thresholds (hours).
# CPU/RAM insights need only 2h of data; disk trends and LLM profile
# require a full 24h cycle to be statistically reliable.
OBSERVATION_THRESHOLDS: dict[str, float] = {
    "cpu": 2.0,
    "ram": 2.0,
    "disk": 24.0,
    "profile": 24.0,
}


@dataclasses.dataclass(frozen=True)
class DataWindow:
    """Computed observation window for a node's metrics history."""

    hours: float
    snapshot_count: int
    ready: bool
    first_seen_at: float | None
    last_seen_at: float | None


def _format_profile_ts(ts: float | None) -> str | None:
    """Format an epoch timestamp as ISO 8601 UTC string, or None."""
    if not ts:
        return None
    return time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(ts))


class HeavyProcessConfig(BaseModel):
    container_name: str | None = Field(default=None)
    service_name: str | None = Field(default=None)
    cpu_threshold_percent: float = Field(
        description="CPU percentage threshold above which this is considered active"
    )
    label: str = Field(description="Human-friendly label")


class ServiceCategory(str, enum.Enum):
    MEDIA = "media"
    DATABASE = "database"
    LLM = "llm"
    REVERSE_PROXY = "reverse_proxy"
    CI_CD = "ci_cd"
    SYSTEM = "system"
    MONITORING = "monitoring"
    OTHER = "other"


class PluginPattern(BaseModel):
    container_pattern: str | None = Field(default=None, description="Regex pattern for container name/image")
    service_pattern: str | None = Field(default=None, description="Regex pattern for systemd service name")
    category: ServiceCategory
    label: str
    cpu_threshold_percent: float


class ClassifiedService(BaseModel):
    name: str
    service_type: str
    category: ServiceCategory
    label: str
    cpu_threshold_percent: float


class NodeServiceClassification(BaseModel):
    services: list[ClassifiedService]
    context_label: str
    baseline_ram_percent: float


class NodeProfile(BaseModel):
    node_id: str
    known_heavy_processes: list[HeavyProcessConfig] = Field(default_factory=list)
    baseline_ram_percent: float = Field(
        default=70.0, description="Expected baseline RAM utilization percentage"
    )
    context_label: str = Field(
        default="Serveur homelab", description="Overall context label of the node"
    )
    generated_via: str = Field(
        default="heuristic",
        description="How the profile was generated: 'llm' or 'heuristic'",
    )


class DiagnosticReport(BaseModel):
    """Structured diagnostic report generated by LLM on demand during anomaly."""

    headline: str = Field(
        max_length=200, description="Short human-friendly summary of the diagnostic"
    )
    explanation: str = Field(
        max_length=4000, description="Detailed explanation of what is causing the load"
    )
    suggested_action: str = Field(
        max_length=1000, description="Remediation action recommended for the user"
    )
    correlated_cause: list[str] = Field(
        default_factory=list,
        max_length=20,
        description="List of correlated events (audit actions, service changes) that may have contributed to this anomaly",
    )


class InsightsManager:
    """
    Manages node profiling, real-time insights generation, and anomaly diagnostics.
    Follows Dependency Injection: receives LLMClient, PluginManager, and optional WorkerQueryPort.
    """

    def __init__(
        self,
        llm_client: LLMClient | None = None,
        plugin_manager: PluginManager | None = None,
        worker_query_port: Any | None = None,
    ) -> None:
        self._llm_client = llm_client
        self._sllm = StructuredLLM(llm_client) if llm_client else None
        self._plugin_manager = plugin_manager
        self._worker_query_port = worker_query_port
        self._background_tasks: set[asyncio.Task] = set()
        # Nodes with an in-flight profile generation (initial or re-profile),
        # guarding against duplicate concurrent generations per node.
        self._profiling_nodes: set[str] = set()
        # In-memory cache for get_insights() responses (5 min TTL).
        # Keyed by node_id → (epoch_timestamp, response_dict).
        self._insights_cache: dict[str, tuple[float, dict[str, Any]]] = {}
        self._INSIGHTS_CACHE_TTL: float = 300.0  # 5 minutes

    def invalidate_cache(self, node_id: str) -> None:
        """Invalidate the insights cache for a node.

        Called when event-driven re-profiling triggers fire (CPU drift,
        LOST→CONNECTED reconnection, new container detection) to ensure
        the next GET /insights returns fresh data.
        """
        self._insights_cache.pop(node_id, None)

    def _spawn_task(self, coro: Any, name: str) -> asyncio.Task:
        """Spawn a supervised background task tracked for graceful shutdown."""
        task = asyncio.create_task(coro, name=name)
        self._background_tasks.add(task)
        task.add_done_callback(self._background_tasks.discard)
        return task

    async def ensure_tasks_complete(self, timeout: float = 30.0) -> None:
        """Wait for all background tasks to complete (graceful shutdown)."""
        if not self._background_tasks:
            return
        done, pending = await asyncio.wait(
            self._background_tasks, timeout=timeout
        )
        for task in pending:
            task.cancel()
        if pending:
            await asyncio.wait(pending, timeout=5.0)
        self._background_tasks.clear()

    async def generate_profile(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        nm: NodeManager,
        force: bool = False,
        locale: str = "fr",
    ) -> NodeProfile:
        logger.info("Generating profile for node %s (force=%s)...", node_id, force)

        node = await nm.get_node(db, node_id)
        if not node:
            raise ValueError(f"Node not found: {node_id}")

        hostname = node.get("hostname") or ""

        services: list[dict[str, Any]] = []
        containers: list[dict[str, Any]] = []

        cached_services = node.get("cached_services_json")
        if cached_services:
            try:
                services = json.loads(cached_services)
            except json.JSONDecodeError:
                pass

        cached_containers = node.get("cached_containers_json")
        if cached_containers:
            try:
                containers = json.loads(cached_containers)
            except json.JSONDecodeError:
                pass

        if node.get("online"):
            if not services:
                try:
                    from master.core.plugin_utils import parse_worker_list
                    from master.plugins.systemd import ServiceInfo

                    result = await self._auto_profiling_intent(
                        node_id, "LIST_SERVICES", {}, nm, db, timeout=8.0
                    )
                    if result.get("success"):
                        parsed = parse_worker_list(result.get("output", ""), ServiceInfo)
                        if parsed is not None:
                            services = parsed
                except Exception as e:
                    logger.warning("Profile gen: failed live services query: %s", e)

            if not containers:
                try:
                    from master.core.plugin_utils import parse_worker_list
                    from master.plugins.docker import ContainerSummary

                    result = await self._auto_profiling_intent(
                        node_id, "LIST_CONTAINERS", {}, nm, db, timeout=8.0
                    )
                    if result.get("success"):
                        parsed = parse_worker_list(result.get("output", ""), ContainerSummary)
                        if parsed is not None:
                            containers = parsed
                except Exception as e:
                    logger.warning("Profile gen: failed live containers query: %s", e)

        classification = await self.classify_node_services(
            node_id, db, nm, locale=locale, services=services, containers=containers
        )

        context_label = classification.context_label
        baseline_ram_percent = classification.baseline_ram_percent

        known_heavy = [
            HeavyProcessConfig(
                container_name=s.name if s.service_type == "container" else None,
                service_name=s.name if s.service_type == "systemd" else None,
                cpu_threshold_percent=s.cpu_threshold_percent,
                label=s.label,
            )
            for s in classification.services
        ]

        profile = NodeProfile(
            node_id=node_id,
            known_heavy_processes=known_heavy,
            baseline_ram_percent=baseline_ram_percent,
            context_label=context_label,
            generated_via="llm" if (self._sllm and self._llm_client and self._llm_client.base_url) else "heuristic",
        )

        logger.info("Profile ready for node %s", node_id)

        now = time.time()
        await db.execute(
            """
            UPDATE nodes SET
                insight_profile = ?,
                insight_profile_generated_at = ?,
                cached_services_json = ?,
                cached_containers_json = ?
            WHERE id = ?
            """,
            (
                profile.model_dump_json(),
                now,
                json.dumps(services) if services else node.get("cached_services_json"),
                json.dumps(containers) if containers else node.get("cached_containers_json"),
                node_id,
            ),
        )
        await db.commit()

        return profile

    async def _auto_profiling_intent(
        self,
        node_id: str,
        action: str,
        params: dict[str, Any],
        nm: NodeManager,
        db: aiosqlite.Connection,
        timeout: float = 8.0,
    ) -> dict[str, Any]:
        """
        Create, auto-approve, execute, and complete a profiling intent.

        Read-only profiling intents (LIST_SERVICES, LIST_CONTAINERS) are
        auto-approved by 'system' — no human operator needed — but are still
        tracked through ActionProposal for audit trail consistency.
        """
        from master.core.action_proposal import ActionProposal
        from master.core.audit import AuditAction, log_action

        proposal = ActionProposal(
            node_id=node_id,
            action=action,
            params=params,
            reasoning="Profiling intent (auto-approved, read-only).",
            risk_level="LOW",
            created_by="insights",
            status="APPROVED",
            approved_by="system",
        )

        data = proposal.to_db_dict()
        await db.execute(
            """INSERT INTO action_proposals
               (id, node_id, action, params_json, reasoning, risk_level,
                status, created_by, approved_by, created_at, updated_at)
               VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)""",
            (
                data["id"], data["node_id"], data["action"], data["params_json"],
                data["reasoning"], data["risk_level"],
                data["status"], data["created_by"], data["approved_by"],
                data["created_at"], data["updated_at"],
            ),
        )
        await db.commit()

        from master.core.worker_query_port import WorkerQueryPort

        port = self._worker_query_port or WorkerQueryPort(nm)
        try:
            result = await port.query(node_id, action, params, timeout=timeout)
        except (RuntimeError, TimeoutError) as exc:
            proposal.complete(success=False, result_data={"error": str(exc)})
            result = {"success": False, "error": str(exc)}

        db_data = proposal.to_db_dict()
        await db.execute(
            """UPDATE action_proposals SET
                status = ?, updated_at = ?, executed_at = ?, result_json = ?
               WHERE id = ?""",
            (
                db_data["status"], db_data["updated_at"],
                db_data["executed_at"], db_data["result_json"],
                proposal.id,
            ),
        )
        await db.commit()

        await log_action(
            db,
            user_id="system",
            action=AuditAction.AUTOMATION_TRIGGERED,
            node_id=node_id,
            details={
                "proposal_id": proposal.id,
                "action": action,
                "status": proposal.status,
            },
        )

        return result

    def _get_plugin_patterns(self) -> list[PluginPattern]:
        if not self._plugin_manager:
            return []
        try:
            results = self._plugin_manager.call("get_heavy_process_patterns")
            patterns = []
            for result in results:
                if isinstance(result, list):
                    for item in result:
                        if isinstance(item, dict):
                            patterns.append(PluginPattern(**item))
                        elif isinstance(item, PluginPattern):
                            patterns.append(item)
                elif isinstance(result, PluginPattern):
                    patterns.append(result)
            return patterns
        except Exception as e:
            logger.debug("Failed to collect plugin patterns: %s", e)
            return []

    def _classify_services_fallback(
        self,
        services: list[dict[str, Any]],
        containers: list[dict[str, Any]],
    ) -> list[HeavyProcessConfig]:
        known_heavy: list[HeavyProcessConfig] = []
        plugin_patterns = self._get_plugin_patterns()

        for c in containers:
            c_name = c.get("name", "")
            c_image = c.get("image", "")
            for pattern in plugin_patterns:
                if pattern.container_pattern:
                    if re.search(pattern.container_pattern, c_name.lower()) or re.search(pattern.container_pattern, c_image.lower()):
                        known_heavy.append(
                            HeavyProcessConfig(
                                container_name=c_name,
                                cpu_threshold_percent=pattern.cpu_threshold_percent,
                                label=pattern.label,
                            )
                        )
                        break

        for s in services:
            s_name = s.get("name", "")
            for pattern in plugin_patterns:
                if pattern.service_pattern:
                    if re.search(pattern.service_pattern, s_name.lower()):
                        known_heavy.append(
                            HeavyProcessConfig(
                                service_name=s_name,
                                cpu_threshold_percent=pattern.cpu_threshold_percent,
                                label=pattern.label,
                            )
                        )
                        break

        return known_heavy

    async def classify_node_services(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        nm: NodeManager,
        locale: str = "fr",
        services: list[dict[str, Any]] | None = None,
        containers: list[dict[str, Any]] | None = None,
    ) -> NodeServiceClassification:
        logger.info("Classifying services for node %s...", node_id)
        node = await nm.get_node(db, node_id)
        if not node:
            raise ValueError(f"Node not found: {node_id}")

        hostname = node.get("hostname") or ""

        if services is None:
            services = []
            cached = node.get("cached_services_json")
            if cached:
                try:
                    services = json.loads(cached)
                except Exception:
                    pass

        if containers is None:
            containers = []
            cached = node.get("cached_containers_json")
            if cached:
                try:
                    containers = json.loads(cached)
                except Exception:
                    pass

        if self._sllm and self._llm_client and self._llm_client.base_url:
            lang = (
                "Write the label and context_label in English."
                if locale == "en"
                else "Écris le label et le context_label en français."
            )
            try:
                messages = [
                    {
                        "role": "user",
                        "content": (
                            f"Classify every container and service running on server '{node.get('name')}'.\n\n"
                            f"Systemd services:\n{json.dumps(services[:30], indent=2)}\n\n"
                            f"Docker containers (with image):\n{json.dumps(containers[:30], indent=2)}\n\n"
                            f"For each entry, determine:\n"
                            f"- category: one of {[e.value for e in ServiceCategory]}\n"
                            f"- label: short human-friendly description in French\n"
                            f"- cpu_threshold_percent: CPU % above which this process is considered actively loaded "
                            f"(e.g. 50 for Plex transcoding, 30 for a reverse proxy, 40 for a database)\n"
                            f"- service_type: \"container\" or \"systemd\"\n\n"
                            f"Also suggest:\n"
                            f"- context_label: overall role of this server (e.g. \"Serveur Médias\", \"Base de Données\", \"Passerelle LLM\")\n"
                            f"- baseline_ram_percent: normal baseline RAM usage for this server\n\n"
                            f"{lang}"
                        ),
                    }
                ]
                result = await self._sllm.create(
                    response_model=NodeServiceClassification,
                    messages=messages,
                )
                logger.info("LLM classification successful for node %s", node_id)
                return result
            except Exception as ex:
                logger.warning("LLM classification failed for node %s: %s", node_id, ex)

        known_heavy = self._classify_services_fallback(services, containers)
        # Read context_label from the stored insight_profile JSON,
        # falling back to a sensible default if not yet configured.
        stored_profile = node.get("insight_profile")
        if stored_profile:
            try:
                context = json.loads(stored_profile).get(
                    "context_label", "Serveur homelab"
                )
            except (json.JSONDecodeError, TypeError):
                context = "Serveur homelab"
        else:
            context = "Serveur homelab"
        classified = [
            ClassifiedService(
                name=h.container_name or h.service_name or "",
                service_type="container" if h.container_name else "systemd",
                category=ServiceCategory.OTHER,
                label=h.label,
                cpu_threshold_percent=h.cpu_threshold_percent,
            )
            for h in known_heavy
        ]
        return NodeServiceClassification(
            services=classified,
            context_label=context,
            baseline_ram_percent=65.0,
        )

    def generate_fallback_profile(
        self,
        node_id: str,
        services: list[dict[str, Any]],
        containers: list[dict[str, Any]],
    ) -> NodeProfile:
        known_heavy = self._classify_services_fallback(services, containers)
        return NodeProfile(
            node_id=node_id,
            known_heavy_processes=known_heavy,
            baseline_ram_percent=65.0,
            context_label="Serveur homelab",
        )

    async def _compute_data_window(
        self,
        node_id: str,
        db: aiosqlite.Connection,
    ) -> DataWindow:
        """Compute the observation window for a node from metrics_snapshots."""
        try:
            async with db.execute(
                "SELECT MIN(collected_at), MAX(collected_at), COUNT(*) "
                "FROM metrics_snapshots WHERE node_id = ?",
                (node_id,),
            ) as cursor:
                row = await cursor.fetchone()
            if row and row[0] is not None and row[1] is not None:
                hours = (row[1] - row[0]) / 3600.0
                return DataWindow(
                    hours=hours,
                    snapshot_count=row[2],
                    ready=hours >= OBSERVATION_THRESHOLDS.get("cpu", MIN_OBSERVATION_HOURS),
                    first_seen_at=row[0],
                    last_seen_at=row[1],
                )
        except Exception as ex:
            logger.debug("Could not query metrics_snapshots for node %s: %s", node_id, ex)

        return DataWindow(
            hours=0.0, snapshot_count=0, ready=False,
            first_seen_at=None, last_seen_at=None,
        )

    @staticmethod
    def _compute_profile_confidence(
        profile: NodeProfile | None,
        window: DataWindow,
    ) -> str:
        """Derive a confidence level from the profile source and window maturity."""
        if profile is None:
            return "none"
        if window.snapshot_count == 0:
            return "high"
        if window.hours < MIN_OBSERVATION_HOURS:
            return "low"
        if window.hours < TARGET_OBSERVATION_HOURS:
            return "medium"
        return "high"

    async def get_insights(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        nm: NodeManager,
        locale: str = "fr",
    ) -> dict[str, Any]:
        """
        Produce real-time insights for a node (Phase 2).
        Calculates disk slope on-the-fly and evaluates current CPU/RAM.

        Results are cached in-memory for 5 minutes to avoid redundant
        SQL queries when the operator refreshes the dashboard rapidly.
        """
        node = await nm.get_node(db, node_id)
        if not node:
            return {
                "node_id": node_id,
                "insights": [],
                "data_window_hours": 0.0,
                "observation_ready": False,
                "profile_confidence": "none",
                "next_profile_refresh_at": None,
                "profile_generated_at": None,
            }

        # Compute observation window early — used for metadata and confidence.
        window = await self._compute_data_window(node_id, db)

        # 1. Trigger profile generation automatically if missing and online
        profile_json = node.get("insight_profile")
        if not profile_json:
            if node.get("online"):
                # Spawn generation background task (guarded against duplicates)
                if node_id not in self._profiling_nodes:
                    self._profiling_nodes.add(node_id)
                    task = self._spawn_task(
                        self.generate_profile(node_id, db, nm, locale=locale),
                        name=f"profile:{node_id}",
                    )
                    task.add_done_callback(
                        lambda _t: self._profiling_nodes.discard(node_id)
                    )
                return {
                    "node_id": node_id,
                    "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "insights": [
                        {
                            "type": "status",
                            "severity": "info",
                            "icon": "🔄",
                            "headline": "Analyse du profil en cours",
                            "detail": "Vigilbot identifie les services et configure les seuils de charge...",
                        }
                    ],
                    "data_window_hours": round(window.hours, 1),
                    "observation_ready": window.ready,
                    "profile_confidence": "low",
                    "next_profile_refresh_at": None,
                    "profile_generated_at": None,
                }
            else:
                return {
                    "node_id": node_id,
                    "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "insights": [
                        {
                            "type": "status",
                            "severity": "warning",
                            "icon": "⚠️",
                            "headline": "Profil manquant",
                            "detail": "Le serveur doit être connecté en ligne pour initialiser son profil d'insights.",
                        }
                    ],
                    "data_window_hours": round(window.hours, 1),
                    "observation_ready": window.ready,
                    "profile_confidence": "none",
                    "next_profile_refresh_at": None,
                    "profile_generated_at": None,
                }

        profile = NodeProfile.model_validate_json(profile_json)

        # 1b. Re-profile when stale (> 12h) and node online — stale-while-revalidate:
        # keep serving the existing profile while the background task refreshes it.
        profile_generated_at_ts = node.get("insight_profile_generated_at") or 0
        profile_age = time.time() - profile_generated_at_ts
        if (
            profile_age > 12 * 3600  # 12h soft refresh
            and node.get("online")
            and node_id not in self._profiling_nodes
        ):
            self._profiling_nodes.add(node_id)
            task = self._spawn_task(
                self.generate_profile(node_id, db, nm, locale=locale),
                name=f"reprofile:{node_id}",
            )
            task.add_done_callback(
                lambda _t: self._profiling_nodes.discard(node_id)
            )

        # 2. Get latest metrics snapshot
        latest_snap = None
        async with db.execute(
            "SELECT * FROM metrics_snapshots WHERE node_id = ? ORDER BY collected_at DESC LIMIT 1",
            (node_id,),
        ) as cursor:
            row = await cursor.fetchone()
            if row:
                latest_snap = dict(row)

        latest_snap_ts = latest_snap.get("collected_at") if latest_snap else 0
        cache_key = (node_id, latest_snap_ts, profile_generated_at_ts, locale)

        # --- In-memory cache check ---
        now_cache = time.time()
        cached_entry = self._insights_cache.get(node_id)
        if (
            cached_entry
            and cached_entry[0] == cache_key
            and (now_cache - cached_entry[1]) < self._INSIGHTS_CACHE_TTL
        ):
            return cached_entry[2]

        if not latest_snap:
            return {
                "node_id": node_id,
                "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "insights": [
                    {
                        "type": "status",
                        "severity": "warning",
                        "icon": "🔄",
                        "headline": "En attente de métriques",
                        "detail": "Aucun rapport de métriques n'a encore été stocké pour ce serveur.",
                    }
                ],
                "data_window_hours": 0.0,
                "observation_ready": False,
                "profile_confidence": "low",
                "next_profile_refresh_at": None,
                "profile_generated_at": _format_profile_ts(profile_generated_at_ts),
            }

        insights = []

        # --- A. DISK INSIGHT (On-the-fly Linear Regression) ---
        disk_insight = await self._calculate_disk_insight(node_id, db, latest_snap)
        if disk_insight:
            insights.append(disk_insight)

        # --- B. CPU INSIGHT ---
        cpu_insight = self._calculate_cpu_insight(latest_snap, profile, node, locale=locale)
        if cpu_insight:
            insights.append(cpu_insight)

        # --- C. RAM INSIGHT ---
        ram_insight = self._calculate_ram_insight(latest_snap, profile, locale=locale)
        if ram_insight:
            insights.append(ram_insight)

        confidence = self._compute_profile_confidence(profile, window)
        next_refresh_ts = profile_generated_at_ts + 24 * 3600 if profile_generated_at_ts else None

        # Per-type readiness: tells the frontend exactly which insight types
        # have enough data vs which are still in observation phase.
        per_type_readiness = {
            itype: {
                "ready": window.hours >= threshold,
                "hours": round(window.hours, 1),
                "required": threshold,
            }
            for itype, threshold in OBSERVATION_THRESHOLDS.items()
        }

        result = {
            "node_id": node_id,
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "insights": insights,
            "data_window_hours": round(window.hours, 1),
            "observation_ready": window.ready,
            "profile_confidence": confidence,
            "next_profile_refresh_at": (
                time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime(next_refresh_ts))
                if next_refresh_ts
                else None
            ),
            "profile_generated_at": _format_profile_ts(profile_generated_at_ts),
            "per_type_readiness": per_type_readiness,
        }

        # Store in cache
        self._insights_cache[node_id] = (cache_key, time.time(), result)
        return result
    async def _calculate_disk_insight(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        latest_snap: dict[str, Any],
    ) -> dict[str, Any] | None:
        """Calculate linear regression slope of disk usage and return insight according to decision rules."""
        disk_total = latest_snap.get("disk_total_bytes", 0)
        disk_used = latest_snap.get("disk_used_bytes", 0)
        disk_percent = latest_snap.get("disk_percent", 0.0)

        if disk_total == 0:
            return None

        # Query metrics snapshots from the last 24 hours (86400 seconds)
        now = time.time()
        limit_time = now - 86400

        snapshots = []
        async with db.execute(
            """
            SELECT collected_at, disk_used_bytes
            FROM metrics_snapshots
            WHERE node_id = ? AND collected_at >= ?
            ORDER BY collected_at ASC
            """,
            (node_id, limit_time),
        ) as cursor:
            async for r in cursor:
                if isinstance(r, (tuple, list)):
                    snapshots.append({"collected_at": r[0], "disk_used_bytes": r[1]})
                else:
                    snapshots.append(dict(r))

        free_bytes = disk_total - disk_used
        free_gb = free_bytes / (1024**3)
        used_percent = round(disk_percent, 1)

        timespan = (
            (snapshots[-1]["collected_at"] - snapshots[0]["collected_at"])
            if len(snapshots) >= 2
            else 0
        )
        hours_collected = int(timespan / 3600)

        # Default values
        safety_margin_days = 2
        confidence = "none"

        # Case 1: < 6 hours of history -> Collecte en cours
        if timespan < 21600 or len(snapshots) < 4:
            return {
                "type": "disk",
                "severity": "ok",
                "icon": "🔄",
                "headline": "Collecte en cours",
                "detail": f"Données collectées depuis {max(1, hours_collected)}h — historisation en cours",
                "confidence": "none",
                "raw": {
                    "used_percent": used_percent,
                    "free_gb": round(free_gb, 1),
                    "growth_gb_per_day": 0.0,
                    "hours_collected": hours_collected,
                },
            }

        # --- IQR outlier detection on consecutive deltas ---
        # A one-off spike (e.g. a nightly 50 GB backup written then deleted)
        # skews the naive least-squares slope. But a MASS DELETION must not
        # zero the estimate either. Outlier deltas are therefore treated as
        # PERMANENT LEVEL SHIFTS, not noise: the series is rebuilt backwards
        # from the latest value ignoring those jumps, so the regression slope
        # reflects the underlying growth rate regardless of how much space was
        # freed (or bulk-added) in between.
        raw_gb = [s["disk_used_bytes"] / (1024**3) for s in snapshots]
        deltas = [raw_gb[i] - raw_gb[i - 1] for i in range(1, len(raw_gb))]
        if deltas:
            sorted_deltas = sorted(deltas)
            n_deltas = len(sorted_deltas)
            q1 = sorted_deltas[(n_deltas + 3) // 4 - 1]
            q3 = sorted_deltas[(3 * n_deltas + 3) // 4 - 1]
            iqr = q3 - q1
            lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr
            inliers = [d for d in deltas if lower <= d <= upper]

            # Too many level shifts to reconstruct a reliable trend.
            if len(inliers) < 3:
                return {
                    "type": "disk",
                    "severity": "ok",
                    "icon": "📊",
                    "headline": "Tendance disque fluctuante",
                    "detail": "Historique insuffisant après filtrage des points aberrants",
                    "confidence": "low",
                    "raw": {
                        "used_percent": used_percent,
                        "free_gb": round(free_gb, 1),
                        "growth_gb_per_day": 0.0,
                        "r_squared": 0.0,
                    },
                }

            # Rebuild the series without level shifts: start from the latest
            # measured value and walk backwards, keeping only inlier deltas.
            # Outlier deltas (mass deletion / bulk import / transient spike)
            # are skipped, stitching both sides at the current level.
            normalized_gb = [0.0] * len(raw_gb)
            normalized_gb[-1] = raw_gb[-1]
            for i in range(len(raw_gb) - 2, -1, -1):
                delta = raw_gb[i + 1] - raw_gb[i]
                if lower <= delta <= upper:
                    normalized_gb[i] = normalized_gb[i + 1] - delta
                else:
                    normalized_gb[i] = normalized_gb[i + 1]
            snapshots = [
                {**s, "disk_used_bytes": round(normalized_gb[i] * (1024**3))}
                for i, s in enumerate(snapshots)
            ]

        # Calculate slope (GB per day) and R² (coefficient of determination)
        t0 = snapshots[0]["collected_at"]
        x = [(s["collected_at"] - t0) / 86400.0 for s in snapshots]
        y = [s["disk_used_bytes"] / (1024**3) for s in snapshots]

        n = len(snapshots)
        sum_x = sum(x)
        sum_y = sum(y)
        sum_xx = sum(xi * xi for xi in x)
        sum_xy = sum(xi * yi for xi, yi in zip(x, y))

        denominator = n * sum_xx - sum_x * sum_x
        raw_slope = 0.0
        if abs(denominator) > 1e-6:
            raw_slope = (n * sum_xy - sum_x * sum_y) / denominator

        # Calculate R² (Pearson correlation coefficient squared)
        y_mean = sum_y / n
        ss_tot = sum((yi - y_mean) ** 2 for yi in y)
        ss_res = sum(
            (yi - (raw_slope * xi + (sum_y - raw_slope * sum_x) / n)) ** 2
            for xi, yi in zip(x, y)
        )
        r_squared = 1.0 - (ss_res / ss_tot) if ss_tot > 1e-9 else 0.0

        # Handle negative slope (disk is being freed)
        if raw_slope < -0.05:
            return {
                "type": "disk",
                "severity": "ok",
                "icon": "🗑️",
                "headline": "Disque en cours de libération",
                "detail": f"Tendance à la baisse de {abs(raw_slope):.2f} Go/jour",
                "confidence": "high" if timespan >= 86400 else "medium",
                "raw": {
                    "used_percent": used_percent,
                    "free_gb": round(free_gb, 1),
                    "growth_gb_per_day": round(raw_slope, 3),
                    "r_squared": round(r_squared, 2),
                },
            }

        slope = max(0.0, raw_slope)

        # Handle noisy / non-linear data (R² < 0.5)
        if r_squared < 0.5 and timespan >= 21600 and slope > 0.05:
            return {
                "type": "disk",
                "severity": "ok",
                "icon": "📊",
                "headline": "Tendance disque fluctuante",
                "detail": f"Variation non-linéaire détectée sur l'historique (R²={r_squared:.2f})",
                "confidence": "low",
                "raw": {
                    "used_percent": used_percent,
                    "free_gb": round(free_gb, 1),
                    "growth_gb_per_day": round(slope, 3),
                    "r_squared": round(r_squared, 2),
                },
            }

        # Check stability / trend
        if slope <= 0.01:
            return {
                "type": "disk",
                "severity": "ok",
                "icon": "✅",
                "headline": "Disque stable",
                "detail": "Plus de 6 mois d'autonomie restants",
                "confidence": "high" if timespan >= 86400 else "medium",
                "raw": {
                    "used_percent": used_percent,
                    "free_gb": round(free_gb, 1),
                    "growth_gb_per_day": round(slope, 3),
                    "r_squared": round(r_squared, 2),
                },
            }

        days_left = free_gb / slope

        # Case 2: Early estimation (6h to < 24h)
        if timespan < 86400:
            confidence = "medium"
            # Priority Exception Rule: If early estimation predicts saturation within 24h (< 1 day)
            if days_left < 1.0:
                growth_gb_h = slope / 24.0
                return {
                    "type": "disk",
                    "severity": "critical",
                    "icon": "🚨",
                    "headline": "Risque de saturation aujourd’hui — estimation à confirmer",
                    "detail": f"Données collectées depuis {hours_collected} h, croissance actuelle : +{growth_gb_h:.2f} Go/h",
                    "confidence": "medium",
                    "raw": {
                        "used_percent": used_percent,
                        "free_gb": round(free_gb, 1),
                        "growth_gb_per_day": round(slope, 3),
                        "days_left": round(days_left, 1),
                        "hours_collected": hours_collected,
                    },
                }

            # Normal early estimation
            days_int = max(1, round(days_left))
            action_before = max(1, days_int - safety_margin_days)
            severity = "critical" if days_left < 14 else ("warning" if days_left < 60 else "ok")
            icon = "🚨" if severity == "critical" else ("⚠️" if severity == "warning" else "✅")
            return {
                "type": "disk",
                "severity": severity,
                "icon": icon,
                "headline": f"Environ {days_int} jours — confiance moyenne",
                "detail": f"Taux de croissance de +{slope:.2f} Go/jour · À prévoir avant : dans {action_before} jours",
                "confidence": "medium",
                "raw": {
                    "used_percent": used_percent,
                    "free_gb": round(free_gb, 1),
                    "growth_gb_per_day": round(slope, 3),
                    "days_left": days_int,
                    "action_before_days": action_before,
                    "hours_collected": hours_collected,
                },
            }

        # Case 3: Reliable estimation (>= 24h)
        confidence = "high"
        days_int = max(1, round(days_left))
        action_before = max(1, days_int - safety_margin_days)
        severity = "critical" if days_left < 14 else ("warning" if days_left < 60 else "ok")
        icon = "🚨" if severity == "critical" else ("⚠️" if severity == "warning" else "✅")

        return {
            "type": "disk",
            "severity": severity,
            "icon": icon,
            "headline": f"Saturation estimée dans {days_int} jours",
            "detail": f"Taux de croissance de +{slope:.2f} Go/jour · À prévoir avant : dans {action_before} jours",
            "confidence": "high",
            "raw": {
                "used_percent": used_percent,
                "free_gb": round(free_gb, 1),
                "growth_gb_per_day": round(slope, 3),
                "days_left": days_int,
                "action_before_days": action_before,
                "hours_collected": hours_collected,
            },
        }

    def _calculate_cpu_insight(
        self,
        latest_snap: dict[str, Any],
        profile: NodeProfile,
        node: dict[str, Any],
        locale: str = "fr",
    ) -> dict[str, Any]:
        """Match current CPU load against node profile rules and active processes."""
        cpu_percent = latest_snap.get("cpu_percent", 0.0)

        top_procs: list[dict[str, Any]] = []
        raw_top = latest_snap.get("top_processes_json")
        if isinstance(raw_top, str):
            try:
                top_procs = json.loads(raw_top)
            except json.JSONDecodeError:
                pass
        elif isinstance(latest_snap.get("top_processes"), list):
            top_procs = latest_snap["top_processes"]

        active_containers = []
        cached_containers = node.get("cached_containers_json")
        if cached_containers:
            try:
                active_containers = [
                    c.get("name")
                    for c in json.loads(cached_containers)
                    if c.get("state") == "running" or "up" in c.get("status", "").lower()
                ]
            except json.JSONDecodeError:
                pass

        active_services = []
        cached_services = node.get("cached_services_json")
        if cached_services:
            try:
                active_services = [
                    s.get("service")
                    for s in json.loads(cached_services)
                    if s.get("state") == "active"
                ]
            except json.JSONDecodeError:
                pass

        culprit = None
        culprit_pct: float | None = None
        culprit_ram_pct: float | None = None
        headline = "Stable CPU" if locale == "en" else "CPU stable"
        detail = "Server calm and stable" if locale == "en" else "Serveur calme et stable"
        icon = "💤"

        # Phase 1: Find all running heavy processes
        running_heavy: list[HeavyProcessConfig] = []
        for p in profile.known_heavy_processes:
            is_running = False
            if p.container_name and p.container_name in active_containers:
                is_running = True
            elif p.service_name and p.service_name in active_services:
                is_running = True

            if is_running:
                running_heavy.append(p)

        # Phase 2: Match running heavy processes against actual CPU usage from top_processes
        # Priority: use ACTUAL CPU usage, not threshold value
        if running_heavy and top_procs:
            best_actual_cpu = -1.0
            for p in running_heavy:
                p_name = (p.container_name or p.service_name or "").lower()
                for tp in top_procs:
                    tp_name = tp.get("name", "").lower()
                    tp_cpu = tp.get("cpu_percent", 0.0)
                    if (p_name in tp_name or tp_name in p_name) and tp_cpu >= p.cpu_threshold_percent:
                        if tp_cpu > best_actual_cpu:
                            best_actual_cpu = tp_cpu
                            culprit = p
                            culprit_pct = tp_cpu
                            mem_total = latest_snap.get("mem_total_bytes", 0)
                            if mem_total > 0 and tp.get("mem_rss_kb"):
                                culprit_ram_pct = (tp["mem_rss_kb"] * 1024) / mem_total * 100
                            else:
                                culprit_ram_pct = None
                        break

        # Phase 3: If no heavy process matched but CPU is high, use the top process directly
        if not culprit and top_procs and cpu_percent > 40:
            top = top_procs[0]
            top_cpu = top.get("cpu_percent", 0.0)
            if top_cpu > 10:
                culprit_pct = top_cpu
                mem_total = latest_snap.get("mem_total_bytes", 0)
                if mem_total > 0 and top.get("mem_rss_kb"):
                    culprit_ram_pct = (top["mem_rss_kb"] * 1024) / mem_total * 100

        # Filter out culprit if its resource consumption is negligible (both CPU and RAM < 5.0%)
        if culprit:
            cpu_val = culprit_pct if culprit_pct is not None else cpu_percent
            ram_val = culprit_ram_pct if culprit_ram_pct is not None else 0.0
            if cpu_val < 5.0 and ram_val < 5.0:
                culprit = None

        if cpu_percent > 75:
            if culprit:
                severity = "warning"
                icon = "🔥"
                raw_name = culprit.container_name or culprit.service_name or culprit.label or "inconnu"
                culprit_display_name = raw_name[0].upper() + raw_name[1:] if raw_name else "Inconnu"
                cpu_val = culprit_pct if culprit_pct is not None else cpu_percent
                ram_val = culprit_ram_pct if culprit_ram_pct is not None else 0.0

                resource_parts = []
                if cpu_val >= 5.0:
                    resource_parts.append(f"{cpu_val:.0f}% CPU" if locale == "en" else f"{cpu_val:.0f}% du processeur")
                if ram_val >= 5.0:
                    resource_parts.append(f"{ram_val:.0f}% RAM" if locale == "en" else f"{ram_val:.0f}% de la RAM")
                
                resource_str = (" and " if locale == "en" else " et ").join(resource_parts)
                headline = f"Intense activity · {culprit_display_name}" if locale == "en" else f"Activité intense · {culprit_display_name}"
                if resource_str:
                    detail = f"Service '{raw_name}' uses {resource_str}." if locale == "en" else f"Le service '{raw_name}' utilise {resource_str}."
                else:
                    detail = f"Service '{raw_name}' is active." if locale == "en" else f"Le service '{raw_name}' est actif."
            elif top_procs and top_procs[0].get("cpu_percent", 0) > 10:
                severity = "warning"
                icon = "⚠️"
                top = top_procs[0]
                headline = "Unusually high load" if locale == "en" else "Charge élevée anormale"
                detail = f"Active process {top['name']} ({top['cpu_percent']:.0f}%)" if locale == "en" else f"Processus {top['name']} actif ({top['cpu_percent']:.0f}%)"
            else:
                severity = "warning"
                icon = "⚠️"
                headline = "Unusually high load" if locale == "en" else "Charge élevée anormale"
                detail = "No known heavy process is active." if locale == "en" else "Aucun processus lourd connu n'est actif sur le système."
        elif cpu_percent > 40:
            if culprit:
                severity = "info"
                icon = "⚡"
                raw_name = culprit.container_name or culprit.service_name or culprit.label or "inconnu"
                culprit_display_name = raw_name[0].upper() + raw_name[1:] if raw_name else "Inconnu"
                cpu_val = culprit_pct if culprit_pct is not None else cpu_percent
                ram_val = culprit_ram_pct if culprit_ram_pct is not None else 0.0

                resource_parts = []
                if cpu_val >= 5.0:
                    resource_parts.append(f"{cpu_val:.0f}% CPU" if locale == "en" else f"{cpu_val:.0f}% du processeur")
                if ram_val >= 5.0:
                    resource_parts.append(f"{ram_val:.0f}% RAM" if locale == "en" else f"{ram_val:.0f}% de la RAM")
                
                resource_str = (" and " if locale == "en" else " et ").join(resource_parts)
                headline = f"Moderate load · {culprit_display_name}" if locale == "en" else f"Charge modérée · {culprit_display_name}"
                if resource_str:
                    detail = f"Service '{raw_name}' uses {resource_str}." if locale == "en" else f"Le service '{raw_name}' utilise {resource_str}."
                else:
                    detail = f"Service '{raw_name}' is active." if locale == "en" else f"Le service '{raw_name}' est actif."
            elif top_procs and top_procs[0].get("cpu_percent", 0) > 5:
                severity = "info"
                icon = "🏃"
                top = top_procs[0]
                headline = "Moderate activity" if locale == "en" else "Activité modérée"
                detail = f"Active process {top['name']} ({top['cpu_percent']:.0f}%)" if locale == "en" else f"Processus {top['name']} actif ({top['cpu_percent']:.0f}%)"
            else:
                severity = "info"
                icon = "🏃"
                headline = "Moderate activity" if locale == "en" else "Activité modérée"
                detail = f"General server load at {cpu_percent:.0f}%" if locale == "en" else f"Charge générale du serveur à {cpu_percent:.0f}%"
        else:
            severity = "ok"
            icon = "✅"
            headline = "Stable CPU" if locale == "en" else "CPU stable"
            detail = "Server calm and stable" if locale == "en" else "Serveur calme et stable"

        return {
            "type": "cpu",
            "severity": severity,
            "icon": icon,
            "headline": headline,
            "detail": detail,
            "raw": {
                "cpu_percent": round(cpu_percent, 1),
                "culprit_container": culprit.container_name if culprit else None,
                "culprit_service": culprit.service_name if culprit else None,
                "top_processes": top_procs[:5] if top_procs else None,
            },
        }

    def _calculate_ram_insight(
        self,
        latest_snap: dict[str, Any],
        profile: NodeProfile,
        locale: str = "fr",
    ) -> dict[str, Any]:
        """Assess RAM and swap usage against profile baseline."""
        mem_percent = latest_snap.get("mem_percent", 0.0)
        mem_total = latest_snap.get("mem_total_bytes", 0)
        mem_used = latest_snap.get("mem_used_bytes", 0)
        swap_used = latest_snap.get("swap_used_bytes", 0)

        used_gb = mem_used / (1024**3)
        total_gb = mem_total / (1024**3)
        swap_mb = swap_used / (1024 * 1024)

        baseline = profile.baseline_ram_percent

        if mem_percent > 90:
            severity = "warning"
            icon = "⚠️"
            headline = "RAM nearly full" if locale == "en" else "RAM presque saturée"
            detail = "Potential slow down risk (OOM)" if locale == "en" else "Risque potentiel de ralentissement (OOM)"
        elif mem_percent > baseline:
            severity = "info"
            icon = "🐏"
            headline = "Active RAM" if locale == "en" else "RAM active"
            detail = (
                f"Usage higher than the usual baseline ({baseline:.0f}%)"
                if locale == "en"
                else f"Utilisation supérieure à la ligne de base habituelle ({baseline:.0f}%)"
            )
        else:
            severity = "ok"
            icon = "✅"
            headline = "Stable memory" if locale == "en" else "Mémoire stable"
            if swap_mb < 50:
                detail = "No swap pressure" if locale == "en" else "Aucune pression d'échange (swap)"
            else:
                detail = f"Swap used: {swap_mb:.0f} MB" if locale == "en" else f"Swap utilisé : {swap_mb:.0f} Mo"

        return {
            "type": "ram",
            "severity": severity,
            "icon": icon,
            "headline": headline,
            "detail": detail,
            "raw": {
                "used_percent": round(mem_percent, 1),
                "used_gb": round(used_gb, 1),
                "total_gb": round(total_gb, 1),
                "swap_used_mb": round(swap_mb, 1),
            },
        }

    @staticmethod
    def _trim_json_entries(
        raw: str,
        preferred_state: str,
        max_entries: int = 20,
        max_chars: int = 6000,
    ) -> str:
        """
        Trim a cached services/containers JSON list before LLM prompt injection.

        Keeps at most ``max_entries`` entries, preferring entries whose state
        matches ``preferred_state`` ('active' for services, 'running' for
        containers, with 'up' in the status string as an extra signal). Falls
        back to the raw string truncated to ``max_chars`` when parsing fails.
        """
        try:
            items = json.loads(raw)
        except (json.JSONDecodeError, TypeError):
            return raw[:max_chars]
        if not isinstance(items, list):
            return raw[:max_chars]

        def _is_preferred(item: Any) -> bool:
            if not isinstance(item, dict):
                return False
            if str(item.get("state", "")).lower() == preferred_state:
                return True
            return preferred_state == "running" and "up" in str(
                item.get("status", "")
            ).lower()

        preferred = [i for i in items if _is_preferred(i)]
        rest = [i for i in items if not _is_preferred(i)]
        return json.dumps((preferred + rest)[:max_entries], separators=(",", ":"))

    async def analyze_anomaly(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        nm: NodeManager,
        locale: str = "fr",
    ) -> DiagnosticReport:
        """Call LLM Client on demand to analyze processes and diagnose anomaly."""
        logger.info("Running AI diagnostic for anomaly on node %s...", node_id)
        if not self._sllm:
            return DiagnosticReport(
                headline="Diagnostic IA temporairement indisponible",
                explanation="Le service d'IA n'est pas configuré sur ce serveur Master.",
                suggested_action="Veuillez configurer la clé LLM dans l'environnement du Master.",
                correlated_cause=[],
            )

        node = await nm.get_node(db, node_id)
        if not node:
            raise ValueError(f"Node not found: {node_id}")

        # Fetch active containers and services lists
        cached_services = node.get("cached_services_json") or "[]"
        cached_containers = node.get("cached_containers_json") or "[]"

        # Trim cached lists before prompt injection: the context must stay
        # bounded (at most 20 entries each, active/running preferred).
        services_prompt = self._trim_json_entries(
            cached_services, preferred_state="active"
        )
        containers_prompt = self._trim_json_entries(
            cached_containers, preferred_state="running"
        )

        # Get latest metrics
        latest_snap = None
        async with db.execute(
            "SELECT * FROM metrics_snapshots WHERE node_id = ? ORDER BY collected_at DESC LIMIT 1",
            (node_id,),
        ) as cursor:
            row = await cursor.fetchone()
            if row:
                latest_snap = dict(row)

        snap_str = json.dumps(latest_snap) if latest_snap else "Metrics unavailable"

        # Fetch recent audit log entries for this node (last 6 hours)
        recent_audit = []
        try:
            async with db.execute(
                """SELECT action, details_json, created_at
                   FROM audit_log WHERE node_id = ? AND created_at > ?
                   ORDER BY created_at DESC LIMIT 10""",
                (node_id, time.time() - 21600),
            ) as cursor:
                rows = await cursor.fetchall()
                recent_audit = [dict(r) for r in rows]
        except aiosqlite.Error:
            pass
        audit_str = json.dumps(recent_audit, indent=2) if recent_audit else "No recent audit events"

        lang_instruction = (
            "You must write the explanation, headline, and suggested_action in English."
            if locale == "en"
            else "Tu dois obligatoirement rédiger l'explication (explanation), le titre (headline) et l'action suggérée (suggested_action) en français."
        )
        messages = [
            {
                "role": "user",
                "content": (
                    f"Analyze this server anomaly for node '{node.get('name')}':\n"
                    f"- Active Services: {services_prompt}\n"
                    f"- Active Containers: {containers_prompt}\n"
                    f"- Current Metrics: {snap_str}\n"
                    f"- Recent Audit Events (last 6h): {audit_str}\n\n"
                    f"Diagnose what is causing the anomaly and suggest remediation actions. "
                    f"When evaluating the situation, consider recent audit events "
                    f"that may have triggered state changes. "
                    f"{lang_instruction}"
                ),
            }
        ]

        try:
            report = await self._sllm.create(
                response_model=DiagnosticReport,
                messages=messages,
            )
            logger.info("✓ AI Diagnostic complete for node %s", node_id)
            return report
        except Exception as ex:
            logger.error("Failed to call LLM for diagnostic on node %s: %s", node_id, ex)
            return DiagnosticReport(
                headline="Diagnostic IA temporairement indisponible",
                explanation=f"Une erreur est survenue lors de l'appel au service de diagnostic : {ex}",
                suggested_action="Veuillez inspecter manuellement les services systemd et conteneurs Docker via l'interface du serveur.",
                correlated_cause=[],
            )


def _percentile(data: list[float], p: float) -> float:
    if not data:
        return 0.0
    s = sorted(data)
    n = len(s)
    k = (n - 1) * (p / 100.0)
    f = int(k)
    c = f + 1
    if c >= n:
        return s[-1]
    return s[f] + (k - f) * (s[c] - s[f])


async def calculate_node_baseline(db: Any, node_id: str) -> dict[str, Any]:
    """
    Calcule la baseline statistique glissante (µ, σ, p75, p90, p99) par métrique pour un nœud.
    Si l'historique est < 3 jours (72h), positionne is_limited = True et applique les seuils absolus.
    """
    async with db.execute(
        "SELECT collected_at, cpu_percent, mem_percent, disk_percent "
        "FROM metrics_snapshots WHERE node_id = ? ORDER BY collected_at ASC",
        (node_id,),
    ) as cursor:
        raw_rows = await cursor.fetchall()

    if not raw_rows:
        return {
            "node_id": node_id,
            "data_window_hours": 0.0,
            "is_limited": True,
            "metrics": {
                "cpu": {"mean": 0.0, "std": 0.0, "p75": 50.0, "p90": 75.0, "p99": 90.0, "absolute_warning": 80.0, "absolute_critical": 95.0},
                "ram": {"mean": 0.0, "std": 0.0, "p75": 60.0, "p90": 80.0, "p99": 92.0, "absolute_warning": 85.0, "absolute_critical": 95.0},
                "disk": {"mean": 0.0, "std": 0.0, "p75": 70.0, "p90": 85.0, "p99": 95.0, "absolute_warning": 85.0, "absolute_critical": 95.0},
            },
        }

    rows = []
    for r in raw_rows:
        if hasattr(r, "keys"):
            rows.append(dict(r))
        else:
            rows.append({
                "collected_at": r[0],
                "cpu_percent": r[1],
                "mem_percent": r[2],
                "disk_percent": r[3],
            })

    ts_list = [r["collected_at"] for r in rows if r["collected_at"] is not None]
    data_window_hours = (max(ts_list) - min(ts_list)) / 3600.0 if ts_list else 0.0
    is_limited = data_window_hours < 72.0 or len(rows) < 50

    cpu_vals = [float(r["cpu_percent"]) for r in rows if r["cpu_percent"] is not None]
    ram_vals = [float(r["mem_percent"]) for r in rows if r["mem_percent"] is not None]
    disk_vals = [float(r["disk_percent"]) for r in rows if r["disk_percent"] is not None]

    def _calc_stats(vals: list[float], abs_warn: float, abs_crit: float) -> dict[str, float]:
        if not vals:
            return {"mean": 0.0, "std": 0.0, "p75": 50.0, "p90": 75.0, "p99": 90.0, "absolute_warning": abs_warn, "absolute_critical": abs_crit}
        mean_val = sum(vals) / len(vals)
        variance = sum((x - mean_val) ** 2 for x in vals) / len(vals)
        std_val = variance ** 0.5
        p75 = _percentile(vals, 75.0)
        p90 = _percentile(vals, 90.0)
        p99 = _percentile(vals, 99.0)
        return {
            "mean": round(mean_val, 1),
            "std": round(std_val, 1),
            "p75": round(p75, 1),
            "p90": round(p90, 1),
            "p99": round(p99, 1),
            "absolute_warning": abs_warn,
            "absolute_critical": abs_crit,
        }

    return {
        "node_id": node_id,
        "data_window_hours": round(data_window_hours, 1),
        "is_limited": is_limited,
        "metrics": {
            "cpu": _calc_stats(cpu_vals, 80.0, 95.0),
            "ram": _calc_stats(ram_vals, 85.0, 95.0),
            "disk": _calc_stats(disk_vals, 85.0, 95.0),
        },
    }

