"""
Vigile — Insights Manager

Implements the 3-phase insights and profiling system:
  - Phase 1: structured LLM profiling and fallback heuristic rules
  - Phase 2: real-time rule-based insights (disk regression, CPU/RAM thresholds)
  - Phase 3: real-time diagnostic LLM analysis for anomalies
"""

import asyncio
import json
import logging
import time
from typing import Any

import aiosqlite
from pydantic import BaseModel, Field

from master.core.llm_client import LLMClient
from master.core.node_manager import NodeManager
from master.core.structured_llm import StructuredLLM

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data Models for Node Profile
# ---------------------------------------------------------------------------


class HeavyProcessConfig(BaseModel):
    """Configuration for a heavy CPU process (container or systemd service)."""

    container_name: str | None = Field(default=None, description="Name of the Docker container")
    service_name: str | None = Field(default=None, description="Name of the Systemd service")
    cpu_threshold_percent: float = Field(
        description="CPU percentage threshold above which this is considered active"
    )
    label: str = Field(description="Human-friendly label of this process (e.g. 'Transcodage Plex')")


# ---------------------------------------------------------------------------
# Image-based classification helpers (avoids misidentifying LLM gateways as
# reverse proxies based solely on container name substring matching).
# ---------------------------------------------------------------------------

_LLM_IMAGE_KEYWORDS = frozenset({
    "litellm", "ollama", "vllm", "openai", "localai",
    "text-generation-inference", "tgi",
})


def _is_llm_related(container_name: str, image: str) -> bool:
    """Return True if the container name or image references an LLM/AI tool.

    Used to prevent LLM API gateways (e.g. litellm-proxy) from being
    misclassified as reverse proxies by the heuristic fallback profile.
    """
    haystack = f"{container_name.lower()} {image.lower()}"
    return any(kw in haystack for kw in _LLM_IMAGE_KEYWORDS)


class NodeProfile(BaseModel):
    """Memory profile of a node generated by LLM (or fallback) in Phase 1."""

    node_id: str
    known_heavy_processes: list[HeavyProcessConfig] = Field(default_factory=list)
    baseline_ram_percent: float = Field(
        default=70.0, description="Expected baseline RAM utilization percentage"
    )
    context_label: str = Field(
        default="Serveur homelab", description="Overall context label of the node"
    )


# ---------------------------------------------------------------------------
# Pydantic schema for Phase 3 Diagnostic Analysis
# ---------------------------------------------------------------------------


class DiagnosticReport(BaseModel):
    """Structured diagnostic report generated by LLM on demand during anomaly."""

    headline: str = Field(description="Short human-friendly summary of the diagnostic")
    explanation: str = Field(description="Detailed explanation of what is causing the load")
    suggested_action: str = Field(description="Remediation action recommended for the user")


# ---------------------------------------------------------------------------
# Insights Manager
# ---------------------------------------------------------------------------


class InsightsManager:
    """
    Manages node profiling, real-time insights generation, and anomaly diagnostics.
    Follows Dependency Injection: receives LLMClient inside constructor.
    """

    def __init__(self, llm_client: LLMClient | None = None) -> None:
        self._llm_client = llm_client
        self._sllm = StructuredLLM(llm_client) if llm_client else None

    # -----------------------------------------------------------------------
    # Phase 1: Profile Generation
    # -----------------------------------------------------------------------

    async def generate_profile(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        nm: NodeManager,
        force: bool = False,
        locale: str = "fr",
    ) -> NodeProfile:
        """
        Generate or update the node profile (Phase 1).
        Attempts to call the LLM, falls back to local rules if LLM fails or is disabled.
        """
        logger.info("Generating profile for node %s (force=%s)...", node_id, force)

        # 1. Fetch node info
        node = await nm.get_node(db, node_id)
        if not node:
            raise ValueError(f"Node not found: {node_id}")

        hostname = node.get("hostname") or ""
        os_name = node.get("os") or ""
        arch = node.get("arch") or ""

        # 2. Get containers and services lists (from cache, or live query if empty)
        services = []
        containers = []

        cached_services = node.get("cached_services_json")
        if cached_services:
            try:
                services = json.loads(cached_services)
            except Exception:
                pass

        cached_containers = node.get("cached_containers_json")
        if cached_containers:
            try:
                containers = json.loads(cached_containers)
            except Exception:
                pass

        # If cache is empty and node is connected, try to query them live to feed the profile
        if node.get("online"):
            if not services:
                try:
                    from master.plugins.systemd_plugin import parse_service_list

                    result = await nm.send_intent(node_id, {"action": "LIST_SERVICES"}, timeout=8.0)
                    if result.get("success"):
                        parsed = parse_service_list(result.get("output", ""))
                        if parsed:
                            services = parsed
                except Exception as e:
                    logger.warning("Profile gen: failed live services query: %s", e)

            if not containers:
                try:
                    from master.plugins.docker_plugin import parse_container_list

                    result = await nm.send_intent(
                        node_id, {"action": "LIST_CONTAINERS"}, timeout=8.0
                    )
                    if result.get("success"):
                        parsed = parse_container_list(result.get("output", ""))
                        if parsed:
                            containers = parsed
                except Exception as e:
                    logger.warning("Profile gen: failed live containers query: %s", e)

        # 3. Call LLM to generate profile
        profile = None
        if self._sllm and self._llm_client and self._llm_client.base_url:
            lang_instruction = (
                "You must write the node context label in English."
                if locale == "en"
                else "Tu dois obligatoirement rédiger le label de contexte (context_label) en français."
            )
            try:
                messages = [
                    {
                        "role": "user",
                        "content": (
                            f"Generate a NodeProfile for server '{node.get('name')}' with the following details:\n"
                            f"- Hostname: {hostname}\n"
                            f"- OS/Arch: {os_name} / {arch}\n"
                            f"- Active Systemd Services: {json.dumps(services[:30])}\n"
                            f"- Running Docker Containers: {json.dumps(containers[:30])}\n\n"
                            f"Analyze this server's context. Identify heavy CPU/RAM applications (like Plex, Jellyfin, PostgreSQL, Nginx, CI/CD runners, backups) "
                            f"and determine appropriate CPU utilization thresholds (e.g. 50% for Plex transcoding) "
                            f"where we should flag activity to the operator. Suggest a context label and expected baseline RAM. "
                            f"{lang_instruction}"
                        ),
                    }
                ]
                profile = await self._sllm.create(
                    response_model=NodeProfile,
                    messages=messages,
                    max_retries=2,
                )
                logger.info("✓ Node profile generated successfully via LLM for node %s", node_id)
            except Exception as ex:
                logger.warning(
                    "LLM profile generation failed for node %s: %s. Using local fallback.",
                    node_id,
                    ex,
                )

        # 4. Fallback to local heuristic rules
        if not profile:
            profile = self.generate_fallback_profile(
                node_id, hostname, os_name, services, containers
            )
            logger.info("✓ Generated fallback profile for node %s", node_id)

        # 5. Persist profile to DB
        now = time.time()
        await db.execute(
            """
            UPDATE nodes SET
                insight_profile = ?,
                insight_profile_generated_at = ?,
                cached_services_json = ?,
                cached_containers_json = ?
            WHERE id = ?
            """,
            (
                profile.model_dump_json(),
                now,
                json.dumps(services) if services else node.get("cached_services_json"),
                json.dumps(containers) if containers else node.get("cached_containers_json"),
                node_id,
            ),
        )
        await db.commit()

        return profile

    def generate_fallback_profile(
        self,
        node_id: str,
        hostname: str,
        os_name: str,
        services: list[dict[str, Any]],
        containers: list[dict[str, Any]],
    ) -> NodeProfile:
        """Generate a basic, rules-based NodeProfile when LLM is unavailable."""
        known_heavy = []

        # Analyze Docker containers
        for c in containers:
            c_name = c.get("name", "").lower()
            if "plex" in c_name or "jellyfin" in c_name:
                known_heavy.append(
                    HeavyProcessConfig(
                        container_name=c.get("name"),
                        cpu_threshold_percent=50.0,
                        label="Transcodage Multimédia (Plex/Jellyfin)",
                    )
                )
            elif "postgres" in c_name or "pg-" in c_name:
                known_heavy.append(
                    HeavyProcessConfig(
                        container_name=c.get("name"),
                        cpu_threshold_percent=40.0,
                        label="Requêtes Base de Données (PostgreSQL)",
                    )
                )
            elif "mysql" in c_name or "mariadb" in c_name:
                known_heavy.append(
                    HeavyProcessConfig(
                        container_name=c.get("name"),
                        cpu_threshold_percent=40.0,
                        label="Requêtes Base de Données (MySQL)",
                    )
                )
            elif _is_llm_related(c_name, c.get("image", "")):
                known_heavy.append(
                    HeavyProcessConfig(
                        container_name=c.get("name"),
                        cpu_threshold_percent=40.0,
                        label="Passerelle API LLM (IA Générative)",
                    )
                )
            elif "nginx" in c_name or "traefik" in c_name or "haproxy" in c_name or (
                "proxy" in c_name and not _is_llm_related(c_name, c.get("image", ""))
            ):
                known_heavy.append(
                    HeavyProcessConfig(
                        container_name=c.get("name"),
                        cpu_threshold_percent=30.0,
                        label="Trafic Web (Reverse Proxy)",
                    )
                )
            elif "runner" in c_name or "gitlab" in c_name or "jenkins" in c_name:
                known_heavy.append(
                    HeavyProcessConfig(
                        container_name=c.get("name"),
                        cpu_threshold_percent=60.0,
                        label="Compilation / Pipeline CI-CD",
                    )
                )

        # Analyze systemd services
        for s in services:
            s_name = s.get("name", "").lower()
            if "plex" in s_name:
                known_heavy.append(
                    HeavyProcessConfig(
                        service_name=s.get("name"),
                        cpu_threshold_percent=50.0,
                        label="Transcodage Plex Media Server",
                    )
                )
            elif "postgresql" in s_name or "mysql" in s_name:
                known_heavy.append(
                    HeavyProcessConfig(
                        service_name=s.get("name"),
                        cpu_threshold_percent=45.0,
                        label="Activité Base de Données",
                    )
                )
            elif "nginx" in s_name or "apache" in s_name:
                known_heavy.append(
                    HeavyProcessConfig(
                        service_name=s.get("name"),
                        cpu_threshold_percent=35.0,
                        label="Pic de Trafic Web",
                    )
                )
            elif "fail2ban" in s_name:
                known_heavy.append(
                    HeavyProcessConfig(
                        service_name=s.get("name"),
                        cpu_threshold_percent=20.0,
                        label="Analyse d'intrusions Fail2ban",
                    )
                )

        # Context label suggestion
        context = "Serveur général"
        host_lower = hostname.lower()
        if "web" in host_lower or "nginx" in host_lower:
            context = "Serveur Web / Applicatif"
        elif "db" in host_lower or "sql" in host_lower or "postgres" in host_lower:
            context = "Serveur de Base de Données"
        elif (
            "plex" in host_lower
            or "media" in host_lower
            or "nas" in host_lower
            or any("plex" in c.get("name", "").lower() for c in containers)
        ):
            context = "Homelab Médias & Stockage"

        return NodeProfile(
            node_id=node_id,
            known_heavy_processes=known_heavy,
            baseline_ram_percent=65.0,
            context_label=context,
        )

    # -----------------------------------------------------------------------
    # Phase 2: Real-time Insights (Deterministic)
    # -----------------------------------------------------------------------

    async def get_insights(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        nm: NodeManager,
        locale: str = "fr",
    ) -> dict[str, Any]:
        """
        Produce real-time insights for a node (Phase 2).
        Calculates disk slope on-the-fly and evaluates current CPU/RAM.
        """
        node = await nm.get_node(db, node_id)
        if not node:
            return {"node_id": node_id, "insights": [], "profile_confidence": "low"}

        # 1. Trigger profile generation automatically if missing and online
        profile_json = node.get("insight_profile")
        if not profile_json:
            if node.get("online"):
                # Spawn generation background task
                asyncio.create_task(self.generate_profile(node_id, db, nm, locale=locale))
                return {
                    "node_id": node_id,
                    "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "insights": [
                        {
                            "type": "status",
                            "severity": "info",
                            "icon": "🔄",
                            "headline": "Analyse du profil en cours",
                            "detail": "Vigilbot identifie les services et configure les seuils de charge...",
                        }
                    ],
                    "profile_confidence": "low",
                }
            else:
                return {
                    "node_id": node_id,
                    "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "insights": [
                        {
                            "type": "status",
                            "severity": "warning",
                            "icon": "⚠️",
                            "headline": "Profil manquant",
                            "detail": "Le serveur doit être connecté en ligne pour initialiser son profil d'insights.",
                        }
                    ],
                    "profile_confidence": "low",
                }

        profile = NodeProfile.model_validate_json(profile_json)

        # 2. Get latest metrics snapshot
        latest_snap = None
        async with db.execute(
            "SELECT * FROM metrics_snapshots WHERE node_id = ? ORDER BY collected_at DESC LIMIT 1",
            (node_id,),
        ) as cursor:
            row = await cursor.fetchone()
            if row:
                latest_snap = dict(row)

        if not latest_snap:
            return {
                "node_id": node_id,
                "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                "insights": [
                    {
                        "type": "status",
                        "severity": "warning",
                        "icon": "🔄",
                        "headline": "En attente de métriques",
                        "detail": "Aucun rapport de métriques n'a encore été stocké pour ce serveur.",
                    }
                ],
                "profile_confidence": "medium",
            }

        insights = []

        # --- A. DISK INSIGHT (On-the-fly Linear Regression) ---
        disk_insight = await self._calculate_disk_insight(node_id, db, latest_snap)
        if disk_insight:
            insights.append(disk_insight)

        # --- B. CPU INSIGHT ---
        cpu_insight = self._calculate_cpu_insight(latest_snap, profile, node)
        if cpu_insight:
            insights.append(cpu_insight)

        # --- C. RAM INSIGHT ---
        ram_insight = self._calculate_ram_insight(latest_snap, profile)
        if ram_insight:
            insights.append(ram_insight)

        return {
            "node_id": node_id,
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "insights": insights,
            "profile_confidence": "high" if node.get("online") else "medium",
        }

    async def _calculate_disk_insight(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        latest_snap: dict[str, Any],
    ) -> dict[str, Any] | None:
        """Calculate linear regression slope of disk usage and return insight."""
        disk_total = latest_snap.get("disk_total_bytes", 0)
        disk_used = latest_snap.get("disk_used_bytes", 0)
        disk_percent = latest_snap.get("disk_percent", 0.0)

        if disk_total == 0:
            return None

        # Query metrics snapshots from the last 24 hours (86400 seconds)
        now = time.time()
        limit_time = now - 86400

        snapshots = []
        async with db.execute(
            """
            SELECT collected_at, disk_used_bytes
            FROM metrics_snapshots
            WHERE node_id = ? AND collected_at >= ?
            ORDER BY collected_at ASC
            LIMIT 150
            """,
            (node_id, limit_time),
        ) as cursor:
            async for r in cursor:
                snapshots.append(dict(r))

        free_bytes = disk_total - disk_used
        free_gb = free_bytes / (1024**3)
        used_percent = round(disk_percent, 1)

        # Calculate slope only with enough snapshots AND sufficient time span.
        # With fewer points (or a very short window), filesystem noise yields
        # absurd extrapolations (e.g. +39000 GB/day from a 60s delta).
        slope = 0.0  # GB per day
        min_snapshots = 5
        min_timespan_seconds = 1800  # 30 minutes
        timespan = (
            (snapshots[-1]["collected_at"] - snapshots[0]["collected_at"])
            if len(snapshots) >= 2
            else 0
        )
        if len(snapshots) >= min_snapshots and timespan >= min_timespan_seconds:
            t0 = snapshots[0]["collected_at"]
            # Convert collected_at to days relative to first snapshot to avoid floating overflow
            x = [(s["collected_at"] - t0) / 86400.0 for s in snapshots]
            y = [s["disk_used_bytes"] / (1024**3) for s in snapshots]

            n = len(snapshots)
            sum_x = sum(x)
            sum_y = sum(y)
            sum_xx = sum(xi * xi for xi in x)
            sum_xy = sum(xi * yi for xi, yi in zip(x, y))

            denominator = n * sum_xx - sum_x * sum_x
            if abs(denominator) > 1e-6:
                slope = (n * sum_xy - sum_x * sum_y) / denominator
                if slope < 0.0:
                    slope = 0.0  # Ignore shrinking disk for the "full in" prediction
            else:
                slope = 0.0

        if slope > 0.01:  # Growth rate of at least 10 MB per day
            days_left = free_gb / slope

            if days_left < 14:
                severity = "critical"
                icon = "🚨"
            elif days_left < 60:
                severity = "warning"
                icon = "⚠️"
            else:
                severity = "ok"
                icon = "✅"

            # Human friendly time estimation
            if days_left < 1:
                headline = "Disque plein dans moins d'un jour !"
            elif days_left < 7:
                headline = f"Disque plein dans ~{round(days_left)} jours"
            else:
                weeks = int(days_left / 7)
                days = int(days_left % 7)
                if weeks < 5:
                    day_str = f" et {days}j" if days > 0 else ""
                    headline = f"Disque plein dans {weeks} sem{day_str}"
                else:
                    months = int(days_left / 30)
                    headline = f"Disque plein dans ~{months} mois"

            detail = f"Taux de croissance de +{slope:.2f} Go / jour"
        else:
            severity = "ok"
            icon = "✅"
            headline = "Disque stable"
            detail = "Plus de 6 mois d'autonomie restants"

        return {
            "type": "disk",
            "severity": severity,
            "icon": icon,
            "headline": headline,
            "detail": detail,
            "raw": {
                "used_percent": used_percent,
                "free_gb": round(free_gb, 1),
                "growth_gb_per_day": round(slope, 3),
            },
        }

    def _calculate_cpu_insight(
        self,
        latest_snap: dict[str, Any],
        profile: NodeProfile,
        node: dict[str, Any],
    ) -> dict[str, Any]:
        """Match current CPU load against node profile rules and active processes."""
        cpu_percent = latest_snap.get("cpu_percent", 0.0)

        # Parse active containers and services cache
        active_containers = []
        cached_containers = node.get("cached_containers_json")
        if cached_containers:
            try:
                active_containers = [
                    c.get("name")
                    for c in json.loads(cached_containers)
                    if c.get("state") == "running" or "up" in c.get("status", "").lower()
                ]
            except Exception:
                pass

        active_services = []
        cached_services = node.get("cached_services_json")
        if cached_services:
            try:
                active_services = [
                    s.get("service")
                    for s in json.loads(cached_services)
                    if s.get("state") == "active"
                ]
            except Exception:
                pass

        # Identify heavy processes that are active and exceed threshold
        culprit = None
        headline = "Serveur au repos"
        detail = "Activités d'arrière-plan normales"
        icon = "💤"

        # Check rules
        for p in profile.known_heavy_processes:
            # Check if this process config is running
            is_running = False
            if p.container_name and p.container_name in active_containers:
                is_running = True
            elif p.service_name and p.service_name in active_services:
                is_running = True

            if is_running and cpu_percent >= p.cpu_threshold_percent:
                culprit = p
                # If multiple processes exceed threshold, choose the one with higher threshold
                break

        if cpu_percent > 75:
            if culprit:
                severity = "warning"
                icon = "🔥"
                headline = f"Activité intense · {culprit.label}"
                detail = f"Charge soutenue ({cpu_percent:.0f}%) imputée à {culprit.container_name or culprit.service_name}"
            else:
                severity = "warning"
                icon = "⚠️"
                headline = "Charge élevée anormale"
                detail = "Aucun processus lourd connu n'est actif sur le système."
        elif cpu_percent > 40:
            if culprit:
                severity = "info"
                icon = "⚡"
                headline = f"Charge modérée · {culprit.label}"
                detail = f"Processus {culprit.container_name or culprit.service_name} actif ({cpu_percent:.0f}%)"
            else:
                severity = "info"
                icon = "🏃"
                headline = "Activité modérée"
                detail = f"Charge générale du serveur à {cpu_percent:.0f}%"
        else:
            severity = "ok"
            icon = "✅"
            headline = "CPU stable"
            detail = "Serveur calme et stable"

        return {
            "type": "cpu",
            "severity": severity,
            "icon": icon,
            "headline": headline,
            "detail": detail,
            "raw": {
                "cpu_percent": round(cpu_percent, 1),
                "culprit_container": culprit.container_name if culprit else None,
                "culprit_service": culprit.service_name if culprit else None,
            },
        }

    def _calculate_ram_insight(
        self, latest_snap: dict[str, Any], profile: NodeProfile
    ) -> dict[str, Any]:
        """Assess RAM and swap usage against profile baseline."""
        mem_percent = latest_snap.get("mem_percent", 0.0)
        mem_total = latest_snap.get("mem_total_bytes", 0)
        mem_used = latest_snap.get("mem_used_bytes", 0)
        swap_used = latest_snap.get("swap_used_bytes", 0)

        used_gb = mem_used / (1024**3)
        total_gb = mem_total / (1024**3)
        swap_mb = swap_used / (1024 * 1024)

        baseline = profile.baseline_ram_percent

        if mem_percent > 90:
            severity = "warning"
            icon = "⚠️"
            headline = "RAM presque saturée"
            detail = "Risque potentiel de ralentissement (OOM)"
        elif mem_percent > baseline:
            severity = "info"
            icon = "🐏"
            headline = "RAM active"
            detail = f"Utilisation supérieure à la ligne de base habituelle ({baseline:.0f}%)"
        else:
            severity = "ok"
            icon = "✅"
            headline = "Mémoire stable"
            detail = (
                "Aucune pression d'échange (swap)"
                if swap_mb < 50
                else f"Swap utilisé : {swap_mb:.0f} Mo"
            )

        return {
            "type": "ram",
            "severity": severity,
            "icon": icon,
            "headline": headline,
            "detail": detail,
            "raw": {
                "used_percent": round(mem_percent, 1),
                "used_gb": round(used_gb, 1),
                "total_gb": round(total_gb, 1),
                "swap_used_mb": round(swap_mb, 1),
            },
        }

    # -----------------------------------------------------------------------
    # Phase 3: Anomaly AI Analysis (On-Demand)
    # -----------------------------------------------------------------------

    async def analyze_anomaly(
        self,
        node_id: str,
        db: aiosqlite.Connection,
        nm: NodeManager,
        locale: str = "fr",
    ) -> DiagnosticReport:
        """Call LLM Client on demand to analyze processes and diagnose anomaly."""
        logger.info("Running AI diagnostic for anomaly on node %s...", node_id)
        if not self._sllm:
            return DiagnosticReport(
                headline="Diagnostic IA temporairement indisponible",
                explanation="Le service d'IA n'est pas configuré sur ce serveur Master.",
                suggested_action="Veuillez configurer la clé LLM dans l'environnement du Master.",
            )

        node = await nm.get_node(db, node_id)
        if not node:
            raise ValueError(f"Node not found: {node_id}")

        # Fetch active containers and services lists
        cached_services = node.get("cached_services_json") or "[]"
        cached_containers = node.get("cached_containers_json") or "[]"

        # Get latest metrics
        latest_snap = None
        async with db.execute(
            "SELECT * FROM metrics_snapshots WHERE node_id = ? ORDER BY collected_at DESC LIMIT 1",
            (node_id,),
        ) as cursor:
            row = await cursor.fetchone()
            if row:
                latest_snap = dict(row)

        snap_str = json.dumps(latest_snap) if latest_snap else "Metrics unavailable"

        lang_instruction = (
            "You must write the explanation, headline, and suggested_action in English."
            if locale == "en"
            else "Tu dois obligatoirement rédiger l'explication (explanation), le titre (headline) et l'action suggérée (suggested_action) en français."
        )
        messages = [
            {
                "role": "user",
                "content": (
                    f"Analyze this server anomaly for node '{node.get('name')}':\n"
                    f"- Active Services: {cached_services}\n"
                    f"- Active Containers: {cached_containers}\n"
                    f"- Current Metrics: {snap_str}\n\n"
                    f"Diagnose what is causing the anomaly and suggest remediation actions. "
                    f"{lang_instruction}"
                ),
            }
        ]

        try:
            report = await self._sllm.create(
                response_model=DiagnosticReport,
                messages=messages,
                max_retries=2,
            )
            logger.info("✓ AI Diagnostic complete for node %s", node_id)
            return report
        except Exception as ex:
            logger.error("Failed to call LLM for diagnostic on node %s: %s", node_id, ex)
            return DiagnosticReport(
                headline="Diagnostic IA temporairement indisponible",
                explanation=f"Une erreur est survenue lors de l'appel au service de diagnostic : {ex}",
                suggested_action="Veuillez inspecter manuellement les services systemd et conteneurs Docker via l'interface du serveur.",
            )
