"""
Vigile — Nodes API: kickstart script endpoints

Provides the install shell/PowerShell script templates and the public
``/kickstart.sh`` / ``/kickstart.ps1`` endpoints.
"""

from __future__ import annotations

from fastapi import Depends, Request
from fastapi.responses import PlainTextResponse

from master.api.nodes_router import router
from master.api.rate_limits import KICKSTART_LIMIT
from master.core.rate_limiter import rate_limiter

# ---------------------------------------------------------------------------
# Kickstart script templates
# ---------------------------------------------------------------------------

KICKSTART_TEMPLATE = """\
#!/usr/bin/env bash
# Vigile — Worker Kickstart Script
# Generated by the Master Node. DO NOT EDIT.
#
# Usage:
#   curl -sSL $master_url/api/nodes/kickstart.sh | bash -s -- --token TOKEN --master MASTER_URL
#
# Requirements: curl, sha256sum (or shasum on macOS), systemd or launchd

set -eu

# ── Privilege check ─────────────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root. Please run with sudo at the end of the pipe:" >&2
    echo "  curl -sSL $master_url/api/nodes/kickstart.sh | sudo bash -s -- --token <token> --master <master_url>" >&2
    exit 1
fi

# ── Cleanup trap ────────────────────────────────────────────────────────────
TMPDIR_VIGILE="$(mktemp -d /tmp/vigile_install.XXXXXX)"
cleanup() {
    rm -rf "$TMPDIR_VIGILE"
}
trap cleanup EXIT

# ── Argument parsing ─────────────────────────────────────────────────────────
JOIN_TOKEN=""
MASTER_URL=""
UNINSTALL=false
CA_BUNDLE=""
CACERT=""
OFFLINE=false

while [ $# -gt 0 ]; do
    case "$1" in
        --token)       JOIN_TOKEN="$2"; shift 2 ;;
        --master)      MASTER_URL="$2"; shift 2 ;;
        --ca-bundle)   CA_BUNDLE="$2"; shift 2 ;;
        --cacert)      CACERT="$2"; shift 2 ;;
        --offline)     OFFLINE=true; shift ;;
        --uninstall)   UNINSTALL=true; shift ;;
        *)             echo "Unknown argument: $1"; exit 1 ;;
    esac
done

# ── CA certificate bundle ─────────────────────────────────────────────────────
# Allow override via CUSTOM_CA_BUNDLE env var (set before running the script).
if [ -z "$CA_BUNDLE" ] && [ -n "${CUSTOM_CA_BUNDLE:-}" ]; then
    CA_BUNDLE="$CUSTOM_CA_BUNDLE"
fi

# Build curl CA options
CURL_CA_OPTS=""
if [ -n "$CA_BUNDLE" ]; then
    CURL_CA_OPTS="--ca-bundle $CA_BUNDLE"
elif [ -n "$CACERT" ]; then
    CURL_CA_OPTS="--cacert $CACERT"
fi

if [ "$UNINSTALL" = true ]; then
    echo "[vigile] Uninstalling Worker..."
    if command -v systemctl >/dev/null 2>&1 && (systemctl is-active vigile-worker >/dev/null 2>&1 || systemctl is-enabled vigile-worker >/dev/null 2>&1); then
        echo "[vigile] Disabling and stopping systemd service..."
        systemctl disable --now vigile-worker || true
        rm -f /etc/systemd/system/vigile-worker.service
        systemctl daemon-reload
    fi
    if command -v launchctl >/dev/null 2>&1; then
        echo "[vigile] Unloading and removing macOS launchd service..."
        launchctl unload -w /Library/LaunchDaemons/com.vigile.worker.plist 2>/dev/null || true
        rm -f /Library/LaunchDaemons/com.vigile.worker.plist
        rm -f /var/log/vigile-worker.log /var/log/vigile-worker.err
    fi
    echo "[vigile] Removing binary and configurations..."
    rm -f /usr/local/bin/vigile-worker
    rm -rf /etc/vigile
    echo "[vigile] Uninstallation complete!"
    exit 0
fi

if [ -z "$JOIN_TOKEN" ] || [ -z "$MASTER_URL" ]; then
    echo "ERROR: --token and --master are required." >&2
    exit 1
fi

# Sanitize MASTER_URL to prevent command injection in heredocs
if ! echo "$MASTER_URL" | grep -qE '^https?://[a-zA-Z0-9._:/@-]+$'; then
    echo "ERROR: MASTER_URL contains invalid characters: $MASTER_URL" >&2
    exit 1
fi


# ── OS / Arch detection ──────────────────────────────────────────────────────
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"

case "$ARCH" in
    x86_64)         ARCH="amd64" ;;
    aarch64|arm64)  ARCH="arm64" ;;
    armv7l)         ARCH="armv7" ;;
    *)
        echo "ERROR: Unsupported architecture: $ARCH" >&2
        exit 1
        ;;
esac

case "$OS" in
    linux|darwin|freebsd) ;;
    *)
        echo "ERROR: Unsupported OS: $OS" >&2
        exit 1
        ;;
esac

echo "[vigile] Detected: $OS/$ARCH"

# ── Binary download ───────────────────────────────────────────────────────────
BINARY_URL="$MASTER_URL/api/nodes/binary/$OS/$ARCH/worker"
HASH_URL="$BINARY_URL.sha256"
BINARY_PATH="$TMPDIR_VIGILE/worker"

echo "[vigile] Downloading Worker binary..."
curl $CURL_CA_OPTS -sSfL "$BINARY_URL" -o "$BINARY_PATH"

echo "[vigile] Verifying SHA256..."
EXPECTED_HASH="$(curl $CURL_CA_OPTS -sSfL "$HASH_URL" | awk '{print $1}')"
if command -v sha256sum >/dev/null 2>&1; then
    ACTUAL_HASH="$(sha256sum "$BINARY_PATH" | awk '{print $1}')"
else
    ACTUAL_HASH="$(shasum -a 256 "$BINARY_PATH" | awk '{print $1}')"
fi

if [ "$EXPECTED_HASH" != "$ACTUAL_HASH" ]; then
    echo "ERROR: SHA256 mismatch! Binary may be corrupted or tampered." >&2
    echo "  Expected: $EXPECTED_HASH" >&2
    echo "  Got:      $ACTUAL_HASH" >&2
    exit 1
fi

echo "[vigile] SHA256 OK."

# ── Minisign signature verification (optional if minisign CLI available) ───
SIG_URL="$BINARY_URL.sig"
PUBKEY_URL="$MASTER_URL/api/nodes/binary/public-key"

if command -v minisign >/dev/null 2>&1; then
    echo "[vigile] Verifying minisign signature..."
    PUBKEY="$(curl $CURL_CA_OPTS -sSfL "$PUBKEY_URL" 2>/dev/null || true)"
    SIG_FILE="$TMPDIR_VIGILE/worker.sig"
    if [ -n "$PUBKEY" ] && curl $CURL_CA_OPTS -sSfL "$SIG_URL" -o "$SIG_FILE" 2>/dev/null; then
        KEY_LINE="$(echo "$PUBKEY" | awk 'NR==2')"
        if [ -n "$KEY_LINE" ] && minisign -Vm "$BINARY_PATH" -P "$KEY_LINE" -x "$SIG_FILE" >/dev/null 2>&1; then
            echo "[vigile] Signature OK."
        else
            echo "ERROR: Minisign signature verification failed — binary rejected." >&2
            exit 1
        fi
    fi
else
    echo "[vigile] WARNING: minisign CLI not found — signature verification skipped (SHA256 verified)."
fi

chmod +x "$BINARY_PATH"

# ── Installation ──────────────────────────────────────────────────────────────
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/vigile"

echo "[vigile] Installing Worker to $INSTALL_DIR/vigile-worker..."
install -m 0755 "$BINARY_PATH" "$INSTALL_DIR/vigile-worker"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
if [ ! -d "$CONFIG_DIR" ]; then
    echo "ERROR: Failed to create $CONFIG_DIR" >&2
    exit 1
fi

echo "[vigile] Storing enrollment token..."
printf '%s' "$JOIN_TOKEN" > "$CONFIG_DIR/enrollment.token"
chmod 600 "$CONFIG_DIR/enrollment.token"

printf '%s' "$MASTER_URL" > "$CONFIG_DIR/master_url"
chmod 600 "$CONFIG_DIR/master_url"

# ── Systemd service installation ──────────────────────────────────────────────
if command -v systemctl >/dev/null 2>&1; then
    cat > /etc/systemd/system/vigile-worker.service <<EOF
[Unit]
Description=Vigile — Worker Node
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/vigile-worker
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=vigile-worker
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/etc/vigile
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable --now vigile-worker
    echo "[vigile] systemd service enabled and started."
    echo "[vigile] Installation complete! The Worker will enroll automatically."
    echo "[vigile] Check status: systemctl status vigile-worker"

else
    local_allow_insecure=""
    case "$MASTER_URL" in
        http://*|ws://*) local_allow_insecure="ALLOW_INSECURE=true" ;;
    esac

    if command -v launchctl >/dev/null 2>&1; then
        echo "[vigile] macOS launchd detected. Installing service..."
        PLIST_PATH="/Library/LaunchDaemons/com.vigile.worker.plist"
        cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.vigile.worker</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/vigile-worker</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/var/log/vigile-worker.log</string>
    <key>StandardErrorPath</key>
    <string>/var/log/vigile-worker.err</string>
EOF

        if [ -n "$local_allow_insecure" ]; then
            cat >> "$PLIST_PATH" <<EOF
    <key>EnvironmentVariables</key>
    <dict>
        <key>ALLOW_INSECURE</key>
        <string>true</string>
    </dict>
EOF
        fi

        cat >> "$PLIST_PATH" <<EOF
</dict>
</plist>
EOF

        chmod 644 "$PLIST_PATH"
        launchctl unload -w "$PLIST_PATH" 2>/dev/null || true
        launchctl load -w "$PLIST_PATH"
        echo "[vigile] launchd service enabled and started."
        echo "[vigile] Installation complete! The Worker will enroll automatically."
        echo "[vigile] Check logs: tail -f /var/log/vigile-worker.log"
    else
        echo "[vigile] To start the worker manually, run:"
        echo "  sudo ${local_allow_insecure:+$local_allow_insecure }/usr/local/bin/vigile-worker --master ${MASTER_URL} --token ${JOIN_TOKEN}"
        echo "[vigile] Once /etc/vigile is populated you can simplify to:"
        echo "  sudo ${local_allow_insecure:+$local_allow_insecure }/usr/local/bin/vigile-worker"
        echo "[vigile] Installation complete!"
    fi
fi
"""

KICKSTART_PS1_TEMPLATE = """\
# Windows PowerShell Kickstart Script for Vigile Worker Node
# Generated by the Master Node. DO NOT EDIT.
#
# Usage (run as Administrator):
#   Invoke-WebRequest -Uri "$master_url/api/nodes/kickstart.ps1" -OutFile kickstart.ps1
#   .\\kickstart.ps1 -Token <TOKEN> -Master <MASTER_URL>

param(
    [Parameter(Mandatory=$true)] [string]$Token,
    [Parameter(Mandatory=$true)] [string]$Master,
    [switch]$Uninstall
)

$InstallDir  = "$env:ProgramFiles\\vigile"
$ConfigDir   = "$env:ProgramData\\vigile"
$BinaryPath  = "$InstallDir\\vigile-worker.exe"
$ServiceName = "vigile-worker"

# Check administrator privileges
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
$isAdmin = $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Error "ERROR: This script must be run as Administrator."
    exit 1
}

if ($Uninstall) {
    Write-Host "[vigile] Uninstalling Worker..."
    $service = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    if ($service) {
        Write-Host "[vigile] Stopping and removing Windows Service..."
        sc.exe stop $ServiceName 2>$null | Out-Null
        Start-Sleep -Seconds 2
        sc.exe delete $ServiceName 2>$null | Out-Null
    }
    if (Test-Path $InstallDir) {
        Remove-Item -Recurse -Force $InstallDir -ErrorAction SilentlyContinue
    }
    if (Test-Path $ConfigDir) {
        Remove-Item -Recurse -Force $ConfigDir -ErrorAction SilentlyContinue
    }
    Write-Host "[vigile] Uninstallation complete!"
    exit 0
}

# CPU Architecture check (strictly amd64 supported)
$arch = if ([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture -eq "Arm64") { "arm64" } else { "amd64" }
if ($arch -ne "amd64") {
    Write-Error "ERROR: Unsupported architecture $arch. Only amd64 is supported on Windows."
    exit 1
}

$binaryUrl = "$Master/api/nodes/binary/windows/$arch/worker"
$hashUrl   = "$binaryUrl.sha256"

Write-Host "[vigile] Downloading Worker binary from $binaryUrl..."
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Invoke-WebRequest -Uri $binaryUrl -OutFile $BinaryPath

Write-Host "[vigile] Verifying SHA256..."
$expectedHash = (Invoke-WebRequest -Uri $hashUrl -UseBasicParsing).Content.Trim().Split()[0]
$actualHash   = (Get-FileHash -Algorithm SHA256 $BinaryPath).Hash.ToLower()

if ($expectedHash -ne $actualHash) {
    Write-Error "ERROR: SHA256 mismatch! Binary may be corrupted."
    Write-Error "  Expected: $expectedHash"
    Write-Error "  Got:      $actualHash"
    exit 1
}
Write-Host "[vigile] SHA256 OK."

New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
$Token  | Out-File -Encoding ASCII -NoNewline "$ConfigDir\\enrollment.token"
$Master | Out-File -Encoding ASCII -NoNewline "$ConfigDir\\master_url"

Write-Host "[vigile] Storing enrollment token and configs to $ConfigDir..."

# Install and start Windows Service via sc.exe (Native Windows Services)
Write-Host "[vigile] Installing Windows Service '$ServiceName'..."
# Check if service already exists
$existingService = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existingService) {
    sc.exe stop $ServiceName 2>$null | Out-Null
    sc.exe delete $ServiceName 2>$null | Out-Null
    Start-Sleep -Seconds 1
}

sc.exe create $ServiceName binPath= "`"$BinaryPath`"" start= auto DisplayName= "Vigile Worker Node"
sc.exe description $ServiceName "Vigile Worker Agent Node for Orchestration."
sc.exe start $ServiceName

Write-Host "[vigile] Service installed and started."
Write-Host "[vigile] Verify status via: Get-Service -Name $ServiceName"
Write-Host "[vigile] Installation complete!"
"""


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.get(
    "/kickstart.sh",
    response_class=PlainTextResponse,
    summary="Download the Worker installation script",
    dependencies=[Depends(rate_limiter.dependency(KICKSTART_LIMIT))],
)
async def get_kickstart_script(request: Request) -> PlainTextResponse:
    """
    Return the kickstart shell script.

    This endpoint is public (no auth required) so the curl | sh pipeline works
    without pre-authentication. Security comes from the JOIN_TOKEN validation
    in Phase 2 of the enrollment process.
    """
    # Sanitize: escape $ to prevent bash variable expansion in the generated script
    safe_url = request.app.state.master_url.replace("$", "\\$")
    script = KICKSTART_TEMPLATE.replace("$master_url", safe_url)
    return PlainTextResponse(
        content=script,
        media_type="text/x-sh",
        headers={"Content-Disposition": "inline; filename=kickstart.sh"},
    )


@router.get(
    "/kickstart.ps1",
    response_class=PlainTextResponse,
    summary="Download the Windows Worker installation PowerShell script",
    dependencies=[Depends(rate_limiter.dependency(KICKSTART_LIMIT))],
)
async def get_kickstart_ps1_script(request: Request) -> PlainTextResponse:
    """
    Return the kickstart PowerShell script.

    This endpoint is public (no auth required) so it can be directly downloaded and executed.
    """
    safe_url = request.app.state.master_url.replace("$", "`$")
    script = KICKSTART_PS1_TEMPLATE.replace("$master_url", safe_url)
    return PlainTextResponse(
        content=script,
        media_type="text/plain",
        headers={"Content-Disposition": "inline; filename=kickstart.ps1"},
    )
