from __future__ import annotations

"""
Vigile — Nodes API

Endpoints:
  POST   /api/nodes/generate-join            Admin: generate JOIN_TOKEN + curl command
  GET    /api/nodes/kickstart.sh             Public: download the kickstart bash script
  GET    /api/nodes/binary/{os}/{arch}       Public: download Worker binary (Sprint 2)
  GET    /api/nodes                          Operator+: list all nodes
  GET    /api/nodes/{node_id}                Operator+: node details
  GET    /api/nodes/{node_id}/stats          Operator+: latest metrics snapshots
  DELETE /api/nodes/{node_id}                Admin: hard-delete a node (cascades to tokens, metrics, etc.)
"""

import json
import logging
import time
import uuid
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request, status
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field

from master.api.demo_data import DEMO_NODES, get_demo_logs, get_demo_metrics, get_demo_node, is_demo
from master.api.deps import (
    DB,
    CurrentUser,
    Insights,
    get_locale,
    get_node_manager,
    get_security,
    require_role,
)
from master.api.rate_limits import KICKSTART_LIMIT
from master.core.audit import AuditAction, log_action
from master.core.enums import WorkerAction
from master.core.insights import DiagnosticReport, HeavyProcessConfig, NodeProfile
from master.core.node_manager import NodeManager, NodeState
from master.core.rate_limiter import rate_limiter
from master.core.security_manager import SecurityManager
from master.db.disk_scan_cache import get_cached_disk_scan, set_cached_disk_scan
from master.schemas.disk_scan import DiskScanResult

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/nodes", tags=["nodes"])


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------


class GenerateJoinRequest(BaseModel):
    name: str | None = Field(
        default=None, max_length=128, description="Optional pre-filled human label"
    )
    group: str | None = Field(default=None, max_length=128, description="Optional group/tag")
    ip_prefix: str = Field(
        default="",
        max_length=64,
        pattern=r"^$|^[\d.]+$",
        description="DEPRECATED, ignored. Kept for back-compat with older clients.",
    )


class NodePatchRequest(BaseModel):
    name: str | None = Field(default=None, min_length=1, max_length=128)
    group: str | None = Field(default=None, max_length=128)
    disabled: bool | None = None


class ConfigureRequest(BaseModel):
    name: str = Field(..., min_length=1, max_length=128)
    group: str | None = Field(default=None, max_length=128)


class JoinTokenResponse(BaseModel):
    node_id: str
    token: str
    expires_in: int  # seconds
    curl_command: str


class NodeResponse(BaseModel):
    id: str
    name: str
    hostname: str | None
    machine_id: str | None
    arch: str | None
    os: str | None
    state: str
    online: bool
    last_heartbeat: float | None
    enrolled_at: float | None
    created_at: float
    updated_at: float
    group: str | None
    disabled: bool
    enrolled_recently: bool
    version: str | None = None
    cpu_percent: float | None = None
    memory_percent: float | None = None
    disk_percent: float | None = None
    uptime_seconds: float | None = None


class BulkNodeStatus(BaseModel):
    cpu: float | None = None
    mem: float | None = None
    disk: float | None = None
    uptime: float | None = None
    containers_count: int | None = None


class BulkStatusResponse(BaseModel):
    statuses: dict[str, BulkNodeStatus]


# ---------------------------------------------------------------------------
# Kickstart script template
# ---------------------------------------------------------------------------

KICKSTART_TEMPLATE = """\
#!/usr/bin/env bash
# Vigile — Worker Kickstart Script
# Generated by the Master Node. DO NOT EDIT.
#
# Usage:
#   curl -sSL $master_url/api/nodes/kickstart.sh | bash -s -- --token TOKEN --master MASTER_URL
#
# Requirements: curl, sha256sum (or shasum on macOS), systemd or launchd

set -euo pipefail

# ── Privilege check ─────────────────────────────────────────────────────────
if [ "$(id -u)" -ne 0 ]; then
    echo "ERROR: This script must be run as root. Please run with sudo at the end of the pipe:" >&2
    echo "  curl -sSL $master_url/api/nodes/kickstart.sh | sudo bash -s -- --token <token> --master <master_url>" >&2
    exit 1
fi

# ── Cleanup trap ────────────────────────────────────────────────────────────
TMPDIR_VIGILE="$(mktemp -d /tmp/vigile_install.XXXXXX)"
cleanup() {
    rm -rf "$TMPDIR_VIGILE"
}
trap cleanup EXIT

# ── Argument parsing ─────────────────────────────────────────────────────────
JOIN_TOKEN=""
MASTER_URL=""
UNINSTALL=false
CA_BUNDLE=""
CACERT=""
OFFLINE=false

while [ $# -gt 0 ]; do
    case "$1" in
        --token)       JOIN_TOKEN="$2"; shift 2 ;;
        --master)      MASTER_URL="$2"; shift 2 ;;
        --ca-bundle)   CA_BUNDLE="$2"; shift 2 ;;
        --cacert)      CACERT="$2"; shift 2 ;;
        --offline)     OFFLINE=true; shift ;;
        --uninstall)   UNINSTALL=true; shift ;;
        *)             echo "Unknown argument: $1"; exit 1 ;;
    esac
done

# ── CA certificate bundle ─────────────────────────────────────────────────────
# Allow override via CUSTOM_CA_BUNDLE env var (set before running the script).
if [ -z "$CA_BUNDLE" ] && [ -n "${CUSTOM_CA_BUNDLE:-}" ]; then
    CA_BUNDLE="$CUSTOM_CA_BUNDLE"
fi

# Build curl CA options
CURL_CA_OPTS=""
if [ -n "$CA_BUNDLE" ]; then
    CURL_CA_OPTS="--ca-bundle $CA_BUNDLE"
elif [ -n "$CACERT" ]; then
    CURL_CA_OPTS="--cacert $CACERT"
fi

if [ "$UNINSTALL" = true ]; then
    echo "[vigile] Uninstalling Worker..."
    if command -v systemctl &>/dev/null && (systemctl is-active vigile-worker &>/dev/null || systemctl is-enabled vigile-worker &>/dev/null); then
        echo "[vigile] Disabling and stopping systemd service..."
        systemctl disable --now vigile-worker || true
        rm -f /etc/systemd/system/vigile-worker.service
        systemctl daemon-reload
    fi
    if command -v launchctl &>/dev/null; then
        echo "[vigile] Unloading and removing macOS launchd service..."
        launchctl unload -w /Library/LaunchDaemons/com.vigile.worker.plist 2>/dev/null || true
        rm -f /Library/LaunchDaemons/com.vigile.worker.plist
        rm -f /var/log/vigile-worker.log /var/log/vigile-worker.err
    fi
    echo "[vigile] Removing binary and configurations..."
    rm -f /usr/local/bin/vigile-worker
    rm -rf /etc/vigile
    echo "[vigile] Uninstallation complete!"
    exit 0
fi

if [ -z "$JOIN_TOKEN" ] || [ -z "$MASTER_URL" ]; then
    echo "ERROR: --token and --master are required." >&2
    exit 1
fi


# ── OS / Arch detection ──────────────────────────────────────────────────────
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"

case "$ARCH" in
    x86_64)         ARCH="amd64" ;;
    aarch64|arm64)  ARCH="arm64" ;;
    armv7l)         ARCH="armv7" ;;
    *)
        echo "ERROR: Unsupported architecture: $ARCH" >&2
        exit 1
        ;;
esac

case "$OS" in
    linux|darwin|freebsd) ;;
    *)
        echo "ERROR: Unsupported OS: $OS" >&2
        exit 1
        ;;
esac

echo "[vigile] Detected: $OS/$ARCH"

# ── Binary download ───────────────────────────────────────────────────────────
BINARY_URL="$MASTER_URL/api/nodes/binary/$OS/$ARCH/worker"
HASH_URL="$BINARY_URL.sha256"
BINARY_PATH="$TMPDIR_VIGILE/worker"

echo "[vigile] Downloading Worker binary..."
curl $CURL_CA_OPTS -sSfL "$BINARY_URL" -o "$BINARY_PATH"

echo "[vigile] Verifying SHA256..."
EXPECTED_HASH="$(curl $CURL_CA_OPTS -sSfL "$HASH_URL" | awk '{print $1}')"
if command -v sha256sum &>/dev/null; then
    ACTUAL_HASH="$(sha256sum "$BINARY_PATH" | awk '{print $1}')"
else
    ACTUAL_HASH="$(shasum -a 256 "$BINARY_PATH" | awk '{print $1}')"
fi

if [ "$EXPECTED_HASH" != "$ACTUAL_HASH" ]; then
    echo "ERROR: SHA256 mismatch! Binary may be corrupted or tampered." >&2
    echo "  Expected: $EXPECTED_HASH" >&2
    echo "  Got:      $ACTUAL_HASH" >&2
    exit 1
fi

echo "[vigile] SHA256 OK."
chmod +x "$BINARY_PATH"

# ── Installation ──────────────────────────────────────────────────────────────
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/vigile"

echo "[vigile] Installing Worker to $INSTALL_DIR/vigile-worker..."
install -m 0755 "$BINARY_PATH" "$INSTALL_DIR/vigile-worker"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"
if [ ! -d "$CONFIG_DIR" ]; then
    echo "ERROR: Failed to create $CONFIG_DIR" >&2
    exit 1
fi

echo "[vigile] Storing enrollment token..."
printf '%s' "$JOIN_TOKEN" > "$CONFIG_DIR/enrollment.token"
chmod 600 "$CONFIG_DIR/enrollment.token"

printf '%s' "$MASTER_URL" > "$CONFIG_DIR/master_url"
chmod 600 "$CONFIG_DIR/master_url"

# ── Systemd service installation ──────────────────────────────────────────────
if command -v systemctl &>/dev/null; then
    cat > /etc/systemd/system/vigile-worker.service <<EOF
[Unit]
Description=Vigile — Worker Node
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/vigile-worker
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=vigile-worker
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/etc/vigile
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable --now vigile-worker
    echo "[vigile] systemd service enabled and started."
    echo "[vigile] Installation complete! The Worker will enroll automatically."
    echo "[vigile] Check status: systemctl status vigile-worker"

else
    local_allow_insecure=""
    case "$MASTER_URL" in
        http://*|ws://*) local_allow_insecure="ALLOW_INSECURE=true" ;;
    esac

    if command -v launchctl &>/dev/null; then
        echo "[vigile] macOS launchd detected. Installing service..."
        PLIST_PATH="/Library/LaunchDaemons/com.vigile.worker.plist"
        cat > "$PLIST_PATH" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.vigile.worker</string>
    <key>ProgramArguments</key>
    <array>
        <string>/usr/local/bin/vigile-worker</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>/var/log/vigile-worker.log</string>
    <key>StandardErrorPath</key>
    <string>/var/log/vigile-worker.err</string>
EOF

        if [ -n "$local_allow_insecure" ]; then
            cat >> "$PLIST_PATH" <<EOF
    <key>EnvironmentVariables</key>
    <dict>
        <key>ALLOW_INSECURE</key>
        <string>true</string>
    </dict>
EOF
        fi

        cat >> "$PLIST_PATH" <<EOF
</dict>
</plist>
EOF

        chmod 644 "$PLIST_PATH"
        launchctl unload -w "$PLIST_PATH" 2>/dev/null || true
        launchctl load -w "$PLIST_PATH"
        echo "[vigile] launchd service enabled and started."
        echo "[vigile] Installation complete! The Worker will enroll automatically."
        echo "[vigile] Check logs: tail -f /var/log/vigile-worker.log"
    else
        echo "[vigile] To start the worker manually, run:"
        echo "  sudo ${local_allow_insecure:+$local_allow_insecure }/usr/local/bin/vigile-worker --master ${MASTER_URL} --token ${JOIN_TOKEN}"
        echo "[vigile] Once /etc/vigile is populated you can simplify to:"
        echo "  sudo ${local_allow_insecure:+$local_allow_insecure }/usr/local/bin/vigile-worker"
        echo "[vigile] Installation complete!"
    fi
fi
"""


KICKSTART_PS1_TEMPLATE = """\
# Windows PowerShell Kickstart Script for Vigile Worker Node
# Generated by the Master Node. DO NOT EDIT.
#
# Usage (run as Administrator):
#   Invoke-WebRequest -Uri "$master_url/api/nodes/kickstart.ps1" -OutFile kickstart.ps1
#   .\\kickstart.ps1 -Token <TOKEN> -Master <MASTER_URL>

param(
    [Parameter(Mandatory=$true)] [string]$Token,
    [Parameter(Mandatory=$true)] [string]$Master,
    [switch]$Uninstall
)

$InstallDir  = "$env:ProgramFiles\\vigile"
$ConfigDir   = "$env:ProgramData\\vigile"
$BinaryPath  = "$InstallDir\\vigile-worker.exe"
$ServiceName = "vigile-worker"

# Check administrator privileges
$currentPrincipal = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
$isAdmin = $currentPrincipal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Error "ERROR: This script must be run as Administrator."
    exit 1
}

if ($Uninstall) {
    Write-Host "[vigile] Uninstalling Worker..."
    $service = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
    if ($service) {
        Write-Host "[vigile] Stopping and removing Windows Service..."
        sc.exe stop $ServiceName 2>$null | Out-Null
        Start-Sleep -Seconds 2
        sc.exe delete $ServiceName 2>$null | Out-Null
    }
    if (Test-Path $InstallDir) {
        Remove-Item -Recurse -Force $InstallDir -ErrorAction SilentlyContinue
    }
    if (Test-Path $ConfigDir) {
        Remove-Item -Recurse -Force $ConfigDir -ErrorAction SilentlyContinue
    }
    Write-Host "[vigile] Uninstallation complete!"
    exit 0
}

# CPU Architecture check (strictly amd64 supported)
$arch = if ([System.Runtime.InteropServices.RuntimeInformation]::OSArchitecture -eq "Arm64") { "arm64" } else { "amd64" }
if ($arch -ne "amd64") {
    Write-Error "ERROR: Unsupported architecture $arch. Only amd64 is supported on Windows."
    exit 1
}

$binaryUrl = "$Master/api/nodes/binary/windows/$arch/worker"
$hashUrl   = "$binaryUrl.sha256"

Write-Host "[vigile] Downloading Worker binary from $binaryUrl..."
New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Invoke-WebRequest -Uri $binaryUrl -OutFile $BinaryPath

Write-Host "[vigile] Verifying SHA256..."
$expectedHash = (Invoke-WebRequest -Uri $hashUrl -UseBasicParsing).Content.Trim().Split()[0]
$actualHash   = (Get-FileHash -Algorithm SHA256 $BinaryPath).Hash.ToLower()

if ($expectedHash -ne $actualHash) {
    Write-Error "ERROR: SHA256 mismatch! Binary may be corrupted."
    Write-Error "  Expected: $expectedHash"
    Write-Error "  Got:      $actualHash"
    exit 1
}
Write-Host "[vigile] SHA256 OK."

New-Item -ItemType Directory -Force -Path $ConfigDir | Out-Null
$Token  | Out-File -Encoding ASCII -NoNewline "$ConfigDir\\enrollment.token"
$Master | Out-File -Encoding ASCII -NoNewline "$ConfigDir\\master_url"

Write-Host "[vigile] Storing enrollment token and configs to $ConfigDir..."

# Install and start Windows Service via sc.exe (Native Windows Services)
Write-Host "[vigile] Installing Windows Service '$ServiceName'..."
# Check if service already exists
$existingService = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
if ($existingService) {
    sc.exe stop $ServiceName 2>$null | Out-Null
    sc.exe delete $ServiceName 2>$null | Out-Null
    Start-Sleep -Seconds 1
}

sc.exe create $ServiceName binPath= "`"$BinaryPath`"" start= auto DisplayName= "Vigile Worker Node"
sc.exe description $ServiceName "Vigile Worker Agent Node for Orchestration."
sc.exe start $ServiceName

Write-Host "[vigile] Service installed and started."
Write-Host "[vigile] Verify status via: Get-Service -Name $ServiceName"
Write-Host "[vigile] Installation complete!"
"""


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.post(
    "/generate-join",
    response_model=JoinTokenResponse,
    summary="Generate an enrollment token and kickstart command (Admin only)",
    status_code=status.HTTP_201_CREATED,
)
async def generate_join_token(
    body: GenerateJoinRequest,
    request: Request,
    db: DB,
    claims: Annotated[dict, Depends(require_role("admin"))],
    sec: SecurityManager = Depends(get_security),
    nm: NodeManager = Depends(get_node_manager),
) -> JoinTokenResponse:
    """
    Generate a JOIN_TOKEN for a new Worker Node.

    Steps:
      1. Pre-create the node entry in PENDING state
      2. Generate HMAC-SHA256 signed JOIN_TOKEN
      3. Store token hash in DB (never store raw token)
      4. Return the curl command for the kickstart script

    The token is single-use and expires in 30 minutes.
    """
    # Demo mode: return mock response
    if is_demo(claims):
        master_url = request.app.state.master_url
        fake_token = f"demo-join-token-{uuid.uuid4()}"
        return JoinTokenResponse(
            node_id="demo-node-99",
            token=fake_token,
            expires_in=1800,
            curl_command=(
                f"curl -sSL {master_url}/api/nodes/kickstart.sh | "
                f"sudo bash -s -- --token {fake_token} --master {master_url}"
            ),
        )

    # Generate node_id (UUID) without persisting. The `nodes` row is created
    # by the Worker enrollment handshake — see master/ws/worker_handler.py.
    # This avoids "phantom" nodes: if the Worker never connects, no row leaks.
    # `group` and `ip_prefix` are forwarded through the JOIN_TOKEN payload and
    # applied to the `nodes` row at enrollment time.
    node_id = nm.generate_node_id()
    pending_name = body.name or ""
    pending_group = body.group or ""

    # 2. Generate JOIN_TOKEN (returns token + payload together)
    # `name` and `group` are carried in the payload so the Worker enrollment
    # can persist them on first INSERT (no `nodes` row exists yet).
    token, payload = sec.generate_join_token(
        node_id=node_id,
        ip_prefix=body.ip_prefix,
        name=pending_name,
        group=pending_group,
    )
    token_hash = sec.join_token_hash(token)

    # 3. Store token in DB. The FK on join_tokens.node_id is dropped (migration
    # 006) so this row can exist before the corresponding `nodes` row.
    token_id = str(uuid.uuid4())
    now = time.time()
    await db.execute(
        """
        INSERT INTO join_tokens (id, node_id, token_hash, payload_b64, consumed, expires_at, created_at)
        VALUES (?, ?, ?, ?, 0, ?, ?)
        """,
        (
            token_id,
            node_id,
            token_hash,
            token.split(".", 1)[1],
            payload["expires_at"],
            now,
        ),
    )
    await db.commit()

    # 4. Audit (no node_id FK — audit log keeps the reference for traceability)
    await log_action(
        db,
        user_id=claims["sub"],
        action=AuditAction.GENERATE_JOIN_TOKEN,
        node_id=node_id,
        details={
            "node_name": pending_name,
            "node_group": pending_group,
            "ip_prefix": body.ip_prefix,
        },
    )

    master_url = request.app.state.master_url
    curl_command = (
        f"curl -sSL {master_url}/api/nodes/kickstart.sh | "
        f"sudo bash -s -- --token {token} --master {master_url}"
    )

    expires_in = int(payload["expires_at"] - now)
    logger.info(
        "JOIN_TOKEN generated: node_id=%s name=%s expires_in=%ds",
        node_id,
        body.name,
        expires_in,
    )

    return JoinTokenResponse(
        node_id=node_id,
        token=token,
        expires_in=expires_in,
        curl_command=curl_command,
    )


@router.get(
    "/kickstart.sh",
    response_class=PlainTextResponse,
    summary="Download the Worker installation script",
    dependencies=[Depends(rate_limiter.dependency(KICKSTART_LIMIT))],
)
async def get_kickstart_script(request: Request) -> PlainTextResponse:
    """
    Return the kickstart shell script.

    This endpoint is public (no auth required) so the curl | sh pipeline works
    without pre-authentication. Security comes from the JOIN_TOKEN validation
    in Phase 2 of the enrollment process.
    """
    # Sanitize: escape $ to prevent bash variable expansion in the generated script
    safe_url = request.app.state.master_url.replace("$", "\\$")
    script = KICKSTART_TEMPLATE.replace("$master_url", safe_url)
    return PlainTextResponse(
        content=script,
        media_type="text/x-sh",
        headers={"Content-Disposition": "inline; filename=kickstart.sh"},
    )


@router.get(
    "/kickstart.ps1",
    response_class=PlainTextResponse,
    summary="Download the Windows Worker installation PowerShell script",
    dependencies=[Depends(rate_limiter.dependency(KICKSTART_LIMIT))],
)
async def get_kickstart_ps1_script(request: Request) -> PlainTextResponse:
    """
    Return the kickstart PowerShell script.

    This endpoint is public (no auth required) so it can be directly downloaded and executed.
    """
    safe_url = request.app.state.master_url.replace("$", "`$")
    script = KICKSTART_PS1_TEMPLATE.replace("$master_url", safe_url)
    return PlainTextResponse(
        content=script,
        media_type="text/plain",
        headers={"Content-Disposition": "inline; filename=kickstart.ps1"},
    )


@router.get(
    "",
    response_model=list[NodeResponse],
    summary="List all nodes (Operator+)",
)
async def list_nodes(
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    state: str | None = Query(default=None, description="Filter by state"),
    limit: int = Query(default=50, ge=1, le=200, description="Max results"),
    offset: int = Query(default=0, ge=0, description="Result offset for pagination"),
    nm: NodeManager = Depends(get_node_manager),
) -> list[NodeResponse]:
    """Return a list of registered nodes, with optional pagination."""
    # Demo mode: return mock data
    if is_demo(claims):
        mock_dicts = [_node_to_response(n) for n in DEMO_NODES]
        mock_enriched = await _add_bulk_node_metrics(db, mock_dicts, claims)
        return [NodeResponse(**nd) for nd in mock_enriched]

    nodes = await nm.list_nodes(db, state=state, limit=limit, offset=offset)
    node_dicts = [_node_to_response(n) for n in nodes]
    enriched = await _add_bulk_node_metrics(db, node_dicts, claims)
    return [NodeResponse(**nd) for nd in enriched]


@router.get(
    "/verify-chain",
    response_model=dict,
    summary="Verify audit chain integrity with optional pagination (Admin only)",
)
async def verify_chain(
    db: DB,
    claims: Annotated[dict, Depends(require_role("admin"))],
    max_entries: int | None = Query(
        default=None, ge=1, le=100000, description="Max entries to verify"
    ),
) -> dict:
    """Verify the audit log hash chain. `max_entries` limits scan for large tables."""
    # Demo mode: return mock data
    if is_demo(claims):
        return {"verified": True, "entries_checked": 5, "corrupted": False, "valid": True}

    from master.core.audit import verify_chain as _verify_chain

    report = await _verify_chain(db, max_entries=max_entries)
    return report


@router.get(
    "/bulk/status",
    response_model=BulkStatusResponse,
    summary="Get bulk status metrics and container counts for all online nodes (Operator+)",
)
async def get_bulk_status(
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    nm: NodeManager = Depends(get_node_manager),
) -> BulkStatusResponse:
    """Get the latest metrics snapshots and container counts for all nodes in bulk."""
    import json

    if is_demo(claims):
        demo_statuses = {}
        for node_id in ["demo-node-01", "demo-node-02", "demo-node-03"]:
            is_online = node_id in ("demo-node-01", "demo-node-02")
            if is_online:
                snaps = get_demo_metrics(node_id, limit=1)
                if snaps:
                    snap = snaps[0]
                    demo_statuses[node_id] = BulkNodeStatus(
                        cpu=snap.get("cpu_percent"),
                        mem=snap.get("mem_percent"),
                        disk=snap.get("disk_percent"),
                        uptime=snap.get("uptime_seconds"),
                        containers_count=4 if node_id == "demo-node-01" else 0,
                    )
            else:
                demo_statuses[node_id] = BulkNodeStatus()
        return BulkStatusResponse(statuses=demo_statuses)

    # Real mode
    # 1. Fetch latest snapshots using window function
    snapshots_map = {}
    async with db.execute("""
        WITH RankedSnapshots AS (
            SELECT
                node_id,
                cpu_percent,
                mem_percent,
                disk_percent,
                uptime_seconds,
                ROW_NUMBER() OVER (PARTITION BY node_id ORDER BY collected_at DESC) as rn
            FROM metrics_snapshots
        )
        SELECT node_id, cpu_percent, mem_percent, disk_percent, uptime_seconds
        FROM RankedSnapshots
        WHERE rn = 1
        """) as cursor:
        for row in await cursor.fetchall():
            snapshots_map[row["node_id"]] = {
                "cpu": row["cpu_percent"],
                "mem": row["mem_percent"],
                "disk": row["disk_percent"],
                "uptime": row["uptime_seconds"],
            }

    # 2. Combine with container count from nodes cached_containers_json
    statuses = {}
    async with db.execute("SELECT id, cached_containers_json FROM nodes") as cursor:
        for row in await cursor.fetchall():
            node_id = row["id"]
            snap = snapshots_map.get(node_id, {})

            containers_count = None
            cached_containers = row["cached_containers_json"]
            if cached_containers:
                try:
                    conts = json.loads(cached_containers)
                    if isinstance(conts, list):
                        containers_count = len(conts)
                except Exception:
                    pass

            statuses[node_id] = BulkNodeStatus(
                cpu=snap.get("cpu"),
                mem=snap.get("mem"),
                disk=snap.get("disk"),
                uptime=snap.get("uptime"),
                containers_count=containers_count,
            )

    return BulkStatusResponse(statuses=statuses)


@router.get(
    "/{node_id}",
    response_model=NodeResponse,
    summary="Get a node's details (Operator+)",
)
async def get_node(
    node_id: Annotated[str, Path(description="Node UUID")],
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    nm: NodeManager = Depends(get_node_manager),
) -> NodeResponse:
    """Fetch detailed information for a single node."""
    # Demo mode: return mock data
    if is_demo(claims):
        node = get_demo_node(node_id)
        if node is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")
        enriched_demo = await _add_node_metrics(db, _node_to_response(node), claims)
        return NodeResponse(**enriched_demo)

    node = await nm.get_node(db, node_id)
    if node is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")
    enriched = await _add_node_metrics(db, _node_to_response(node), claims)
    return NodeResponse(**enriched)


@router.delete(
    "/{node_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Hard-delete a node (Admin only)",
)
async def delete_node(
    node_id: Annotated[str, Path(description="Node UUID")],
    db: DB,
    claims: Annotated[dict, Depends(require_role("admin"))],
    nm: NodeManager = Depends(get_node_manager),
):
    """
    Hard-delete a node from the database.

    This action is permanent — the row is removed and all dependent rows
    (join_tokens, worker_tokens, metrics_snapshots, action_proposals) are
    cascaded away by FK ON DELETE CASCADE. The audit_log keeps a NODE_DELETED
    entry forever (it stores node_id as plain TEXT, no FK). A new enrollment
    is required to re-add the same node.
    """
    # Demo mode: no-op (simulate successful deletion)
    if is_demo(claims):
        return

    deleted = await nm.delete_node(db, node_id, deleted_by=claims["sub"])
    if deleted is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    logger.warning("Node %s hard-deleted by user %s", node_id, claims["sub"])


@router.patch(
    "/{node_id}",
    response_model=NodeResponse,
    summary="Update node metadata or disable flag (Operator+ for metadata, Admin for disable)",
)
async def patch_node(
    node_id: Annotated[str, Path(description="Node UUID")],
    body: NodePatchRequest,
    db: DB,
    claims: CurrentUser,
    nm: NodeManager = Depends(get_node_manager),
) -> NodeResponse:
    """
    Partial update of a node.
      - `name` / `group` : operator+ can change; empty string for `group` clears the value.
      - `disabled`       : admin only; toggles the disable flag and may transition state.
    """
    if is_demo(claims):
        demo_node = get_demo_node(node_id)
        if demo_node is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")
        if body.name is not None:
            demo_node["name"] = body.name
        if body.group is not None:
            demo_node["node_group"] = body.group
        if body.disabled is not None:
            demo_node["disabled"] = bool(body.disabled)
            demo_node["state"] = "DISABLED" if body.disabled else demo_node["state"]
        demo_node["updated_at"] = time.time()
        enriched_demo = await _add_node_metrics(db, _node_to_response(demo_node), claims)
        return NodeResponse(**enriched_demo)

    existing = await nm.get_node(db, node_id)
    if existing is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    user_role = claims.get("role", "viewer")
    has_disabled_field = body.disabled is not None
    has_metadata_field = body.name is not None or body.group is not None

    if has_disabled_field and user_role != "admin":
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Admin role required to enable/disable a node",
        )

    if has_disabled_field:
        await nm.set_disabled(db, node_id, body.disabled, by_user=claims["sub"])  # type: ignore[arg-type]

    if has_metadata_field:
        # Empty string for group means clear; Pydantic keeps it as empty string
        # (None means "field not provided", "" means "clear it").
        group_value = body.group if body.group != "" else None
        await nm.patch_metadata(
            db,
            node_id,
            name=body.name,
            group=group_value,
            by_user=claims["sub"],
        )

    updated = await nm.get_node(db, node_id)
    enriched = await _add_node_metrics(db, _node_to_response(updated), claims)  # type: ignore[arg-type]
    return NodeResponse(**enriched)


@router.post(
    "/{node_id}/configure",
    response_model=NodeResponse,
    summary="Confirm node name+group after enrollment handshake (Operator+)",
)
async def configure_node(
    node_id: Annotated[str, Path(description="Node UUID")],
    body: ConfigureRequest,
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    nm: NodeManager = Depends(get_node_manager),
) -> NodeResponse:
    """
    Operator confirms the Worker's name and group after Ed25519 handshake.
    Transitions UNCONFIGURED -> CONNECTED.
    """
    if is_demo(claims):
        demo_node = get_demo_node(node_id)
        if demo_node is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")
        demo_node["name"] = body.name
        demo_node["node_group"] = body.group or ""
        if demo_node["state"] == "UNCONFIGURED":
            demo_node["state"] = "CONNECTED"
        demo_node["updated_at"] = time.time()
        enriched_demo = await _add_node_metrics(db, _node_to_response(demo_node), claims)
        return NodeResponse(**enriched_demo)

    existing = await nm.get_node(db, node_id)
    if existing is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    if existing["state"] != NodeState.UNCONFIGURED.value:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail=f"Node is not awaiting configuration (state={existing['state']}).",
        )

    try:
        await nm.configure_node(db, node_id, name=body.name, group=body.group)
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_409_CONFLICT, detail=str(exc))

    updated = await nm.get_node(db, node_id)
    enriched = await _add_node_metrics(db, _node_to_response(updated), claims)  # type: ignore[arg-type]
    return NodeResponse(**enriched)


@router.post(
    "/{node_id}/regenerate-token",
    response_model=JoinTokenResponse,
    summary="Invalidate existing JOIN_TOKENs and issue a fresh one (Admin only)",
    status_code=status.HTTP_201_CREATED,
)
async def regenerate_join_token(
    node_id: Annotated[str, Path(description="Node UUID")],
    request: Request,
    db: DB,
    claims: Annotated[dict, Depends(require_role("admin"))],
    sec: SecurityManager = Depends(get_security),
    nm: NodeManager = Depends(get_node_manager),
) -> JoinTokenResponse:
    """
    Issue a new JOIN_TOKEN for an already-pre-created (PENDING) node, invalidating
    any tokens previously issued for it. The node must still be in PENDING state.
    """
    if is_demo(claims):
        master_url = request.app.state.master_url
        fake_token = f"demo-regen-{uuid.uuid4()}"
        return JoinTokenResponse(
            node_id=node_id,
            token=fake_token,
            expires_in=1800,
            curl_command=(
                f"curl -sSL {master_url}/api/nodes/kickstart.sh | "
                f"sudo bash -s -- --token {fake_token} --master {master_url}"
            ),
        )

    existing = await nm.get_node(db, node_id)
    if existing is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    if existing["state"] != NodeState.PENDING.value:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Node already enrolled. Cannot regenerate token.",
        )

    invalidated = await nm.invalidate_join_tokens(db, node_id)
    logger.info("Invalidated %d join tokens for node %s", invalidated, node_id)

    token, payload = sec.generate_join_token(node_id=node_id, ip_prefix="")
    token_hash = sec.join_token_hash(token)

    token_id = str(uuid.uuid4())
    now = time.time()
    await db.execute(
        """
        INSERT INTO join_tokens (id, node_id, token_hash, payload_b64, consumed, expires_at, created_at)
        VALUES (?, ?, ?, ?, 0, ?, ?)
        """,
        (
            token_id,
            node_id,
            token_hash,
            token.split(".", 1)[1],
            payload["expires_at"],
            now,
        ),
    )
    await db.execute(
        "UPDATE nodes SET updated_at = ? WHERE id = ?",
        (now, node_id),
    )
    await db.commit()

    await log_action(
        db,
        user_id=claims["sub"],
        action=AuditAction.REGENERATE_JOIN_TOKEN,
        node_id=node_id,
        details={"invalidated": invalidated},
    )

    master_url = request.app.state.master_url
    curl_command = (
        f"curl -sSL {master_url}/api/nodes/kickstart.sh | "
        f"sudo bash -s -- --token {token} --master {master_url}"
    )
    expires_in = int(payload["expires_at"] - now)
    logger.info("JOIN_TOKEN regenerated: node_id=%s expires_in=%ds", node_id, expires_in)

    return JoinTokenResponse(
        node_id=node_id,
        token=token,
        expires_in=expires_in,
        curl_command=curl_command,
    )


# ---------------------------------------------------------------------------
# Logs response model
# ---------------------------------------------------------------------------


class LogsResponse(BaseModel):
    """Response model for live logs fetched from a Worker."""

    node_id: str
    output: str
    lines: int
    service: str | None = None
    path: str | None = None
    error: str | None = None


# ---------------------------------------------------------------------------
# Stats response models
# ---------------------------------------------------------------------------


class DiskMountResponse(BaseModel):
    mount_point: str
    fs_type: str
    device: str
    total_bytes: int
    used_bytes: int
    percent: float


class MetricsSnapshotResponse(BaseModel):
    """Single metrics snapshot exposed via the stats endpoint."""

    collected_at: float
    cpu_percent: float
    cpu_load_1m: float | None = None
    cpu_load_5m: float | None = None
    cpu_load_15m: float | None = None
    cpu_cores: int | None = None
    mem_total_bytes: int
    mem_used_bytes: int
    mem_percent: float
    swap_total_bytes: int
    swap_used_bytes: int
    disk_total_bytes: int
    disk_used_bytes: int
    disk_percent: float
    disks: list[DiskMountResponse] | None = None
    uptime_seconds: float
    processes: int | None = None


class NodeStatsResponse(BaseModel):
    """Node stats endpoint response."""

    node_id: str
    snapshots: list[MetricsSnapshotResponse]


@router.get(
    "/{node_id}/stats",
    response_model=NodeStatsResponse,
    summary="Get metrics snapshots for a node (Operator+)",
)
async def get_node_stats(
    node_id: Annotated[str, Path(description="Node UUID")],
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    limit: Annotated[int, Query(ge=1, le=100, description="Number of snapshots to return")] = 10,
    nm: NodeManager = Depends(get_node_manager),
) -> NodeStatsResponse:
    """Return the latest metrics snapshots for a node, ordered by time descending."""
    # Demo mode: return mock metrics
    if is_demo(claims):
        demo_node = get_demo_node(node_id)
        if demo_node is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")
        snapshots = get_demo_metrics(node_id, limit)
        return NodeStatsResponse(
            node_id=node_id,
            snapshots=[MetricsSnapshotResponse(**s) for s in snapshots],
        )

    # Verify node exists
    node = await nm.get_node(db, node_id)
    if node is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    import json
    rows: list[dict] = []
    async with db.execute(
        """
        SELECT
            collected_at,
            cpu_percent, cpu_load_1m, cpu_load_5m, cpu_load_15m, cpu_cores,
            mem_total_bytes, mem_used_bytes, mem_percent,
            swap_total_bytes, swap_used_bytes,
            disk_total_bytes, disk_used_bytes, disk_percent,
            uptime_seconds, processes, disks_json
        FROM metrics_snapshots
        WHERE node_id = ?
        ORDER BY collected_at DESC
        LIMIT ?
        """,
        (node_id, limit),
    ) as cursor:
        for row in await cursor.fetchall():
            d = dict(row)
            if d.get("disks_json"):
                try:
                    d["disks"] = json.loads(d["disks_json"])
                except Exception:
                    d["disks"] = None
            rows.append(d)

    return NodeStatsResponse(
        node_id=node_id,
        snapshots=[MetricsSnapshotResponse(**r) for r in rows],
    )


@router.get(
    "/{node_id}/logs",
    response_model=LogsResponse,
    summary="Get live logs from a node (Operator+)",
)
async def get_node_logs(
    node_id: Annotated[str, Path(description="Node UUID")],
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    lines: Annotated[int, Query(ge=1, le=500, description="Number of log lines")] = 50,
    service: Annotated[
        str | None, Query(description="systemd service name (uses journalctl)")
    ] = None,
    path: Annotated[
        str | None, Query(description="Log file path on the worker (/var/log/ only)")
    ] = None,
    nm: NodeManager = Depends(get_node_manager),
) -> LogsResponse:
    """
    Fetch live logs from a Worker via INTENT.

    Supports two modes:
      - **Service logs** (`service` param): uses `journalctl -u <service>` on the Worker
      - **File logs** (`path` param): reads a log file from `/var/log/` on the Worker

    If neither `service` nor `path` is specified, defaults to `/var/log/syslog`.
    """
    # Demo mode: return mock logs
    if is_demo(claims):
        demo_node = get_demo_node(node_id)
        if demo_node is None:
            raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")
        _effective_path = path if path else "/var/log/syslog"
        logs = get_demo_logs(service, _effective_path, lines)
        return LogsResponse(
            node_id=node_id,
            output="\n".join(logs),
            lines=len(logs),
            service=service,
            path=_effective_path if not service else None,
        )

    node = await nm.get_node(db, node_id)
    if node is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    effective_path = path
    if service:
        action = WorkerAction.READ_LOGS_SERVICE
        params = {"service": service, "lines": lines}
    elif effective_path:
        action = WorkerAction.READ_LOGS
        params = {"path": effective_path, "lines": lines}
    else:
        action = WorkerAction.READ_LOGS
        effective_path = "/var/log/syslog"
        params = {"path": effective_path, "lines": lines}

    try:
        result = await nm.send_intent(
            node_id,
            {"action": action, "params": params},
            timeout=15.0,
        )
    except RuntimeError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        )
    except TimeoutError:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="Worker did not respond to log request in time",
        )

    return LogsResponse(
        node_id=node_id,
        output=result.get("output", ""),
        lines=lines,
        service=service,
        path=effective_path if not service else None,
        error=result.get("error") if not result.get("success") else None,
    )


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _node_to_response(node: dict) -> dict:
    """Map DB row dict to the NodeResponse field set."""
    enrolled_at = node.get("enrolled_at")
    enrolled_recently = bool(enrolled_at is not None and (time.time() - float(enrolled_at)) < 86400)
    return {
        "id": node["id"],
        "name": node.get("name", ""),
        "hostname": node.get("hostname"),
        "machine_id": node.get("machine_id"),
        "arch": node.get("arch"),
        "os": node.get("os"),
        "state": node["state"],
        "online": node.get("online", False),
        "last_heartbeat": node.get("last_heartbeat"),
        "enrolled_at": enrolled_at,
        "created_at": node["created_at"],
        "updated_at": node["updated_at"],
        "group": node.get("node_group") or None,
        "disabled": bool(node.get("disabled", 0)),
        "enrolled_recently": enrolled_recently,
        "version": node.get("version"),
    }


async def _add_node_metrics(db: DB, node_dict: dict, claims: dict) -> dict:
    """Fetch and merge the latest metrics snapshot for a node."""
    if is_demo(claims):
        # Return some mock metrics for demo nodes
        if node_dict["id"] == "demo-node-01":
            node_dict.update(
                {
                    "cpu_percent": 12.5,
                    "memory_percent": 45.2,
                    "disk_percent": 38.4,
                    "uptime_seconds": 3600.0,
                }
            )
        elif node_dict["id"] == "demo-node-02":
            node_dict.update(
                {
                    "cpu_percent": 8.0,
                    "memory_percent": 30.1,
                    "disk_percent": 42.0,
                    "uptime_seconds": 1800.0,
                }
            )
        return node_dict

    async with db.execute(
        """
        SELECT cpu_percent, mem_percent, disk_percent, uptime_seconds
        FROM metrics_snapshots
        WHERE node_id = ?
        ORDER BY collected_at DESC
        LIMIT 1
        """,
        (node_dict["id"],),
    ) as cursor:
        snapshot = await cursor.fetchone()
    if snapshot:
        node_dict.update(
            {
                "cpu_percent": snapshot["cpu_percent"],
                "memory_percent": snapshot["mem_percent"],
                "disk_percent": snapshot["disk_percent"],
                "uptime_seconds": snapshot["uptime_seconds"],
            }
        )
    return node_dict


async def _add_bulk_node_metrics(db: DB, node_dicts: list[dict], claims: dict) -> list[dict]:
    """Fetch and merge the latest metrics snapshots for a list of nodes in bulk."""
    if is_demo(claims):
        for nd in node_dicts:
            if nd["id"] == "demo-node-01":
                nd.update(
                    {
                        "cpu_percent": 12.5,
                        "memory_percent": 45.2,
                        "disk_percent": 38.4,
                        "uptime_seconds": 3600.0,
                    }
                )
            elif nd["id"] == "demo-node-02":
                nd.update(
                    {
                        "cpu_percent": 8.0,
                        "memory_percent": 30.1,
                        "disk_percent": 42.0,
                        "uptime_seconds": 1800.0,
                    }
                )
        return node_dicts

    node_ids = [n["id"] for n in node_dicts]
    if not node_ids:
        return node_dicts

    placeholders = ",".join("?" for _ in node_ids)
    snapshots_map = {}
    async with db.execute(
        f"""
        WITH RankedSnapshots AS (
            SELECT
                node_id,
                cpu_percent,
                mem_percent,
                disk_percent,
                uptime_seconds,
                ROW_NUMBER() OVER (PARTITION BY node_id ORDER BY collected_at DESC) as rn
            FROM metrics_snapshots
            WHERE node_id IN ({placeholders})
        )
        SELECT node_id, cpu_percent, mem_percent, disk_percent, uptime_seconds
        FROM RankedSnapshots
        WHERE rn = 1
        """,
        tuple(node_ids),
    ) as cursor:
        for row in await cursor.fetchall():
            snapshots_map[row["node_id"]] = {
                "cpu_percent": row["cpu_percent"],
                "memory_percent": row["mem_percent"],
                "disk_percent": row["disk_percent"],
                "uptime_seconds": row["uptime_seconds"],
            }

    for nd in node_dicts:
        snap = snapshots_map.get(nd["id"])
        if snap:
            nd.update(snap)
    return node_dicts


# ---------------------------------------------------------------------------
# Insights & Profiling Endpoints
# ---------------------------------------------------------------------------


@router.get(
    "/{node_id}/insights",
    summary="Get real-time insights for a node (Operator+)",
)
async def get_node_insights(
    node_id: Annotated[str, Path(description="Node UUID")],
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    im: Insights,
    nm: NodeManager = Depends(get_node_manager),
    locale: str = Depends(get_locale),
) -> dict:
    """Fetch real-time natural language insights for CPU, memory, and disk usage."""
    if is_demo(claims):
        insights = []
        if node_id in ("demo-node-01", "demo-node-99"):
            insights = [
                {
                    "type": "disk",
                    "severity": "warning",
                    "icon": "⚠️",
                    "headline": (
                        "Disk full in 1 week and 3 days"
                        if locale == "en"
                        else "Disque plein dans 1 semaine et 3j"
                    ),
                    "detail": (
                        "+2.4 GB / day growth rate"
                        if locale == "en"
                        else "Taux de croissance de +2.4 Go / jour"
                    ),
                    "raw": {"used_percent": 80.0, "free_gb": 24.0, "growth_gb_per_day": 2.4},
                },
                {
                    "type": "cpu",
                    "severity": "warning",
                    "icon": "🔥",
                    "headline": (
                        "Higher than normal load · Plex Transcoding"
                        if locale == "en"
                        else "Charge supérieure à la normale · Transcodage Plex"
                    ),
                    "detail": (
                        "Sustained load (60%) attributed to Plex container"
                        if locale == "en"
                        else "Charge soutenue (60%) imputée au conteneur Plex"
                    ),
                    "raw": {
                        "cpu_percent": 60.0,
                        "culprit_container": "plex",
                        "culprit_service": None,
                    },
                },
                {
                    "type": "ram",
                    "severity": "ok",
                    "icon": "✅",
                    "headline": "Stable memory" if locale == "en" else "Mémoire stable",
                    "detail": (
                        "No swap pressure" if locale == "en" else "Aucune pression d'échange (swap)"
                    ),
                    "raw": {
                        "used_percent": 65.0,
                        "used_gb": 10.4,
                        "total_gb": 16.0,
                        "swap_used_mb": 0.0,
                    },
                },
            ]
        elif node_id == "demo-node-02":
            insights = [
                {
                    "type": "disk",
                    "severity": "ok",
                    "icon": "✅",
                    "headline": "Stable disk" if locale == "en" else "Disque stable",
                    "detail": (
                        "More than 6 months of space remaining"
                        if locale == "en"
                        else "Plus de 6 mois d'autonomie restants"
                    ),
                    "raw": {"used_percent": 42.0},
                },
                {
                    "type": "cpu",
                    "severity": "ok",
                    "icon": "✅",
                    "headline": "Stable CPU" if locale == "en" else "CPU stable",
                    "detail": "Low usage" if locale == "en" else "Faible utilisation",
                    "raw": {"cpu_percent": 18.7},
                },
                {
                    "type": "ram",
                    "severity": "ok",
                    "icon": "✅",
                    "headline": "Stable memory" if locale == "en" else "Mémoire stable",
                    "detail": (
                        "No swap pressure" if locale == "en" else "Aucune pression d'échange (swap)"
                    ),
                    "raw": {"used_percent": 57.8},
                },
            ]
        else:
            insights = [
                {
                    "type": "disk",
                    "severity": "ok",
                    "icon": "✅",
                    "headline": "Stable disk" if locale == "en" else "Disque stable",
                    "detail": (
                        "More than 6 months of space remaining"
                        if locale == "en"
                        else "Plus de 6 mois d'autonomie restants"
                    ),
                    "raw": {"used_percent": 25.0},
                },
                {
                    "type": "cpu",
                    "severity": "ok",
                    "icon": "✅",
                    "headline": "Stable CPU" if locale == "en" else "CPU stable",
                    "detail": "Low usage" if locale == "en" else "Faible utilisation",
                    "raw": {"cpu_percent": 12.0},
                },
                {
                    "type": "ram",
                    "severity": "ok",
                    "icon": "✅",
                    "headline": "Stable memory" if locale == "en" else "Mémoire stable",
                    "detail": (
                        "No swap pressure" if locale == "en" else "Aucune pression d'échange (swap)"
                    ),
                    "raw": {"used_percent": 30.0},
                },
            ]
        return {
            "node_id": node_id,
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "insights": insights,
            "profile_confidence": "high",
        }

    # Verify node exists
    node = await nm.get_node(db, node_id)
    if node is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    return await im.get_insights(node_id, db, nm, locale=locale)


@router.post(
    "/{node_id}/profile/regenerate",
    response_model=NodeProfile,
    summary="Regenerate node profile manually (Operator+)",
)
async def regenerate_node_profile(
    node_id: Annotated[str, Path(description="Node UUID")],
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    im: Insights,
    nm: NodeManager = Depends(get_node_manager),
    locale: str = Depends(get_locale),
) -> NodeProfile:
    """Manually trigger LLM/heuristic profile regeneration for a node."""
    if is_demo(claims):
        return NodeProfile(
            node_id=node_id,
            known_heavy_processes=[
                HeavyProcessConfig(
                    container_name="plex",
                    cpu_threshold_percent=50.0,
                    label="Plex Transcoding" if locale == "en" else "Transcodage Plex",
                )
            ],
            baseline_ram_percent=70.0,
            context_label="Homelab Server" if locale == "en" else "Serveur homelab",
        )

    # Verify node exists
    node = await nm.get_node(db, node_id)
    if node is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    try:
        profile = await im.generate_profile(node_id, db, nm, force=True, locale=locale)
        return profile
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to generate profile: {e}",
        )


@router.post(
    "/{node_id}/insights/analyze",
    response_model=DiagnosticReport,
    summary="Analyze anomaly using LLM diagnostic (Operator+)",
)
async def analyze_node_anomaly(
    node_id: Annotated[str, Path(description="Node UUID")],
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    im: Insights,
    nm: NodeManager = Depends(get_node_manager),
    locale: str = Depends(get_locale),
) -> DiagnosticReport:
    """Analyze current metrics and services with LLM to produce an anomaly diagnostic report."""
    if is_demo(claims):
        return DiagnosticReport(
            headline=(
                "Plex transcoding task detected"
                if locale == "en"
                else "Tâche de transcodage Plex détectée"
            ),
            explanation=(
                "The Plex container is currently transcoding a 4K H.265 video stream to 1080p H.264 for client 'iPad-de-Flavio'. This operation intensively uses the CPU (60%)."
                if locale == "en"
                else "Le conteneur Plex effectue actuellement le transcodage d'un flux vidéo 4K H.265 vers 1080p H.264 pour le client 'iPad-de-Flavio'. Cette opération sollicite intensément le processeur (60%)."
            ),
            suggested_action=(
                "No action required. If this impacts other services, you can limit Plex CPU or enable hardware acceleration (GPU transcoding)."
                if locale == "en"
                else "Aucune action requise. Si cela impacte d'autres services, vous pouvez limiter le CPU de Plex ou activer l'accélération matérielle (transcodage GPU)."
            ),
        )

    # Verify node exists
    node = await nm.get_node(db, node_id)
    if node is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    try:
        report = await im.analyze_anomaly(node_id, db, nm, locale=locale)
        return report
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Anomaly analysis failed: {e}",
        )


@router.post(
    "/{node_id}/update",
    summary="Trigger worker self-update (Admin only)",
)
async def update_worker(
    node_id: Annotated[str, Path(description="Node UUID")],
    db: DB,
    claims: Annotated[dict, Depends(require_role("admin"))],
    nm: NodeManager = Depends(get_node_manager),
) -> dict:
    """Send an UPDATE_WORKER intent to the worker, causing it to download the latest binary from the Master and restart."""
    if is_demo(claims):
        return {"success": True, "output": "demo worker update simulation complete"}

    node = await nm.get_node(db, node_id)
    if node is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    try:
        result = await nm.send_intent(
            node_id,
            {"action": WorkerAction.UPDATE_WORKER, "params": {}},
            timeout=30.0,
        )
    except RuntimeError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        )
    except TimeoutError:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="Worker did not respond to update request in time",
        )

    if not result.get("success"):
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=result.get("error", "Update failed on worker"),
        )

    # Log action to audit trails
    await log_action(
        db,
        user_id=claims["sub"],
        action="UPDATE_WORKER",
        node_id=node_id,
        details={"result": result},
    )

    return {"success": True, "output": result.get("output", "")}


# ---------------------------------------------------------------------------
# DISK_SCAN endpoint
# ---------------------------------------------------------------------------

_operator_plus = Depends(require_role("operator", "admin"))


@router.get(
    "/{node_id}/disk-scan",
    summary="Scan disk usage on a node (Operator+, force: Admin)",
)
async def get_disk_scan(
    node_id: Annotated[str, Path(description="Node UUID")],
    path: str = Query("/"),
    force: bool = False,
    max_depth: int = Query(4, ge=0, le=20),
    min_size_bytes: int = Query(10 * 1024 * 1024, ge=0),
    claims: Annotated[dict, _operator_plus] = None,
    nm: NodeManager = Depends(get_node_manager),
    db: DB = None,
) -> dict[str, Any]:
    """
    Scan disk usage tree for a node's filesystem.

    Results are cached for 5 minutes per node. Pass ``force=true``
    (admin only) to bypass the cache and trigger a fresh scan.
    """
    if claims is None:
        claims = {}
    if force:
        if claims.get("role") not in ("admin",):
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="force=true requires admin role",
            )

    if not force:
        try:
            cached_json, cached_at = await get_cached_disk_scan(db, node_id)
        except Exception:
            cached_json, cached_at = None, None
        if (
            cached_json
            and cached_at is not None
            and (time.time() - cached_at) < 300
        ):
            try:
                return json.loads(cached_json)
            except Exception:
                pass

    node = await nm.get_node(db, node_id)
    if node is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    mounts = ["/"]
    try:
        stats_result = await nm.send_intent(
            node_id, {"action": "GET_STATS"}, timeout=10.0
        )
        if stats_result.get("success"):
            disks = stats_result.get("disks", [])
            extracted = [d["mount_point"] for d in disks if d.get("mount_point")]
            if extracted:
                mounts = extracted
    except Exception as exc:
        logger.warning("Node %s: GET_STATS failed for disk-scan mounts: %s", node_id, exc)

    try:
        result = await nm.send_intent(
            node_id,
            {
                "action": WorkerAction.DISK_SCAN,
                "params": {
                    "path": path,
                    "max_depth": max_depth,
                    "min_size_bytes": min_size_bytes,
                    "mounts": mounts,
                },
            },
            timeout=45.0,
        )
    except TimeoutError:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="Worker did not respond to disk-scan request in time",
        )
    except RuntimeError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        )

    if not result.get("success"):
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail=result.get("error", "scan failed"),
        )

    try:
        parsed = DiskScanResult.model_validate_json(result["output"])
    except (ValueError, TypeError):
        raise HTTPException(
            status_code=status.HTTP_502_BAD_GATEWAY,
            detail="invalid scan result from worker",
        )

    try:
        await set_cached_disk_scan(db, node_id, result["output"], time.time())
    except Exception as exc:
        logger.warning("Node %s: failed to write disk-scan cache: %s", node_id, exc)

    await log_action(
        db,
        user_id=claims.get("sub", "system"),
        action=AuditAction.DISK_SCAN,
        node_id=node_id,
        details={"path": path, "max_depth": max_depth, "min_size_bytes": min_size_bytes},
    )

    return parsed.model_dump(mode="json")
