"""
YouCloud AI Admin — Nodes API

Endpoints:
  POST   /api/nodes/generate-join            Admin: generate JOIN_TOKEN + curl command
  GET    /api/nodes/kickstart.sh             Public: download the kickstart bash script
  GET    /api/nodes/binary/{os}/{arch}       Public: download Worker binary (Sprint 2)
  GET    /api/nodes                          Operator+: list all nodes
  GET    /api/nodes/{node_id}                Operator+: node details
  GET    /api/nodes/{node_id}/stats          Operator+: latest metrics snapshots
  DELETE /api/nodes/{node_id}                Admin: revoke a node
"""

import logging
import time
import uuid
from typing import Annotated

import aiosqlite
from fastapi import APIRouter, Depends, HTTPException, Path, Query, Request, status
from fastapi.responses import PlainTextResponse
from pydantic import BaseModel, Field

from master.api.deps import CurrentUser, DB, get_security, require_role
from master.core.audit import log_action
from master.core.node_manager import NodeManager, node_manager, NodeState
from master.core.security_manager import SecurityManager

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/nodes", tags=["nodes"])


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------


class GenerateJoinRequest(BaseModel):
    name: str = Field(..., min_length=1, max_length=128, description="Human-readable node label")
    ip_prefix: str = Field(
        default="",
        max_length=64,
        pattern=r"^$|^[\d.]+$",
        description="Optional IP prefix restriction (e.g. '192.168.1.'). Empty = no restriction.",
    )


class JoinTokenResponse(BaseModel):
    node_id: str
    token: str
    expires_in: int  # seconds
    curl_command: str


class NodeResponse(BaseModel):
    id: str
    name: str
    hostname: str | None
    machine_id: str | None
    arch: str | None
    os: str | None
    state: str
    online: bool
    last_heartbeat: float | None
    enrolled_at: float | None
    created_at: float
    updated_at: float


# ---------------------------------------------------------------------------
# Kickstart script template
# ---------------------------------------------------------------------------

KICKSTART_TEMPLATE = """\
#!/usr/bin/env bash
# YouCloud AI Admin — Worker Kickstart Script
# Generated by the Master Node. DO NOT EDIT.
#
# Usage:
#   curl -sSL $master_url/api/nodes/kickstart.sh | sh -s -- --token TOKEN --master MASTER_URL
#
# Requirements: curl, sha256sum (or shasum on macOS), systemd or launchd

set -euo pipefail

# ── Cleanup trap ────────────────────────────────────────────────────────────
TMPDIR_YOUCLOUD="$(mktemp -d /tmp/youcloud_install.XXXXXX)"
cleanup() {
    rm -rf "$TMPDIR_YOUCLOUD"
}
trap cleanup EXIT

# ── Argument parsing ─────────────────────────────────────────────────────────
JOIN_TOKEN=""
MASTER_URL=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --token)   JOIN_TOKEN="$2"; shift 2 ;;
        --master)  MASTER_URL="$2"; shift 2 ;;
        *)         echo "Unknown argument: $1"; exit 1 ;;
    esac
done

if [[ -z "$JOIN_TOKEN" || -z "$MASTER_URL" ]]; then
    echo "ERROR: --token and --master are required." >&2
    exit 1
fi

# ── OS / Arch detection ──────────────────────────────────────────────────────
OS="$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="$(uname -m)"

case "$ARCH" in
    x86_64)         ARCH="amd64" ;;
    aarch64|arm64)  ARCH="arm64" ;;
    armv7l)         ARCH="armv7" ;;
    *)
        echo "ERROR: Unsupported architecture: $ARCH" >&2
        exit 1
        ;;
esac

case "$OS" in
    linux|darwin|freebsd) ;;
    *)
        echo "ERROR: Unsupported OS: $OS" >&2
        exit 1
        ;;
esac

echo "[youcloud] Detected: $OS/$ARCH"

# ── Binary download ───────────────────────────────────────────────────────────
BINARY_URL="$MASTER_URL/api/nodes/binary/$OS/$ARCH/worker"
HASH_URL="$BINARY_URL.sha256"
BINARY_PATH="$TMPDIR_YOUCLOUD/worker"

echo "[youcloud] Downloading Worker binary..."
curl -sSfL "$BINARY_URL" -o "$BINARY_PATH"

echo "[youcloud] Verifying SHA256..."
EXPECTED_HASH="$(curl -sSfL "$HASH_URL")"
if command -v sha256sum &>/dev/null; then
    ACTUAL_HASH="$(sha256sum "$BINARY_PATH" | awk '{print $1}')"
else
    ACTUAL_HASH="$(shasum -a 256 "$BINARY_PATH" | awk '{print $1}')"
fi

if [[ "$EXPECTED_HASH" != "$ACTUAL_HASH" ]]; then
    echo "ERROR: SHA256 mismatch! Binary may be corrupted or tampered." >&2
    echo "  Expected: $EXPECTED_HASH" >&2
    echo "  Got:      $ACTUAL_HASH" >&2
    exit 1
fi

echo "[youcloud] SHA256 OK."
chmod +x "$BINARY_PATH"

# ── Installation ──────────────────────────────────────────────────────────────
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/youcloud"

echo "[youcloud] Installing Worker to $INSTALL_DIR/youcloud-worker..."
install -m 0755 "$BINARY_PATH" "$INSTALL_DIR/youcloud-worker"

mkdir -p "$CONFIG_DIR"
chmod 700 "$CONFIG_DIR"

echo "[youcloud] Storing enrollment token..."
printf '%s' "$JOIN_TOKEN" > "$CONFIG_DIR/enrollment.token"
chmod 600 "$CONFIG_DIR/enrollment.token"

printf '%s' "$MASTER_URL" > "$CONFIG_DIR/master_url"
chmod 600 "$CONFIG_DIR/master_url"

# ── Systemd service installation ──────────────────────────────────────────────
if command -v systemctl &>/dev/null; then
    cat > /etc/systemd/system/youcloud-worker.service <<EOF
[Unit]
Description=YouCloud AI Admin — Worker Node
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=/usr/local/bin/youcloud-worker
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
SyslogIdentifier=youcloud-worker
NoNewPrivileges=true
ProtectSystem=strict
ReadWritePaths=/etc/youcloud
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable --now youcloud-worker
    echo "[youcloud] systemd service enabled and started."

elif command -v launchctl &>/dev/null; then
    # macOS launchd (Sprint 2 — placeholder for now)
    echo "[youcloud] macOS detected. launchd support coming in Sprint 2."
else
    echo "[youcloud] WARNING: No init system detected. Start manually:"
    echo "  youcloud-worker"
fi

echo "[youcloud] Installation complete! The Worker will enroll automatically."
echo "[youcloud] Check status: systemctl status youcloud-worker
"""


# ---------------------------------------------------------------------------
# Endpoints
# ---------------------------------------------------------------------------


@router.post(
    "/generate-join",
    response_model=JoinTokenResponse,
    summary="Generate an enrollment token and kickstart command (Admin only)",
    status_code=status.HTTP_201_CREATED,
)
async def generate_join_token(
    body: GenerateJoinRequest,
    request: Request,
    db: DB,
    claims: Annotated[dict, Depends(require_role("admin"))],
    sec: SecurityManager = Depends(get_security),
    nm: NodeManager = Depends(lambda: node_manager),
) -> JoinTokenResponse:
    """
    Generate a JOIN_TOKEN for a new Worker Node.

    Steps:
      1. Pre-create the node entry in PENDING state
      2. Generate HMAC-SHA256 signed JOIN_TOKEN
      3. Store token hash in DB (never store raw token)
      4. Return the curl command for the kickstart script

    The token is single-use and expires in 30 minutes.
    """
    from master.config import settings

    # 1. Pre-create node
    node_id = await nm.create_node(db, name=body.name, ip_prefix=body.ip_prefix)

    # 2. Generate JOIN_TOKEN (returns token + payload together)
    token, payload = sec.generate_join_token(node_id=node_id, ip_prefix=body.ip_prefix)
    token_hash = sec.join_token_hash(token)

    # 3. Store token in DB
    token_id = str(uuid.uuid4())
    now = time.time()
    await db.execute(
        """
        INSERT INTO join_tokens (id, node_id, token_hash, payload_b64, consumed, expires_at, created_at)
        VALUES (?, ?, ?, ?, 0, ?, ?)
        """,
        (
            token_id,
            node_id,
            token_hash,
            token.split(".", 1)[1],
            payload["expires_at"],
            now,
        ),
    )
    await db.commit()

    # 4. Audit
    await log_action(
        db,
        user_id=claims["sub"],
        action="GENERATE_JOIN_TOKEN",
        node_id=node_id,
        details={"node_name": body.name, "ip_prefix": body.ip_prefix},
    )

    master_url = settings.master_url
    curl_command = (
        f"curl -sSL {master_url}/api/nodes/kickstart.sh | "
        f"sh -s -- --token {token} --master {master_url}"
    )

    expires_in = int(payload["expires_at"] - now)
    logger.info(
        "JOIN_TOKEN generated: node_id=%s name=%s expires_in=%ds",
        node_id, body.name, expires_in,
    )

    return JoinTokenResponse(
        node_id=node_id,
        token=token,
        expires_in=expires_in,
        curl_command=curl_command,
    )


@router.get(
    "/kickstart.sh",
    response_class=PlainTextResponse,
    summary="Download the Worker installation script",
)
async def get_kickstart_script(request: Request) -> PlainTextResponse:
    """
    Return the kickstart shell script.

    This endpoint is public (no auth required) so the curl | sh pipeline works
    without pre-authentication. Security comes from the JOIN_TOKEN validation
    in Phase 2 of the enrollment process.
    """
    from master.config import settings

    # Sanitize: escape $ to prevent bash variable expansion in the generated script
    safe_url = settings.master_url.replace("$", "\\$")
    script = KICKSTART_TEMPLATE.replace("$master_url", safe_url)
    return PlainTextResponse(
        content=script,
        media_type="text/x-sh",
        headers={"Content-Disposition": "inline; filename=kickstart.sh"},
    )


@router.get(
    "",
    response_model=list[NodeResponse],
    summary="List all nodes (Operator+)",
)
async def list_nodes(
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    state: str | None = Query(default=None, description="Filter by state"),
    nm: NodeManager = Depends(lambda: node_manager),
) -> list[NodeResponse]:
    """Return a list of all registered nodes, optionally filtered by state."""
    nodes = await nm.list_nodes(db, state=state)
    return [NodeResponse(**_node_to_response(n)) for n in nodes]


@router.get(
    "/{node_id}",
    response_model=NodeResponse,
    summary="Get a node's details (Operator+)",
)
async def get_node(
    node_id: Annotated[str, Path(description="Node UUID")],
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    nm: NodeManager = Depends(lambda: node_manager),
) -> NodeResponse:
    """Fetch detailed information for a single node."""
    node = await nm.get_node(db, node_id)
    if node is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")
    return NodeResponse(**_node_to_response(node))


@router.delete(
    "/{node_id}",
    status_code=status.HTTP_204_NO_CONTENT,
    summary="Revoke a node (Admin only)",
)
async def revoke_node(
    node_id: Annotated[str, Path(description="Node UUID")],
    db: DB,
    claims: Annotated[dict, Depends(require_role("admin"))],
    nm: NodeManager = Depends(lambda: node_manager),
) -> None:
    """
    Revoke a node: disconnect it, invalidate its tokens, and mark it REVOKED.
    This action is permanent — a new enrollment is required to re-add the node.
    """
    node = await nm.get_node(db, node_id)
    if node is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    if node["state"] == NodeState.REVOKED.value:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Node is already revoked",
        )

    await nm.revoke_node(db, node_id, revoked_by=claims["sub"])

    await log_action(
        db,
        user_id=claims["sub"],
        action="REVOKE_NODE",
        node_id=node_id,
        details={"node_name": node.get("name"), "previous_state": node["state"]},
    )

    logger.warning("Node %s revoked by user %s", node_id, claims["sub"])


# ---------------------------------------------------------------------------
# Logs response model
# ---------------------------------------------------------------------------


class LogsResponse(BaseModel):
    """Response model for live logs fetched from a Worker."""
    node_id: str
    output: str
    lines: int
    service: str | None = None
    path: str | None = None
    error: str | None = None


# ---------------------------------------------------------------------------
# Stats response models
# ---------------------------------------------------------------------------


class MetricsSnapshotResponse(BaseModel):
    """Single metrics snapshot exposed via the stats endpoint."""
    collected_at: float
    cpu_percent: float
    cpu_load_1m: float | None = None
    cpu_load_5m: float | None = None
    cpu_load_15m: float | None = None
    cpu_cores: int | None = None
    mem_total_bytes: int
    mem_used_bytes: int
    mem_percent: float
    swap_total_bytes: int
    swap_used_bytes: int
    disk_total_bytes: int
    disk_used_bytes: int
    disk_percent: float
    uptime_seconds: float
    processes: int | None = None


class NodeStatsResponse(BaseModel):
    """Node stats endpoint response."""
    node_id: str
    snapshots: list[MetricsSnapshotResponse]


@router.get(
    "/{node_id}/stats",
    response_model=NodeStatsResponse,
    summary="Get metrics snapshots for a node (Operator+)",
)
async def get_node_stats(
    node_id: Annotated[str, Path(description="Node UUID")],
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    limit: Annotated[int, Query(ge=1, le=100, description="Number of snapshots to return")] = 10,
    nm: NodeManager = Depends(lambda: node_manager),
) -> NodeStatsResponse:
    """Return the latest metrics snapshots for a node, ordered by time descending."""
    # Verify node exists
    node = await nm.get_node(db, node_id)
    if node is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    rows: list[dict] = []
    async with db.execute(
        """
        SELECT
            collected_at,
            cpu_percent, cpu_load_1m, cpu_load_5m, cpu_load_15m, cpu_cores,
            mem_total_bytes, mem_used_bytes, mem_percent,
            swap_total_bytes, swap_used_bytes,
            disk_total_bytes, disk_used_bytes, disk_percent,
            uptime_seconds, processes
        FROM metrics_snapshots
        WHERE node_id = ?
        ORDER BY collected_at DESC
        LIMIT ?
        """,
        (node_id, limit),
    ) as cursor:
        for row in await cursor.fetchall():
            rows.append(dict(row))

    return NodeStatsResponse(
        node_id=node_id,
        snapshots=[MetricsSnapshotResponse(**r) for r in rows],
    )


@router.get(
    "/{node_id}/logs",
    response_model=LogsResponse,
    summary="Get live logs from a node (Operator+)",
)
async def get_node_logs(
    node_id: Annotated[str, Path(description="Node UUID")],
    db: DB,
    claims: Annotated[dict, Depends(require_role("operator", "admin"))],
    lines: Annotated[int, Query(ge=1, le=500, description="Number of log lines")] = 50,
    service: Annotated[str | None, Query(description="systemd service name (uses journalctl)")] = None,
    path: Annotated[str | None, Query(description="Log file path on the worker (/var/log/ only)")] = None,
    nm: NodeManager = Depends(lambda: node_manager),
) -> LogsResponse:
    """
    Fetch live logs from a Worker via INTENT.

    Supports two modes:
      - **Service logs** (`service` param): uses `journalctl -u <service>` on the Worker
      - **File logs** (`path` param): reads a log file from `/var/log/` on the Worker

    If neither `service` nor `path` is specified, defaults to `/var/log/syslog`.
    """
    node = await nm.get_node(db, node_id)
    if node is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Node not found")

    if service:
        action = "READ_LOGS_SERVICE"
        params = {"service": service, "lines": lines}
    elif path:
        action = "READ_LOGS"
        params = {"path": path, "lines": lines}
    else:
        action = "READ_LOGS"
        params = {"path": "/var/log/syslog", "lines": lines}

    try:
        result = await nm.send_intent(
            node_id,
            {"action": action, "params": params},
            timeout=15.0,
        )
    except RuntimeError as exc:
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail=str(exc),
        )
    except TimeoutError:
        raise HTTPException(
            status_code=status.HTTP_504_GATEWAY_TIMEOUT,
            detail="Worker did not respond to log request in time",
        )

    return LogsResponse(
        node_id=node_id,
        output=result.get("output", ""),
        lines=lines,
        service=service,
        path=path,
        error=result.get("error") if not result.get("success") else None,
    )


# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------


def _node_to_response(node: dict) -> dict:
    """Map DB row dict to the NodeResponse field set."""
    return {
        "id": node["id"],
        "name": node.get("name", ""),
        "hostname": node.get("hostname"),
        "machine_id": node.get("machine_id"),
        "arch": node.get("arch"),
        "os": node.get("os"),
        "state": node["state"],
        "online": node.get("online", False),
        "last_heartbeat": node.get("last_heartbeat"),
        "enrolled_at": node.get("enrolled_at"),
        "created_at": node["created_at"],
        "updated_at": node["updated_at"],
    }
