"""
Vigile — SQL Schema Definitions
All table DDL in one place. No ORM — pure aiosqlite SQL.

Tables:
  - nodes               : registered worker nodes
  - join_tokens         : single-use enrollment tokens (HMAC-SHA256)
  - worker_tokens       : operational JWT tokens with rotation lifecycle
  - users               : human operators with RBAC roles
  - audit_log           : append-only action log with chained SHA256 hashes
  - metrics_snapshots   : periodic status reports from Workers
  - action_proposals    : Human-in-the-Loop action lifecycle
  - automation_rules    : Trigger→Condition→Action automation rules
  - automation_logs     : Execution history for automation rules
  - alerts              : Engine-evaluated alert lifecycle (firing → resolved)
"""

# ---------------------------------------------------------------------------
# nodes
# ---------------------------------------------------------------------------
CREATE_NODES = """
CREATE TABLE IF NOT EXISTS nodes (
    id                           TEXT PRIMARY KEY,           -- UUID generated by Master at token creation
    name                         TEXT NOT NULL,              -- Human-readable label given by Admin
    hostname                     TEXT,                       -- Reported by Worker during enrollment
    machine_id                   TEXT,                       -- sha256(/etc/machine-id), set at enrollment
    arch                         TEXT,                       -- e.g. x86_64, aarch64
    os                           TEXT,                       -- e.g. linux, darwin
    public_key                   TEXT,                       -- Ed25519 public key (base64), set at enrollment
    state                        TEXT NOT NULL DEFAULT 'PENDING',
                                                             -- PENDING | ENROLLING | CONNECTED |
                                                             -- RECONNECTING | LOST | STALE | REVOKED
    ip_prefix                    TEXT,                       -- IP prefix restriction from join token
    last_heartbeat               REAL,                       -- Unix timestamp (float)
    enrolled_at                  REAL,                       -- Unix timestamp
    created_at                   REAL NOT NULL,              -- Unix timestamp
    updated_at                   REAL NOT NULL,              -- Unix timestamp
    insight_profile              TEXT,                       -- Profile JSON for smart insights
    insight_profile_generated_at REAL,                       -- Timestamp when profile was generated
    cached_services_json         TEXT,                       -- Cached services JSON from background task
    cached_containers_json       TEXT,                       -- Cached containers JSON from background task
    version                      TEXT                        -- Worker binary version reported by Worker
)
"""

# ---------------------------------------------------------------------------
# join_tokens  (single-use, 30-min TTL)
# ---------------------------------------------------------------------------
# No FK to nodes.id: the `nodes` row is created by the Worker enrollment
# handshake, AFTER the join_token row exists (see migration 006 + master/ws/
# worker_handler.py). Orphaned join_tokens are cleaned by JOIN_TOKEN_TTL expiry.
CREATE_JOIN_TOKENS = """
CREATE TABLE IF NOT EXISTS join_tokens (
    id          TEXT PRIMARY KEY,     -- UUID
    node_id     TEXT NOT NULL,        -- UUID of the (not-yet-existing) target node
    token_hash  TEXT NOT NULL UNIQUE, -- sha256 of the raw token (never store raw token)
    payload_b64 TEXT NOT NULL,        -- The base64url payload embedded in the token
    consumed    INTEGER NOT NULL DEFAULT 0,  -- 0=available, 1=consumed
    expires_at  REAL NOT NULL,        -- Unix timestamp
    created_at  REAL NOT NULL
)
"""

# ---------------------------------------------------------------------------
# worker_tokens  (operational JWT, 30-day TTL, 7-day soft rotation)
# ---------------------------------------------------------------------------
CREATE_WORKER_TOKENS = """
CREATE TABLE IF NOT EXISTS worker_tokens (
    id            TEXT PRIMARY KEY,
    node_id       TEXT NOT NULL,
    token_hash    TEXT NOT NULL UNIQUE,   -- sha256 of the raw JWT
    issued_at     REAL NOT NULL,
    rotation_due  REAL NOT NULL,          -- soft: Master pushes new token at next connect
    expires_at    REAL NOT NULL,          -- hard: connection refused after this
    revoked       INTEGER NOT NULL DEFAULT 0,
    revoked_at    REAL,
    revoked_by    TEXT,                   -- user_id who revoked
    FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
)
"""

# ---------------------------------------------------------------------------
# users  (human operators — RBAC)
# ---------------------------------------------------------------------------
CREATE_USERS = """
CREATE TABLE IF NOT EXISTS users (
    id                   TEXT PRIMARY KEY,       -- UUID
    username             TEXT NOT NULL UNIQUE,
    password_hash        TEXT NOT NULL,          -- bcrypt hash via passlib
    role                 TEXT NOT NULL DEFAULT 'viewer',
                                                 -- viewer | operator | admin
    is_active            INTEGER NOT NULL DEFAULT 1,
    must_change_password INTEGER NOT NULL DEFAULT 0,
    created_at           REAL NOT NULL,
    updated_at           REAL NOT NULL,
    last_login           REAL                    -- Unix timestamp, nullable
)
"""

# ---------------------------------------------------------------------------
# refresh_tokens (invalidation & theft detection)
# ---------------------------------------------------------------------------
CREATE_REFRESH_TOKENS = """
CREATE TABLE IF NOT EXISTS refresh_tokens (
    id          TEXT PRIMARY KEY,        -- UUID
    user_id     TEXT NOT NULL,           -- FK users.id
    token_hash  TEXT NOT NULL UNIQUE,    -- SHA256 of raw token
    family_id   TEXT NOT NULL,           -- Token family (for rotation/theft detection)
    issued_at   REAL NOT NULL,
    expires_at  REAL NOT NULL,
    revoked     INTEGER NOT NULL DEFAULT 0,
    revoked_at  REAL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
)
"""

# ---------------------------------------------------------------------------
# audit_log  (append-only, chained SHA256 hashes)
# ---------------------------------------------------------------------------
CREATE_AUDIT_LOG = """
CREATE TABLE IF NOT EXISTS audit_log (
    id            TEXT PRIMARY KEY,       -- UUID
    sequence      INTEGER NOT NULL UNIQUE, -- monotonic sequence for chain ordering
    timestamp     REAL NOT NULL,          -- Unix timestamp (float, microsecond precision)
    user_id       TEXT NOT NULL,          -- who initiated (user UUID or 'system')
    action        TEXT NOT NULL,          -- e.g. APPROVE_INTENT, ENROLL_NODE, REVOKE_NODE
    node_id       TEXT,                   -- may be NULL for non-node actions
    details_json  TEXT NOT NULL DEFAULT '{}',  -- JSON blob with action-specific context
    previous_hash TEXT NOT NULL,          -- entry_hash of record N-1 (or '0' for genesis)
    entry_hash    TEXT NOT NULL UNIQUE    -- sha256(previous_hash+sequence+timestamp+action+...)
)
"""

# ---------------------------------------------------------------------------
# metrics_snapshots  (periodic status reports from Workers)
# ---------------------------------------------------------------------------
CREATE_METRICS_SNAPSHOTS = """
CREATE TABLE IF NOT EXISTS metrics_snapshots (
    id               TEXT PRIMARY KEY,           -- UUID
    node_id          TEXT NOT NULL,              -- References nodes.id
    collected_at     REAL NOT NULL,              -- Unix timestamp from the Worker
    created_at       REAL NOT NULL,              -- When this DB row was inserted

    -- CPU
    cpu_percent      REAL NOT NULL DEFAULT 0,
    cpu_load_1m      REAL,
    cpu_load_5m      REAL,
    cpu_load_15m     REAL,
    cpu_cores        INTEGER,

    -- Memory
    mem_total_bytes  INTEGER NOT NULL DEFAULT 0,
    mem_used_bytes   INTEGER NOT NULL DEFAULT 0,
    mem_percent      REAL NOT NULL DEFAULT 0,

    -- Swap
    swap_total_bytes INTEGER NOT NULL DEFAULT 0,
    swap_used_bytes  INTEGER NOT NULL DEFAULT 0,

    -- Disk (root partition)
    disk_total_bytes INTEGER NOT NULL DEFAULT 0,
    disk_used_bytes  INTEGER NOT NULL DEFAULT 0,
    disk_percent     REAL NOT NULL DEFAULT 0,

    -- System
    uptime_seconds   REAL NOT NULL DEFAULT 0,
    processes        INTEGER,

    -- Network I/O
    net_bytes_recv      INTEGER,
    net_bytes_sent      INTEGER,
    net_packets_recv    INTEGER,
    net_packets_sent    INTEGER,
    net_errors_in       INTEGER,
    net_errors_out      INTEGER,
    net_drops_in        INTEGER,
    net_drops_out       INTEGER,

    -- Disk I/O
    disk_reads          INTEGER,
    disk_writes         INTEGER,
    disk_read_bytes     INTEGER,
    disk_write_bytes    INTEGER,

    -- Temperature
    temp_celsius        REAL,

    -- PSI
    psi_cpu_avg10       REAL,
    psi_mem_avg10       REAL,
    psi_io_avg10        REAL,

    -- File handles
    file_handles_used   INTEGER,
    file_handles_max    INTEGER,

    -- Entropy
    entropy_avail       INTEGER,

    -- Context switches
    context_switches    INTEGER,

    -- CPU throttling
    cpu_throttled_count INTEGER,

    FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
)
"""

# ---------------------------------------------------------------------------
# action_proposals  (Human-in-the-Loop action lifecycle)
# ---------------------------------------------------------------------------
CREATE_PROPOSALS = """
CREATE TABLE IF NOT EXISTS action_proposals (
    id                TEXT PRIMARY KEY,
    node_id           TEXT NOT NULL,
    action            TEXT NOT NULL,
    params_json       TEXT NOT NULL DEFAULT '{}',
    reasoning         TEXT NOT NULL,
    risk_level        TEXT NOT NULL DEFAULT 'MEDIUM',
    status            TEXT NOT NULL DEFAULT 'PENDING'
                      CHECK(status IN ('PENDING','APPROVED','EXECUTED','FAILED','REJECTED')),
    created_by        TEXT NOT NULL,
    approved_by       TEXT,
    rejected_by       TEXT,
    rejection_reason  TEXT,
    created_at        REAL NOT NULL,
    updated_at        REAL NOT NULL,
    executed_at       REAL,
    result_json       TEXT,
    FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
)
"""

# ---------------------------------------------------------------------------
# chat_sessions  (Persisted Copilot conversations)
# ---------------------------------------------------------------------------
CREATE_CHAT_SESSIONS = """
CREATE TABLE IF NOT EXISTS chat_sessions (
    id            TEXT PRIMARY KEY,
    user_id       TEXT NOT NULL,
    node_id       TEXT,
    title         TEXT NOT NULL,
    history_json  TEXT NOT NULL DEFAULT '[]',
    created_at    REAL NOT NULL,
    updated_at    REAL NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE SET NULL
)
"""

# ---------------------------------------------------------------------------
# plugin_configs  (Plugin configurations and states)
# ---------------------------------------------------------------------------
CREATE_PLUGIN_CONFIGS = """
CREATE TABLE IF NOT EXISTS plugin_configs (
    plugin_id   TEXT PRIMARY KEY,
    enabled     INTEGER NOT NULL DEFAULT 1,
    config_json TEXT NOT NULL DEFAULT '{}'
)
"""

# ---------------------------------------------------------------------------
# plugins  (Plugin registry with version, status, and manifest metadata)
# ---------------------------------------------------------------------------
CREATE_PLUGINS = """
CREATE TABLE IF NOT EXISTS plugins (
    id             TEXT PRIMARY KEY,
    version        TEXT NOT NULL DEFAULT '0.0.0',
    enabled        INTEGER NOT NULL DEFAULT 1,
    status         TEXT NOT NULL DEFAULT 'INSTALLED',
    config_json    TEXT NOT NULL DEFAULT '{}',
    manifest_hash  TEXT,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)
"""

# ---------------------------------------------------------------------------
# automation_rules  (Trigger → Condition → Action automation engine)
# ---------------------------------------------------------------------------
CREATE_AUTOMATION_RULES = """
CREATE TABLE IF NOT EXISTS automation_rules (
    id                   TEXT PRIMARY KEY,          -- UUID
    name                 TEXT NOT NULL,             -- Human-readable label
    description          TEXT NOT NULL DEFAULT '',  -- Optional description
    enabled              INTEGER NOT NULL DEFAULT 1,
    trigger_type         TEXT NOT NULL,             -- metric_threshold | node_state
    trigger_config_json  TEXT NOT NULL DEFAULT '{}',-- Trigger params (metric, operator, threshold, state)
    conditions_json      TEXT NOT NULL DEFAULT '[]',-- List of condition dicts [{type, ...}]
    actions_json         TEXT NOT NULL DEFAULT '[]',-- List of action dicts [{type, ...}]
    target_node_id       TEXT,                      -- Scope: specific node (NULL = all nodes)
    target_group         TEXT,                      -- Scope: node group (NULL = all groups)
    cooldown_seconds     INTEGER NOT NULL DEFAULT 300, -- Anti-spam: min seconds between triggers
    trust_level          TEXT NOT NULL DEFAULT 'auto' -- auto | always_approve | manual
                        CHECK(trust_level IN ('auto','always_approve','manual')),
    created_by           TEXT NOT NULL,             -- user_id of the creator
    created_at           REAL NOT NULL,
    updated_at           REAL NOT NULL,
    FOREIGN KEY (target_node_id) REFERENCES nodes(id) ON DELETE SET NULL
)
"""

# ---------------------------------------------------------------------------
# automation_logs  (Execution history for automation rules)
# ---------------------------------------------------------------------------
CREATE_AUTOMATION_LOGS = """
CREATE TABLE IF NOT EXISTS automation_logs (
    id               TEXT PRIMARY KEY,  -- UUID
    rule_id          TEXT NOT NULL,     -- FK → automation_rules.id
    node_id          TEXT,              -- Target node at time of trigger (nullable)
    triggered_at     REAL NOT NULL,     -- Unix timestamp
    status           TEXT NOT NULL DEFAULT 'TRIGGERED'
                     CHECK(status IN ('SUCCESS','FAILED','SKIPPED','COOLDOWN')),
    trigger_data_json TEXT NOT NULL DEFAULT '{}', -- Snapshot of the data that triggered the rule
    result_json      TEXT NOT NULL DEFAULT '{}',  -- Results of each action execution
    FOREIGN KEY (rule_id) REFERENCES automation_rules(id) ON DELETE CASCADE,
    FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE SET NULL
)
"""

# ---------------------------------------------------------------------------
# alerts  (Engine-evaluated alert lifecycle — firing → resolved)
# ---------------------------------------------------------------------------
CREATE_ALERTS = """
CREATE TABLE IF NOT EXISTS alerts (
    id            TEXT PRIMARY KEY,           -- UUID
    node_id       TEXT NOT NULL,              -- FK → nodes.id
    alert_name    TEXT NOT NULL,              -- ex: "disk_usage_high", "node_state_lost"
    severity      TEXT NOT NULL DEFAULT 'warning',  -- info | warning | critical
    status        TEXT NOT NULL DEFAULT 'firing'
                  CHECK(status IN ('firing', 'resolved')),
    message       TEXT NOT NULL DEFAULT '',
    metric_value  REAL,                      -- Valeur au moment du déclenchement
    threshold     REAL,                      -- Seuil qui a déclenché
    details_json  TEXT NOT NULL DEFAULT '{}', -- Contexte additionnel (JSON)
    created_at    REAL NOT NULL,             -- Premier déclenchement
    resolved_at   REAL,                      -- Timestamp de résolution
    updated_at    REAL NOT NULL,             -- Dernière mise à jour
    FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
)
"""

# ---------------------------------------------------------------------------
# investigations  (Alert-triggered diagnosis records — Sprint 9)
# ---------------------------------------------------------------------------
CREATE_INVESTIGATIONS = """
CREATE TABLE IF NOT EXISTS investigations (
    id                TEXT PRIMARY KEY,           -- UUID
    alert_id          TEXT,                       -- FK → alerts.id (nullable for manual)
    node_id           TEXT NOT NULL,              -- FK → nodes.id
    alert_name        TEXT NOT NULL,              -- ex: "disk_usage_high"
    severity          TEXT NOT NULL DEFAULT 'warning',
    status            TEXT NOT NULL DEFAULT 'queued'
                      CHECK(status IN ('queued', 'in_progress', 'completed', 'failed')),
    context_json      TEXT NOT NULL DEFAULT '{}', -- Snapshot context at time of fire
    result            TEXT,                       -- Phase 3 LLM diagnostic result (JSON)
    created_at        REAL NOT NULL,
    completed_at      REAL,
    updated_at        REAL NOT NULL,
    FOREIGN KEY (alert_id) REFERENCES alerts(id) ON DELETE SET NULL,
    FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
)
"""

# ---------------------------------------------------------------------------
# Indexes for common query patterns
# ---------------------------------------------------------------------------
CREATE_INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_join_tokens_node_id ON join_tokens(node_id)",
    "CREATE INDEX IF NOT EXISTS idx_join_tokens_consumed ON join_tokens(consumed, expires_at)",
    "CREATE INDEX IF NOT EXISTS idx_worker_tokens_node_id ON worker_tokens(node_id)",
    "CREATE INDEX IF NOT EXISTS idx_worker_tokens_hash ON worker_tokens(token_hash)",
    "CREATE INDEX IF NOT EXISTS idx_nodes_state ON nodes(state)",
    "CREATE INDEX IF NOT EXISTS idx_audit_log_sequence ON audit_log(sequence)",
    "CREATE INDEX IF NOT EXISTS idx_audit_log_node_id ON audit_log(node_id)",
    "CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_metrics_snapshots_node_time ON metrics_snapshots(node_id, collected_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_proposals_status ON action_proposals(status)",
    "CREATE INDEX IF NOT EXISTS idx_proposals_node ON action_proposals(node_id)",
    "CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user ON refresh_tokens(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_refresh_tokens_family ON refresh_tokens(family_id)",
    "CREATE INDEX IF NOT EXISTS idx_chat_sessions_user ON chat_sessions(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_chat_sessions_node ON chat_sessions(node_id)",
    "CREATE INDEX IF NOT EXISTS idx_plugin_configs_enabled ON plugin_configs(enabled)",
    "CREATE INDEX IF NOT EXISTS idx_plugins_enabled ON plugins(enabled)",
    "CREATE INDEX IF NOT EXISTS idx_plugins_status ON plugins(status)",
    "CREATE INDEX IF NOT EXISTS idx_automation_rules_enabled ON automation_rules(enabled)",
    "CREATE INDEX IF NOT EXISTS idx_automation_rules_trigger ON automation_rules(trigger_type)",
    "CREATE INDEX IF NOT EXISTS idx_automation_logs_rule ON automation_logs(rule_id, triggered_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_automation_logs_node ON automation_logs(node_id)",
    "CREATE INDEX IF NOT EXISTS idx_alerts_node_status ON alerts(node_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_alerts_name_status ON alerts(alert_name, node_id, status)",
    "CREATE INDEX IF NOT EXISTS idx_alerts_created ON alerts(created_at)",
    "CREATE INDEX IF NOT EXISTS idx_alerts_severity ON alerts(severity, status)",
    "CREATE INDEX IF NOT EXISTS idx_investigations_node ON investigations(node_id, created_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_investigations_status ON investigations(status)",
    "CREATE INDEX IF NOT EXISTS idx_investigations_alert ON investigations(alert_id)",
]

# All CREATE statements in dependency order
ALL_TABLES = [
    CREATE_NODES,
    CREATE_JOIN_TOKENS,
    CREATE_WORKER_TOKENS,
    CREATE_USERS,
    CREATE_REFRESH_TOKENS,
    CREATE_AUDIT_LOG,
    CREATE_METRICS_SNAPSHOTS,
    CREATE_PROPOSALS,
    CREATE_CHAT_SESSIONS,
    CREATE_PLUGIN_CONFIGS,
    CREATE_PLUGINS,
    CREATE_AUTOMATION_RULES,
    CREATE_AUTOMATION_LOGS,
    CREATE_ALERTS,
    CREATE_INVESTIGATIONS,
]
