"""
Vigile — SQL Schema Definitions
All table DDL in one place. No ORM — pure aiosqlite SQL.

Tables:
  - nodes             : registered worker nodes
  - join_tokens       : single-use enrollment tokens (HMAC-SHA256)
  - worker_tokens     : operational JWT tokens with rotation lifecycle
  - users             : human operators with RBAC roles
  - audit_log         : append-only action log with chained SHA256 hashes
  - metrics_snapshots : periodic status reports from Workers
  - action_proposals  : Human-in-the-Loop action lifecycle
"""

# ---------------------------------------------------------------------------
# nodes
# ---------------------------------------------------------------------------
CREATE_NODES = """
CREATE TABLE IF NOT EXISTS nodes (
    id               TEXT PRIMARY KEY,           -- UUID generated by Master at token creation
    name             TEXT NOT NULL,              -- Human-readable label given by Admin
    hostname         TEXT,                       -- Reported by Worker during enrollment
    machine_id       TEXT,                       -- sha256(/etc/machine-id), set at enrollment
    arch             TEXT,                       -- e.g. x86_64, aarch64
    os               TEXT,                       -- e.g. linux, darwin
    public_key       TEXT,                       -- Ed25519 public key (base64), set at enrollment
    state            TEXT NOT NULL DEFAULT 'PENDING',
                                                 -- PENDING | ENROLLING | CONNECTED |
                                                 -- RECONNECTING | LOST | STALE | REVOKED
    ip_prefix        TEXT,                       -- IP prefix restriction from join token
    last_heartbeat   REAL,                       -- Unix timestamp (float)
    enrolled_at      REAL,                       -- Unix timestamp
    created_at       REAL NOT NULL,              -- Unix timestamp
    updated_at       REAL NOT NULL               -- Unix timestamp
)
"""

# ---------------------------------------------------------------------------
# join_tokens  (single-use, 30-min TTL)
# ---------------------------------------------------------------------------
CREATE_JOIN_TOKENS = """
CREATE TABLE IF NOT EXISTS join_tokens (
    id          TEXT PRIMARY KEY,     -- UUID
    node_id     TEXT NOT NULL,        -- References nodes.id (node pre-created in PENDING state)
    token_hash  TEXT NOT NULL UNIQUE, -- sha256 of the raw token (never store raw token)
    payload_b64 TEXT NOT NULL,        -- The base64url payload embedded in the token
    consumed    INTEGER NOT NULL DEFAULT 0,  -- 0=available, 1=consumed
    expires_at  REAL NOT NULL,        -- Unix timestamp
    created_at  REAL NOT NULL,
    FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
)
"""

# ---------------------------------------------------------------------------
# worker_tokens  (operational JWT, 30-day TTL, 7-day soft rotation)
# ---------------------------------------------------------------------------
CREATE_WORKER_TOKENS = """
CREATE TABLE IF NOT EXISTS worker_tokens (
    id            TEXT PRIMARY KEY,
    node_id       TEXT NOT NULL,
    token_hash    TEXT NOT NULL UNIQUE,   -- sha256 of the raw JWT
    issued_at     REAL NOT NULL,
    rotation_due  REAL NOT NULL,          -- soft: Master pushes new token at next connect
    expires_at    REAL NOT NULL,          -- hard: connection refused after this
    revoked       INTEGER NOT NULL DEFAULT 0,
    revoked_at    REAL,
    revoked_by    TEXT,                   -- user_id who revoked
    FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
)
"""

# ---------------------------------------------------------------------------
# users  (human operators — RBAC)
# ---------------------------------------------------------------------------
CREATE_USERS = """
CREATE TABLE IF NOT EXISTS users (
    id            TEXT PRIMARY KEY,       -- UUID
    username      TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,          -- bcrypt hash via passlib
    role          TEXT NOT NULL DEFAULT 'viewer',
                                          -- viewer | operator | admin
    is_active     INTEGER NOT NULL DEFAULT 1,
    created_at    REAL NOT NULL,
    updated_at    REAL NOT NULL,
    last_login    REAL                    -- Unix timestamp, nullable
)
"""

# ---------------------------------------------------------------------------
# audit_log  (append-only, chained SHA256 hashes)
# ---------------------------------------------------------------------------
CREATE_AUDIT_LOG = """
CREATE TABLE IF NOT EXISTS audit_log (
    id            TEXT PRIMARY KEY,       -- UUID
    sequence      INTEGER NOT NULL UNIQUE, -- monotonic sequence for chain ordering
    timestamp     REAL NOT NULL,          -- Unix timestamp (float, microsecond precision)
    user_id       TEXT NOT NULL,          -- who initiated (user UUID or 'system')
    action        TEXT NOT NULL,          -- e.g. APPROVE_INTENT, ENROLL_NODE, REVOKE_NODE
    node_id       TEXT,                   -- may be NULL for non-node actions
    details_json  TEXT NOT NULL DEFAULT '{}',  -- JSON blob with action-specific context
    previous_hash TEXT NOT NULL,          -- entry_hash of record N-1 (or '0' for genesis)
    entry_hash    TEXT NOT NULL UNIQUE    -- sha256(previous_hash+sequence+timestamp+action+...)
)
"""

# ---------------------------------------------------------------------------
# metrics_snapshots  (periodic status reports from Workers)
# ---------------------------------------------------------------------------
CREATE_METRICS_SNAPSHOTS = """
CREATE TABLE IF NOT EXISTS metrics_snapshots (
    id               TEXT PRIMARY KEY,           -- UUID
    node_id          TEXT NOT NULL,              -- References nodes.id
    collected_at     REAL NOT NULL,              -- Unix timestamp from the Worker
    created_at       REAL NOT NULL,              -- When this DB row was inserted

    -- CPU
    cpu_percent      REAL NOT NULL DEFAULT 0,
    cpu_load_1m      REAL,
    cpu_load_5m      REAL,
    cpu_load_15m     REAL,
    cpu_cores        INTEGER,

    -- Memory
    mem_total_bytes  INTEGER NOT NULL DEFAULT 0,
    mem_used_bytes   INTEGER NOT NULL DEFAULT 0,
    mem_percent      REAL NOT NULL DEFAULT 0,

    -- Swap
    swap_total_bytes INTEGER NOT NULL DEFAULT 0,
    swap_used_bytes  INTEGER NOT NULL DEFAULT 0,

    -- Disk (root partition)
    disk_total_bytes INTEGER NOT NULL DEFAULT 0,
    disk_used_bytes  INTEGER NOT NULL DEFAULT 0,
    disk_percent     REAL NOT NULL DEFAULT 0,

    -- System
    uptime_seconds   REAL NOT NULL DEFAULT 0,
    processes        INTEGER,

    FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
)
"""

# ---------------------------------------------------------------------------
# action_proposals  (Human-in-the-Loop action lifecycle)
# ---------------------------------------------------------------------------
CREATE_PROPOSALS = """
CREATE TABLE IF NOT EXISTS action_proposals (
    id                TEXT PRIMARY KEY,
    node_id           TEXT NOT NULL,
    action            TEXT NOT NULL,
    params_json       TEXT NOT NULL DEFAULT '{}',
    reasoning         TEXT NOT NULL,
    risk_level        TEXT NOT NULL DEFAULT 'MEDIUM',
    status            TEXT NOT NULL DEFAULT 'PENDING',
    created_by        TEXT NOT NULL,
    approved_by       TEXT,
    rejected_by       TEXT,
    rejection_reason  TEXT,
    created_at        REAL NOT NULL,
    updated_at        REAL NOT NULL,
    executed_at       REAL,
    result_json       TEXT,
    FOREIGN KEY (node_id) REFERENCES nodes(id) ON DELETE CASCADE
)
"""

# ---------------------------------------------------------------------------
# Indexes for common query patterns
# ---------------------------------------------------------------------------
CREATE_INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_join_tokens_node_id ON join_tokens(node_id)",
    "CREATE INDEX IF NOT EXISTS idx_join_tokens_consumed ON join_tokens(consumed, expires_at)",
    "CREATE INDEX IF NOT EXISTS idx_worker_tokens_node_id ON worker_tokens(node_id)",
    "CREATE INDEX IF NOT EXISTS idx_worker_tokens_hash ON worker_tokens(token_hash)",
    "CREATE INDEX IF NOT EXISTS idx_nodes_state ON nodes(state)",
    "CREATE INDEX IF NOT EXISTS idx_audit_log_sequence ON audit_log(sequence)",
    "CREATE INDEX IF NOT EXISTS idx_audit_log_node_id ON audit_log(node_id)",
    "CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON audit_log(user_id)",
    "CREATE INDEX IF NOT EXISTS idx_metrics_snapshots_node_time ON metrics_snapshots(node_id, collected_at DESC)",
    "CREATE INDEX IF NOT EXISTS idx_proposals_status ON action_proposals(status)",
    "CREATE INDEX IF NOT EXISTS idx_proposals_node ON action_proposals(node_id)",
]

# All CREATE statements in dependency order
ALL_TABLES = [
    CREATE_NODES,
    CREATE_JOIN_TOKENS,
    CREATE_WORKER_TOKENS,
    CREATE_USERS,
    CREATE_AUDIT_LOG,
    CREATE_METRICS_SNAPSHOTS,
    CREATE_PROPOSALS,
]
